plugins { id 'com.android.application' }

android {
    namespace 'com.andrefiker.quietatc'
    compileSdk 35
    defaultConfig {
        applicationId 'com.andrefiker.quietatc'
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName '1.1.1'
    }
    sourceSets {
        main.assets.srcDirs = ['../../web']
    }
}
