const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../app/src/main/assets/engine.js');
test('seeds 12 illustrated muscle-mapped exercises',()=>{let s=E.seed();assert.equal(s.schema,2);assert.equal(s.exercises.length,12);assert.ok(s.exercises.every(e=>e.visual&&e.primaryMuscles.length));assert.equal(s.settings.dailyCount,8);});
test('daily plan is deterministic, varied by date and balanced',()=>{let s=E.seed(),a=E.planForDate(s,'2026-10-07'),b=E.planForDate(s,'2026-10-07'),c=E.planForDate(s,'2026-10-08');assert.deepEqual(a,b);assert.equal(a.length,8);assert.equal(new Set(a).size,8);assert.notDeepEqual(a,c);let cats=a.map(id=>s.exercises.find(e=>e.id===id).category);assert.ok(cats.includes('upper'));assert.ok(cats.includes('core'));assert.ok(cats.includes('lower'));});
test('one tap marks one entire exercise done and advances',()=>{let s=E.seed();E.start(s,'2026-10-07');let first=s.draft.exerciseIds[0];assert.equal(s.draft.index,0);assert.equal(E.mark(s,'done'),false);assert.equal(s.draft.statuses[first],'done');assert.equal(s.draft.index,1);});
test('skip advances without counting exercise as completed',()=>{let s=E.seed();E.start(s,'2026-10-07');let first=s.draft.exerciseIds[0];E.mark(s,'skipped');assert.equal(s.draft.statuses[first],'skipped');assert.equal(s.draft.index,1);});
test('undo restores previous current exercise and status',()=>{let s=E.seed();E.start(s,'2026-10-07');let first=s.draft.exerciseIds[0];E.mark(s,'done');assert.equal(E.undo(s),true);assert.equal(s.draft.index,0);assert.equal(s.draft.statuses[first],'pending');});
test('finish stores completed/skipped ids and aggregated muscles',()=>{let s=E.seed();E.start(s,'2026-10-07');while(s.draft.index<s.draft.exerciseIds.length){E.mark(s,s.draft.index===1?'skipped':'done');}let out=E.finish(s,123456);assert.equal(out.completedIds.length,7);assert.equal(out.skippedIds.length,1);assert.ok(out.muscles.length>3);assert.equal(s.draft,null);assert.equal(s.sessions.length,1);});
test('cannot finish while exercises remain pending',()=>{let s=E.seed();E.start(s,'2026-10-07');assert.throws(()=>E.finish(s));});
test('daily count respects settings and enabled pool',()=>{let s=E.seed();s.settings.dailyCount=6;assert.equal(E.planForDate(s,'2026-10-07').length,6);s.exercises.slice(2).forEach(e=>e.enabled=false);assert.equal(E.planForDate(s,'2026-10-07').length,2);});
test('v1 data migrates to v2 without discarding exercise names/history',()=>{let legacy={schema:1,exercises:[{id:'seed-5',name:'My Pushups',equipment:'Floor',cue:'Slow',enabled:true}],settings:{theme:'light',haptics:true,keepAwake:true},sessions:[{id:'old',date:'2026-10-01',mode:'main',results:[{exercise:{id:'seed-5'}}],skipped:2}],draft:null};let s=E.validate(legacy);assert.equal(s.schema,2);assert.equal(s.exercises.find(e=>e.id==='seed-5').name,'My Pushups');assert.equal(s.sessions[0].completedIds[0],'seed-5');assert.equal(s.sessions[0].legacySkipped,2);});
test('validation rejects malformed session conflicts',()=>{let s=E.seed();s.sessions.push({id:'x',date:'2026-10-07',exerciseIds:['seed-1'],completedIds:['seed-1'],skippedIds:['seed-1'],muscles:[]});assert.throws(()=>E.validate(s));});
test('muscle aggregation ranks repeated primary work above assists',()=>{let s=E.seed(),m=E.aggregateMuscles(s,['seed-1','seed-3']);assert.equal(m[0].score,4);assert.ok(['glutes','quads'].includes(m[0].name));assert.ok(m.some(x=>x.name==='core'));});
test('completed sessions drive simple totals and streak',()=>{let s=E.seed();for(const date of ['2026-10-05','2026-10-06','2026-10-07']){E.start(s,date);while(s.draft.index<s.draft.exerciseIds.length)E.mark(s,'done');E.finish(s);}let x=E.stats(s,'2026-10-07');assert.equal(x.total,3);assert.equal(x.streak,3);});

test('persisted undo survives validation and can restore the prior exercise',()=>{let s=E.seed();E.start(s,'2026-10-07');let first=s.draft.exerciseIds[0];E.mark(s,'done');let restored=E.validate(s);assert.equal(restored.draft.undo.length,1);assert.equal(E.undo(restored),true);assert.equal(restored.draft.index,0);assert.equal(restored.draft.statuses[first],'pending');});

test('six-movement plans cover all available categories across a month',()=>{let s=E.seed();s.settings.dailyCount=6;for(let day=1;day<=31;day++){let ids=E.planForDate(s,`2026-10-${String(day).padStart(2,'0')}`),categories=new Set(ids.map(id=>s.exercises.find(e=>e.id===id).category));assert.equal(ids.length,6);for(let c of ['warmup','lower','posterior','upper','core'])assert.ok(categories.has(c),c);}});
test('muscle totals exclude skipped movements exactly',()=>{let s=E.seed();E.start(s,'2026-10-07');while(s.draft.index<s.draft.exerciseIds.length)E.mark(s,s.draft.index===0?'done':'skipped');let session=E.finish(s);assert.deepEqual(session.muscles,E.aggregateMuscles(s,session.completedIds));assert.equal(session.completedIds.length,1);assert.equal(session.skippedIds.length,7);});
test('resume sanitizes invalid undo entries without losing valid history',()=>{let s=E.seed();E.start(s,'2026-10-07');E.mark(s,'done');s.draft.undo.push(null,{index:99,statuses:{}},{index:0,statuses:s.draft.statuses});let resumed=E.validate(s);assert.equal(resumed.draft.undo.length,1);assert.ok(E.undo(resumed));assert.equal(resumed.draft.index,0);});
