const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../app/src/main/assets/engine.js');
const main=()=>{let s=E.seed();E.start(s,'main','2026-10-02');return s;};
function complete(s){while(s.draft.index<s.draft.list.length){let r=s.draft.list[s.draft.index];while(r.status!=='done')E.log(s,r.isBaseline?6:s.draft.entry);E.advance(s);}return E.finish(s);}
test('exact 12-exercise seeds and configured targets',()=>{let s=E.seed();assert.equal(s.exercises.length,12);assert.deepEqual(s.schedule,[1,3,5]);assert.deepEqual(s.exercises.map(e=>e.sets),[2,3,3,2,3,3,3,3,3,2,3,2]);assert.deepEqual(s.exercises.map(e=>e.starter),[30,10,10,8,10,0,8,12,15,8,20,15]);});
test('success, partial failure, caps and seconds per set',()=>{let e=E.seed().exercises[1];assert.deepEqual(E.progress(e,[[12],[12],[12]],[[12],[10],[9]]),[[13],[12],[12]]);assert.deepEqual(E.progress(e,[[20]],[[20]]),[[20]]);let p=E.seed().exercises[10];assert.deepEqual(E.progress(p,[[20],[20],[20]],[[20],[19],[25]]),[[25],[20],[25]]);});
test('bilateral success and failure are independent',()=>{let e=E.seed().exercises[3];assert.deepEqual(E.progress(e,[[8,8],[8,8]],[[8,7],[6,8]]),[[9,8],[8,9]]);});
test('push-up first baseline +1, then unmet target repeats',()=>{let e=E.seed().exercises[5];assert.deepEqual(E.progress(e,[[0],[0],[0]],[[7],[5],[3]],true),[[8],[6],[4]]);assert.deepEqual(E.progress(e,[[8],[6],[4]],[[7],[6],[3]]),[[8],[7],[4]]);});
test('finish full workout and restore next targets',()=>{let s=main();complete(s);assert.equal(s.sessions[0].results.length,12);let restored=E.validate(JSON.parse(JSON.stringify(s)));assert.deepEqual(E.targets(restored,restored.exercises[1]),[[11],[11],[11]]);assert.deepEqual(E.targets(restored,restored.exercises[5]),[[7],[7],[7]]);assert.deepEqual(E.targets(restored,restored.exercises[10]),[[25],[25],[25]]);});
test('partial draft persists left-right cursor and results',()=>{let s=main();E.select(s.draft,3);E.log(s,9);let v=E.validate(JSON.parse(JSON.stringify(s)));assert.equal(v.draft.side,1);assert.equal(v.draft.list[3].actual[0][0],9);});
test('undo recorded set and advance preserves original cursor',()=>{let s=main();E.log(s,30);assert.equal(s.draft.set,1);E.undo(s);assert.equal(s.draft.set,0);assert.equal(s.draft.list[0].actual[0][0],null);E.log(s,30);E.log(s,31);E.advance(s);assert.equal(s.draft.index,1);E.undo(s);assert.equal(s.draft.index,0);});
test('skip does not create a progression result',()=>{let s=main();E.advance(s,true);complete(s);assert.equal(s.sessions[0].results.length,11);assert.deepEqual(E.targets(s,s.exercises[0]),[[30],[30]]);});
test('Easy Day exactly five one-round exercises with unchanged main goals',()=>{let s=E.seed(),old=E.targets(s,s.exercises[1]);E.start(s,'easy');assert.deepEqual(s.draft.list.map(r=>r.exercise.id),['seed-0','seed-1','seed-5','seed-9','seed-10']);assert.ok(s.draft.list.every(r=>r.exercise.sets===1));complete(s);assert.deepEqual(E.targets(s,s.exercises[1]),old);assert.equal(E.stats(s).total,0);});
test('explicit easy promotion only changes recorded first set',()=>{let s=E.seed();E.start(s,'easy');while(s.draft.index<s.draft.list.length){let r=s.draft.list[s.draft.index];while(r.status!=='done')E.log(s,50);E.advance(s);}E.finish(s,true);assert.deepEqual(E.targets(s,s.exercises[1]),[[11],[10],[10]]);assert.doesNotThrow(()=>E.validate(s));});
test('reset one progression preserves other exercise history',()=>{let s=main();complete(s);s.exercises[1].generation++;assert.deepEqual(E.targets(s,s.exercises[1]),[[10],[10],[10]]);assert.equal(E.history(s,s.exercises[2]).length,1);assert.equal(s.sessions.length,1);});
test('exercise validation and modifications use normal data model',()=>{let s=E.seed(),e={...s.exercises[1],id:E.uid(),name:'Custom'};s.exercises.push(E.normalizeExercise(e));[s.exercises[0],s.exercises[12]]=[s.exercises[12],s.exercises[0]];s.exercises=s.exercises.filter(e=>e.id!=='seed-0');s.exercises[0].enabled=false;assert.doesNotThrow(()=>E.validate(s));E.start(s,'main');assert.equal(s.draft.list.length,11);assert.throws(()=>E.normalizeExercise({...e,sets:0}));});
test('draft program snapshot stays unchanged after editor changes',()=>{let s=main();s.exercises[1].sets=1;s.exercises[1].name='Renamed';assert.equal(s.draft.list[1].exercise.sets,3);assert.equal(s.draft.list[1].exercise.name,'Goblet Squat');});
test('backup rejects corrupt data and invalid draft cursors',()=>{let s=main();assert.throws(()=>E.validate({...s,schema:5}));s.draft.side=9;assert.throws(()=>E.validate(s));assert.throws(()=>E.validate({...E.seed(),schedule:[]}));});
test('no missed day wipes progression; scheduled streak ignores off days',()=>{let s=main();complete(s);assert.equal(E.stats(s,'2026-10-03').streak,1);assert.equal(E.stats(s,'2026-10-06').streak,0);assert.deepEqual(E.targets(s,s.exercises[1]),[[11],[11],[11]]);});
test('cannot finish with unrecorded exercises or start duplicate session',()=>{let s=main();assert.throws(()=>E.finish(s));assert.throws(()=>E.start(s,'main'));assert.throws(()=>E.log(s,-1));assert.throws(()=>E.log(s,1.5));});
