const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');const {stripTypeScriptTypes}=require('node:module');
function harness(file,hidden=false){let clock=0,id=0,status,cleanup;const tasks=new Map(),instances=[],events=new Map(),updates=[];
class WS{static OPEN=1;constructor(url){this.url=url;this.readyState=0;this.sent=[];instances.push(this);}close(){this.readyState=3;this.onclose?.();}open(){this.readyState=1;this.onopen?.();}message(version,code='ABC123'){this.onmessage?.({data:JSON.stringify({type:'room.update',room:{code,version}})});}send(value){this.sent.push(JSON.parse(value));}}
const window={setTimeout(fn,ms){tasks.set(++id,{fn,at:clock+ms});return id;},clearTimeout(id){tasks.delete(id);},addEventListener(name,fn){events.set(name,fn);},removeEventListener(name,fn){if(events.get(name)===fn)events.delete(name);}};const navigator={onLine:true};const document={visibilityState:hidden?'hidden':'visible',addEventListener:window.addEventListener,removeEventListener:window.removeEventListener};
const context={WebSocket:WS,window,navigator,document,Date:{now:()=>clock},MULTIPLAYER_WS:'wss://example.test/ws',useRef:v=>({current:v}),useState:v=>[v,next=>{if(typeof next==='object')status=next;}],useCallback:fn=>fn,useEffect:fn=>{cleanup=fn();}};
const code=stripTypeScriptTypes(fs.readFileSync(file,'utf8')).replace(/import[^;]+;/g,'').replace('export function','function');vm.runInNewContext(code+';useRoomRealtime("ABC123",room=>updates.push(room));',Object.assign(context,{updates}));
function tick(ms){const end=clock+ms;for(let guard=0;guard<1000;guard++){const due=[...tasks].filter(([,t])=>t.at<=end).sort((a,b)=>a[1].at-b[1].at)[0];if(!due){clock=end;return;}clock=due[1].at;tasks.delete(due[0]);due[1].fn();}throw Error('timer loop');}
return{instances,events,navigator,document,updates,tasks,tick,status:()=>status,cleanup:()=>cleanup(),event:name=>events.get(name)?.(),hide(){document.visibilityState='hidden';events.get('visibilitychange')?.();},show(){document.visibilityState='visible';events.get('visibilitychange')?.();}};}
const before=harness('points-check/room-before.ts');before.tick(150000);assert.equal(before.status().connection,'Connection unavailable');before.event('online');assert.equal(before.instances.length,7);before.hide();before.show();assert.equal(before.instances.length,7);before.cleanup();console.log('REPRODUCED old bug: reconnect exhaustion ignores both network restoration and foreground return.');
const file='points-check/room-after.ts';const a=harness(file);const first=a.instances[0];assert.equal(a.status().connection,'Connecting…');first.open();assert.equal(a.status().connection,'Syncing…');first.message(3);assert.equal(a.status().connection,'Live');const oldMessage=first.onmessage,oldClose=first.onclose;
a.hide();assert.equal(a.status().connection,'Paused');assert.equal(a.tasks.size,0);a.tick(3600000);assert.equal(a.instances.length,1);a.show();assert.equal(a.instances.length,2);assert.equal(a.status().connection,'Connecting…');a.event('focus');a.event('pageshow');assert.equal(a.instances.length,2);const second=a.instances[1];assert.ok(second.url.endsWith('?room=ABC123'));second.open();assert.equal(a.status().connection,'Syncing…');second.message(2);assert.equal(a.status().connection,'Syncing…');second.message(8);assert.equal(a.status().connection,'Live');oldMessage({data:JSON.stringify({type:'room.update',room:{code:'ABC123',version:100}})});oldClose();assert.equal(a.updates.at(-1).version,8);assert.equal(a.status().connection,'Live');a.tick(20000);assert.equal(second.sent[0].type,'room.sync');a.tick(10000);assert.equal(a.status().connection,'Reconnecting…');a.cleanup();assert.equal(a.tasks.size,0);assert.equal(a.events.size,0);
const b=harness(file);b.tick(150000);assert.equal(b.instances.length,7);assert.equal(b.status().connection,'Connection unavailable');b.tick(3600000);assert.equal(b.instances.length,7);b.event('online');assert.equal(b.instances.length,8);b.instances[7].open();b.instances[7].message(4);assert.equal(b.status().connection,'Live');b.cleanup();
const c=harness(file);c.tick(150000);c.hide();c.tick(3600000);c.show();assert.equal(c.instances.length,8);c.instances[7].open();c.instances[7].message(7);assert.equal(c.status().connection,'Live');c.cleanup();
const d=harness(file,true);assert.equal(d.instances.length,0);d.event('online');assert.equal(d.instances.length,0);d.show();assert.equal(d.instances.length,1);d.instances[0].open();d.instances[0].message(2);d.event('pagehide');assert.equal(d.tasks.size,0);d.event('pageshow');assert.equal(d.instances.length,2);d.instances[1].open();d.instances[1].message(3);d.event('freeze');assert.equal(d.status().connection,'Paused');d.event('resume');assert.equal(d.instances.length,3);d.instances[2].open();d.instances[2].message(4);d.navigator.onLine=false;d.event('offline');assert.equal(d.status().connection,'Offline');d.navigator.onLine=true;d.event('online');assert.equal(d.instances.length,4);d.cleanup();
const e=harness(file);e.tick(2000);e.event('focus');assert.equal(e.instances.length,2);e.instances[1].open();e.instances[1].message(9,'OTHER1');assert.equal(e.status().connection,'Syncing…');e.instances[1].message(9);assert.equal(e.status().connection,'Live');e.cleanup();
console.log('PASS: hidden pause/no retries; fresh socket after long background; current snapshot required; missed version8 recovery; stale versions/callbacks blocked; return events coalesced; bounded7 attempts; network/foreground recovery after exhaustion; BFCache pagehide/pageshow; freeze/resume; hidden initial page; offline/online; stuck socket on focus; cleanup.');
