import {Chess} from 'chess.js';import type {Color} from './pieces';export type LocalMove={from:string;to:string;promotion?:string;san?:string};
const pieceValue:Record<string,number>={p:100,n:320,b:335,r:500,q:900,k:20000};
// Custom engine levels, not Elo. Noise is in centipawns; errors choose a legal move.
export const LEVELS=[{depth:0,noise:0,error:1},{depth:1,noise:450,error:.35},{depth:1,noise:260,error:.2},{depth:1,noise:140,error:.08},{depth:1,noise:50,error:0},{depth:2,noise:120,error:0},{depth:2,noise:45,error:0},{depth:2,noise:0,error:0},{depth:3,noise:45,error:0},{depth:3,noise:0,error:0}] as const;
export function buildGame(moves:LocalMove[]){const game=new Chess();for(const move of moves)game.move({from:move.from,to:move.to,promotion:move.promotion});return game;}
function evaluate(game:Chess,perspective:Color){if(game.isCheckmate())return game.turn()===perspective?-100000:100000;if(game.isDraw())return 0;let score=0;for(const row of game.board())for(const piece of row)if(piece)score+=(piece.color===perspective?1:-1)*pieceValue[piece.type];if(game.inCheck())score+=game.turn()===perspective?-25:25;return score;}
function orderedMoves(game:Chess){const priority=(m:{captured?:string;promotion?:string;piece:string})=>(m.captured?10*pieceValue[m.captured]-pieceValue[m.piece]:0)+(m.promotion?pieceValue[m.promotion]:0);return game.moves({verbose:true}).sort((a,b)=>priority(b)-priority(a));}
export function chooseComputerMove(moves:LocalMove[],level:number){const game=buildGame(moves);const candidates=orderedMoves(game);if(!candidates.length||game.isGameOver())return null;const strength=LEVELS[Math.max(0,Math.min(9,Math.round(level)-1))]||LEVELS[4];if(Math.random()<strength.error)return candidates[Math.floor(Math.random()*candidates.length)];const perspective=game.turn() as Color;const deadline=performance.now()+120;let nodes=0;const cutoff={};const checkBudget=()=>{if(++nodes>5000||performance.now()>deadline)throw cutoff;};
function search(depth:number,alpha:number,beta:number,maximizing:boolean):number{checkBudget();if(depth===0||game.isGameOver())return evaluate(game,perspective);let value=maximizing?-Infinity:Infinity;for(const move of orderedMoves(game)){game.move(move);let score:number;try{score=search(depth-1,alpha,beta,!maximizing);}finally{game.undo();}value=maximizing?Math.max(value,score):Math.min(value,score);if(maximizing)alpha=Math.max(alpha,value);else beta=Math.min(beta,value);if(beta<=alpha)break;}return value;}
// Only publish a completely searched iteration: timing cannot favor early root moves.
const noise=candidates.map(()=>((Math.random()-.5)*strength.noise));let best=candidates[0];for(let depth=1;depth<=strength.depth;depth++){let next=best,bestScore=-Infinity;try{for(let i=0;i<candidates.length;i++){checkBudget();game.move(candidates[i]);let score:number;try{score=search(depth-1,bestScore-noise[i],Infinity,false)+noise[i];}finally{game.undo();}if(score>bestScore){bestScore=score;next=candidates[i];}}best=next;}catch(error){if(error!==cutoff)throw error;break;}}return best;}
