import {identityHeaders} from './player-credential';
import {useCallback,useEffect,useState} from 'react';
import {MULTIPLAYER_BASE} from './network';
export type KnightPlayer={id:string;handle:string;quiet_points:number;scored_games:number;wins:number;draws:number;losses:number;current_win_streak:number;best_win_streak:number};
export type RememberedGame={id:string;room_code:string;game_number:number;white_handle:string;black_handle:string;result:string;final_fen:string;moves:{san:string}[];scored:boolean;ended_at:string};
const TOKEN='qk-player-token-v1',PROFILE='qk-player-profile-v1',ACTIVE='qk-player-active-v1';
function read(key:string){try{return localStorage.getItem(key);}catch{return null;}}
function write(key:string,value:string){localStorage.setItem(key,value);}
function cached():KnightPlayer|null{try{const p=JSON.parse(read(PROFILE)||'null');return p&&typeof p.id==='string'&&/^[A-Za-z0-9_-]{3,20}$/.test(p.handle)&&Number.isFinite(p.quiet_points)?p:null;}catch{return null;}}

async function playerRequest(path:string,body?:unknown){const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),8000);try{const response=await fetch(MULTIPLAYER_BASE+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...identityHeaders()},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:controller.signal});const result=await response.json();if(!response.ok)throw Object.assign(new Error(typeof result.error==='string'?result.error:'Knight ID unavailable'),{status:response.status});return result;}finally{window.clearTimeout(timer);}}
export function useKnightId(){
 const[profile,setProfile]=useState(cached);const[active,setActive]=useState(()=>read(ACTIVE)!=='false');const[games,setGames]=useState<RememberedGame[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{if(!navigator.onLine||!identityHeaders().Authorization)return;try{const data=await playerRequest('/players/me');setProfile(data.player);setGames(data.games||[]);try{write(PROFILE,JSON.stringify(data.player));}catch{}setError('');}catch(e){if((e as {status?:number}).status===401){setActive(false);try{write(ACTIVE,'false');}catch{}setError('This device’s Knight ID could not be verified. Guest play remains available.');}}},[]);
 useEffect(()=>{void refresh();window.addEventListener('online',refresh);return()=>window.removeEventListener('online',refresh);},[refresh]);
 async function create(handle:string){if(busy)return;setBusy(true);setError('');try{write('qk-storage-check','1');localStorage.removeItem('qk-storage-check');const result=await playerRequest('/players',{handle});write(TOKEN,result.credential);write(PROFILE,JSON.stringify(result.player));write(ACTIVE,'true');setProfile(result.player);setActive(true);setGames([]);}catch(e){setError(e instanceof DOMException&&e.name==='AbortError'?'The request timed out. Check your connection before trying again.':e instanceof Error?e.message:'Knight ID could not be created');}finally{setBusy(false);}}
 function useGuest(guest:boolean){setActive(!guest);try{write(ACTIVE,String(!guest));}catch{}if(!guest)void refresh();}
 return{player:active?profile:null,profile,active,games,busy,error,create,refresh,useGuest};
}
export function KnightIdPanel({knight,onView}:{knight:ReturnType<typeof useKnightId>;onView?:(game:RememberedGame)=>void}){
 const[handle,setHandle]=useState('');const p=knight.profile;
 return <div className='knight-panel'>{p?<><p className='knight-name'>{p.handle}</p><p className='quiet-points'><strong>{p.quiet_points}</strong> Quiet Points</p><p className='settings-note'>{p.scored_games} scored games · {p.wins} wins · {p.draws} draws · {p.losses} losses<br/>{p.scored_games?Math.round(100*p.wins/p.scored_games):0}% wins · Streak {p.current_win_streak} · Best {p.best_win_streak}</p><label className='preference-row'><span>Play as a guest</span><input type='checkbox' checked={!knight.active} onChange={e=>knight.useGuest(e.target.checked)}/></label></>:<form onSubmit={e=>{e.preventDefault();void knight.create(handle);}}><p>Your name at the table. Always optional.</p><label htmlFor='knight-handle'>Choose your handle</label><input id='knight-handle' aria-label='Knight ID handle' value={handle} onChange={e=>setHandle(e.target.value)} pattern='[A-Za-z0-9_-]{3,20}' minLength={3} maxLength={20} autoComplete='off' autoCapitalize='none' spellCheck={false} required/><small>3–20 letters, numbers, underscores or hyphens.</small><button className='primary wide' disabled={knight.busy||!navigator.onLine} type='submit'>{knight.busy?'Creating…':'Create Knight ID'}</button></form>}{knight.error?<p role='alert'>{knight.error}</p>:null}<p className='settings-note'>This Knight ID lives on this device. Passkey recovery is not available yet. Clearing browser storage can permanently lose access.</p><details className='knight-details'><summary>About Quiet Points</summary><p>Win +3 · Draw +1 · Loss +0. Human games with two different Knight IDs only. The first three scored games between a pair within 24 hours award points; further rematches are casual. This is not a chess rating.</p></details>{p&&knight.games.length?<details className='knight-details'><summary>Recent games</summary>{knight.games.slice(0,5).map(g=><button className='memory-game' type='button' key={g.id} onClick={()=>onView?.(g)} disabled={!onView}><span>{g.white_handle} · {g.black_handle}</span><small>{g.result} · {Math.ceil(g.moves.length/2)} moves{g.scored?'':' · Casual'}</small></button>)}</details>:null}</div>;
}
