import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,makeDeck,isValidSequence,canTableauAccept,canFoundationAccept,drawFromStock,moveCards,undo,legalMove,legalMoves,getHint,isWon,serialize,restore,autoFinishSafe} from '../src/engine.js';

const card=(suit,rank,faceUp=true)=>({suit,rank,faceUp});
function fixture(){const g=newGame(7,1);g.stock=[];g.waste=[];g.foundations=[[],[],[],[]];g.tableau=Array.from({length:7},()=>[]);g.history=[];g.moves=0;g.score=0;return g}

test('new deal contains all 52 unique cards and correct tableau distribution',()=>{const g=newGame(2026);const all=[...g.stock,...g.tableau.flat()];assert.equal(all.length,52);assert.equal(new Set(all.map(c=>`${c.suit}-${c.rank}`)).size,52);assert.deepEqual(g.tableau.map(c=>c.length),[1,2,3,4,5,6,7]);for(const col of g.tableau)assert.equal(col.at(-1).faceUp,true);assert.equal(g.stock.length,24)});
test('seeded game number reproduces exact deal',()=>{const a=newGame(515151,3),b=newGame(515151,3);assert.deepEqual(a.stock,b.stock);assert.deepEqual(a.tableau,b.tableau);assert.deepEqual(a.foundations,b.foundations)});
test('tableau requires descending rank and alternating colors',()=>{assert.equal(canTableauAccept(card('hearts',7),card('clubs',8)),true);assert.equal(canTableauAccept(card('hearts',7),card('diamonds',8)),false);assert.equal(canTableauAccept(card('hearts',7),card('clubs',9)),false);assert.equal(canTableauAccept(card('clubs',13),null),true);assert.equal(canTableauAccept(card('clubs',12),null),false)});
test('face-up sequence validation checks order, alternating colors and face-up state',()=>{assert.equal(isValidSequence([card('spades',10),card('hearts',9),card('clubs',8)]),true);assert.equal(isValidSequence([card('spades',10),card('clubs',9)]),false);assert.equal(isValidSequence([card('spades',10),card('hearts',8)]),false);assert.equal(isValidSequence([card('spades',10),card('hearts',9,false)]),false)});
test('foundation accepts only suited ascending cards beginning with Ace',()=>{assert.equal(canFoundationAccept(card('spades',1),[]),true);assert.equal(canFoundationAccept(card('spades',2),[]),false);assert.equal(canFoundationAccept(card('spades',2),[card('spades',1)]),true);assert.equal(canFoundationAccept(card('hearts',2),[card('spades',1)]),false)});
test('legal sequence movement and reveal-on-move are atomic',()=>{const g=fixture();g.tableau[0]=[card('clubs',9,false),card('spades',8),card('hearts',7)];g.tableau[1]=[card('diamonds',9)];assert.equal(moveCards(g,{type:'tableau',index:0},{type:'tableau',index:1},1),true);assert.equal(g.tableau[0].length,1);assert.equal(g.tableau[0][0].faceUp,true);assert.deepEqual(g.tableau[1].slice(1).map(c=>c.rank),[8,7]);assert.equal(g.moves,1)});
test('empty tableau accepts only a King sequence; illegal moves do not alter state',()=>{const g=fixture();g.tableau[0]=[card('hearts',12)];const before=serialize(g);assert.equal(legalMove(g,{type:'tableau',index:0},{type:'tableau',index:1}),false);assert.equal(serialize(g),before);g.tableau[0]=[card('hearts',13),card('clubs',12)];assert.equal(legalMove(g,{type:'tableau',index:0},{type:'tableau',index:1},0),true)});
test('Draw 1 reveals one card and recycling restores draw order',()=>{const g=newGame(1,1);const original=[...g.stock].reverse().map(c=>`${c.suit}-${c.rank}`);drawFromStock(g);assert.equal(g.waste.length,1);assert.equal(g.stock.length,23);while(g.stock.length)drawFromStock(g);assert.equal(g.stock.length,0);drawFromStock(g);assert.equal(g.waste.length,0);assert.equal(g.stock.length,24);drawFromStock(g);assert.equal(`${g.waste.at(-1).suit}-${g.waste.at(-1).rank}`,original[0])});
test('Draw 3 exposes only the final drawn card and cycles consistently',()=>{const g=newGame(999,3);const first=[...g.stock].slice(-3).reverse();drawFromStock(g);assert.equal(g.waste.length,3);assert.deepEqual(g.waste.map(c=>`${c.suit}-${c.rank}`),first.map(c=>`${c.suit}-${c.rank}`));assert.equal(g.waste.at(-1).faceUp,true);assert.equal(g.stock.length,21);while(g.stock.length)drawFromStock(g);drawFromStock(g);assert.equal(g.stock.length,24);assert.equal(g.waste.length,0)});
test('waste and foundation moves, including foundation back to tableau',()=>{const g=fixture();g.waste=[card('hearts',1)];assert.equal(moveCards(g,{type:'waste'},{type:'foundation',index:0}),true);g.tableau[0]=[card('clubs',2)];assert.equal(moveCards(g,{type:'foundation',index:0},{type:'tableau',index:0}),true);assert.equal(g.foundations[0].length,0);assert.equal(g.tableau[0].at(-1).rank,1)});
test('undo restores exact board state and can be repeated',()=>{const g=newGame(45,1);const before=JSON.stringify({stock:g.stock,waste:g.waste,foundations:g.foundations,tableau:g.tableau,moves:g.moves,score:g.score});drawFromStock(g);drawFromStock(g);assert.equal(undo(g),true);assert.equal(undo(g),true);assert.equal(JSON.stringify({stock:g.stock,waste:g.waste,foundations:g.foundations,tableau:g.tableau,moves:g.moves,score:g.score}),before);assert.equal(undo(g),false)});
test('won state requires all 52 cards on foundations',()=>{const g=fixture();g.foundations=Array.from({length:4},(_,i)=>Array.from({length:13},(_,j)=>card(['hearts','diamonds','clubs','spades'][i],j+1)));assert.equal(isWon(g),true);g.foundations[0].pop();assert.equal(isWon(g),false)});
test('auto-finish safety follows foundation suits when Aces occupy arbitrary slots',()=>{const g=fixture();g.stock=[];g.waste=[];g.foundations=[[...Array.from({length:8},(_,i)=>card('hearts',i+1))],[...Array.from({length:8},(_,i)=>card('clubs',i+1))],[...Array.from({length:3},(_,i)=>card('spades',i+1))],[...Array.from({length:3},(_,i)=>card('diamonds',i+1))]];g.tableau[0]=[card('hearts',10)];assert.equal(autoFinishSafe(g),false)});
test('auto-finish requires a foundation-only path through every remaining card',()=>{
  const g=fixture();
  g.foundations=['hearts','diamonds','clubs','spades'].map(suit=>Array.from({length:11},(_,i)=>card(suit,i+1)));
  g.tableau[0]=[card('hearts',13),card('hearts',12)];
  g.tableau[1]=[card('diamonds',13),card('diamonds',12)];
  g.tableau[2]=[card('clubs',13),card('clubs',12)];
  g.tableau[3]=[card('spades',13),card('spades',12)];
  const before=serialize(g);
  assert.equal(autoFinishSafe(g),true);
  assert.equal(serialize(g),before);
  g.tableau[0].reverse();
  assert.equal(autoFinishSafe(g),false);
});
test('foundation-to-tableau rule rejects incorrect rank/color',()=>{const g=fixture();g.foundations[0]=[card('hearts',1)];g.tableau[0]=[card('diamonds',3)];assert.equal(legalMove(g,{type:'foundation',index:0},{type:'tableau',index:0}),false);g.tableau[0]=[card('clubs',2)];assert.equal(legalMove(g,{type:'foundation',index:0},{type:'tableau',index:0}),true)});
test('hints prefer revealing a hidden tableau card over a foundation return',()=>{const g=fixture();g.foundations[0]=[card('hearts',1)];g.tableau[0]=[card('spades',8,false),card('hearts',7)];g.tableau[1]=[card('clubs',8)];g.tableau[2]=[card('clubs',2)];const hint=getHint(g);assert.equal(hint.source.type,'tableau');assert.equal(hint.source.index,0);assert.equal(hint.dest.index,1);assert.equal(legalMove(g,hint.source,hint.dest,hint.cardIndex),true)});
test('hint identifies recycling the waste when no board move exists',()=>{const g=fixture();g.waste=[card('hearts',5)];const hint=getHint(g);assert.equal(hint.source.type,'stock');assert.equal(hint.dest.type,'waste')});
test('serialized state retains the full undo history',()=>{const g=newGame(909,1);drawFromStock(g);const copy=restore(serialize(g));assert.equal(copy.waste.length,1);assert.equal(copy.history.length,1);assert.equal(undo(copy),true);assert.equal(copy.waste.length,0)});
test('scripted play across multiple seeded games preserves all 52 cards',()=>{for(const seed of [13,27,51,94,2026]){const g=newGame(seed,seed%2?1:3);for(let turn=0;turn<240&&g.status==='playing';turn++){const moves=legalMoves(g).filter(m=>m.source.type!=='foundation');if(moves.length){const choice=moves.find(m=>m.dest.type==='tableau'&&g.tableau[m.source.index]?.some(c=>!c.faceUp))||moves[0];moveCards(g,choice.source,choice.dest,choice.cardIndex)}else if(g.stock.length||g.waste.length)drawFromStock(g);else break;const cards=[...g.stock,...g.waste,...g.foundations.flat(),...g.tableau.flat()];assert.equal(cards.length,52);assert.equal(new Set(cards.map(c=>`${c.suit}-${c.rank}`)).size,52);assert.ok(g.tableau.every(col=>col.every((c,i)=>!c.faceUp||col.slice(i).every(x=>x.faceUp))))}}});
