import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/tmp/impact-local-tools/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const errors=[];const requests=[];page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.route('http://impact.test/**',async r=>{let p=new URL(r.request().url()).pathname;if(p==='/')p='/index.html';try{const body=await fs.readFile(path.join(process.cwd(),'dist',p));await r.fulfill({status:200,body,contentType:p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.html')?'text/html':p.endsWith('.json')?'application/json':'application/octet-stream'});}catch{await r.fulfill({status:404,body:'Not found'})}});
await fs.mkdir('qa/v2.2',{recursive:true});await page.addInitScript(()=>{if(!localStorage.getItem('exhibition-qa-started')){localStorage.setItem('impact-core-settings',JSON.stringify({view:'cutaway',tool:'impact',quality:'mobile'}));localStorage.setItem('exhibition-qa-started','1');}});await page.goto('http://impact.test/');await page.waitForFunction(()=>window.__core?.ready,{timeout:60000});const shot=async n=>{await page.waitForTimeout(130);await page.screenshot({path:'qa/v2.2/'+n+'.png'});};const tap=async()=>{const xy=await page.evaluate(()=>window.__core.projectPoint(-.06,.12,.12));await page.touchscreen.tap(...xy);};
if(await page.locator('#views').isVisible())throw Error('Legacy layer UI exposed');if(await page.locator('#speed').inputValue()!=='0.25')throw Error('Not slow by default');await shot('final-baseline');const profiles=[];
for(const weapon of ['pistol','rifle','shotgun']){await page.locator('#reset').click();await page.locator('[data-focus="torso"]').click();await page.locator('[data-weapon="'+weapon+'"]').click();await tap();await page.locator('#apply').click();await page.evaluate(()=>window.__core.seekReplay(5));await page.evaluate(()=>window.__core.setCamera(.4,.12,.95));await shot(weapon+'-approach');await page.evaluate(()=>window.__core.seekReplay(32));await shot(weapon+'-cavity');const a=await page.locator('canvas').screenshot();await page.evaluate(()=>{window.__core.seekReplay(70);window.__core.seekReplay(32)});await page.waitForTimeout(130);if(!a.equals(await page.locator('canvas').screenshot()))throw Error('Replay differs '+weapon);const animated=await page.evaluate(()=>window.__core.animation());if(animated.group!==(weapon==='shotgun'?3:1))throw Error('Wrong shot group');await page.evaluate(()=>window.__core.finishReplay());await shot(weapon+'-settled');profiles.push(await page.evaluate(()=>({animation:window.__core.animation(),events:window.__core.events(),physics:window.__core.physics(),gel:window.__core.gel()})));}
const saved=await page.evaluate(()=>window.__core.save());await page.reload();await page.waitForFunction(()=>window.__core?.ready,{timeout:60000});if(await page.evaluate(()=>window.__core.save())!==saved)throw Error('Reload state');await page.evaluate(()=>window.__core.seekReplay(32));if(await page.evaluate(()=>window.__core.animation().tips.length)!==3)throw Error('Reload pellet replay lost');await shot('shotgun-reloaded');await page.evaluate(()=>window.__core.finishReplay());await page.locator('#undo').click();if(await page.evaluate(()=>window.__core.events().length)!==0)throw Error('Undo not whole shot');
await page.locator('[data-focus="torso"]').click();await tap();for(let i=0;i<3;i++){await page.locator('#apply').click();await page.evaluate(()=>window.__core.finishReplay());}if(await page.evaluate(()=>window.__core.events().length)!==9)throw Error('Repeated scatter count');await shot('repeated-scatter');await page.locator('#undo').click();if(await page.evaluate(()=>window.__core.events().length)!==6)throw Error('Partial scatter undo');const before=await page.evaluate(()=>window.__core.save());for(const q of ['ultra','balanced','mobile'])await page.locator('#quality').selectOption(q);if(await page.evaluate(()=>window.__core.save())!==before)throw Error('Quality reset');
await page.locator('#reset').click();await page.locator('[data-focus="head"]').click();await page.locator('[data-weapon="pistol"]').click();const head=await page.evaluate(()=>window.__core.projectPoint(-.035,.51,.065));await page.touchscreen.tap(...head);await page.locator('#apply').click();await page.evaluate(()=>window.__core.seekReplay(32));await shot('head-animation');await page.evaluate(()=>window.__core.finishReplay());await page.locator('#reset').click();await page.locator('#home').click();await shot('final-reset');if(await page.evaluate(()=>window.__core.gel().meshes)!==0)throw Error('Reset cavity leak');await page.setViewportSize({width:360,height:640});await shot('small-phone');await page.setViewportSize({width:844,height:390});await shot('landscape');await page.setViewportSize({width:390,height:844});
// Actual controls: pause, scrub, resume from the selected frame, then finish.
await page.locator('[data-focus="torso"]').click();await tap();await page.locator('#apply').click();await page.locator('#replay').click();if(await page.evaluate(()=>window.__core.replayState().playing))throw Error('Pause failed');await page.locator('#timeline').fill('30');await page.locator('#timeline').dispatchEvent('input');await page.locator('#replay').click();const resumed=await page.evaluate(()=>window.__core.replayState());if(!resumed.playing||resumed.frame<30)throw Error('Resume reset');await page.evaluate(()=>window.__core.finishReplay());
const report={environment:'Chrome138 SwiftShader Linux 390x844 DPR1',errors,offlineAssets:requests.every(u=>u.startsWith('http://impact.test/')),gelOnly:true,profiles:profiles.map(p=>({weapon:p.animation.weapon,pellets:p.animation.group,pathEndpoints:p.events.map(e=>e.end),energies:p.physics.records.map(r=>r.path[0].energyIn),eventCpuMs:p.physics.simulationTimes.at(-1),cavitySegments:p.gel.meshes})),replayByteIdentical:true,groupUndo:true,groupReload:true,repeatShots:true,qualityStateEquivalent:true,pauseScrubResume:true,reset:true};await fs.writeFile('qa/v2.2/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();if(errors.length)process.exitCode=1;
