import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/tmp/impact-local-tools/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});const errors=[];const requests=[];page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.route('http://impact.test/**',async r=>{let p=new URL(r.request().url()).pathname;if(p==='/')p='/index.html';try{const body=await fs.readFile(path.join(process.cwd(),'dist',p));await r.fulfill({status:200,body,contentType:p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.html')?'text/html':p.endsWith('.json')?'application/json':'application/octet-stream'});}catch{await r.fulfill({status:404,body:'Not found'})}});
await page.goto('http://impact.test/');await page.waitForFunction(()=>window.__core?.ready,{timeout:60000});await fs.mkdir('qa/v2.1',{recursive:true});
const shot=async n=>{await page.waitForTimeout(180);await page.screenshot({path:'qa/v2.1/'+n+'.png'});};
const tap=async p=>{const xy=await page.evaluate(p=>window.__core.projectPoint(...p),p);await page.touchscreen.tap(...xy);};
const settle=async()=>{await page.waitForFunction(()=>!window.__core.replayState().playing,{timeout:15000});};
const fire=async()=>{await page.locator('#apply').click();await settle();};
const saved=()=>page.evaluate(()=>window.__core.save());
await page.locator('[data-focus="torso"]').click();await shot('baseline');await page.locator('[data-tool="projectile"]').click();const ribTarget=await page.evaluate(()=>{for(let y=.11;y<.20;y+=.006)for(let x=-.09;x<-.035;x+=.008){const p=window.__core.probePoint(x,y,.1);if(p.fractures?.some(id=>id.includes('rib')))return p.point;}return null;});if(!ribTarget)throw Error('No rib target found');console.log('ribTarget',ribTarget);await tap(ribTarget);await fire();await shot('rib-skin');let physics=await page.evaluate(()=>window.__core.physics());if(physics.fragments<1||physics.records[0].path.length<2)throw Error('Core bone/path gate failed');
await page.locator('[data-view="skeleton"]').click();await shot('rib-fracture');await page.evaluate(()=>window.__core.setCamera(.35,.12,.75));await shot('rib-fracture-oblique');
await page.locator('[data-view="skin"]').click();await shot('gel-oblique');await page.evaluate(()=>window.__core.seekReplay(28));await shot('gel-temporary-cavity');await page.evaluate(()=>window.__core.finishReplay());await page.locator('[data-view="skeleton"]').click();const finalState=await saved();await page.evaluate(()=>window.__core.seekReplay(0));await shot('replay-start');await page.evaluate(()=>window.__core.seekReplay(23));const replayA=await page.locator('canvas').screenshot();await shot('replay-compression');await page.evaluate(()=>window.__core.seekReplay(67));await page.evaluate(()=>window.__core.seekReplay(23));await page.waitForTimeout(200);const replayB=await page.locator('canvas').screenshot();if(!replayA.equals(replayB))throw Error('Replay render nondeterminism');await page.evaluate(()=>window.__core.finishReplay());if(await saved()!==finalState)throw Error('Replay mutated persistent state');
await page.locator('[data-view="cutaway"]').click();await shot('post-event-free');for(const mode of ['axial','coronal','sagittal']){await page.locator('#section-mode').selectOption(mode);await shot('post-event-'+mode);}await page.locator('#section-mode').selectOption('free');await page.locator('#section').fill('62');await page.locator('#section').dispatchEvent('input');await shot('section-offset');await page.locator('#section').fill('50');await page.locator('#section').dispatchEvent('input');await page.locator('[data-view="skin"]').click();await page.locator('[data-focus="torso"]').click();
const checkpoints=[];for(let i=1;i<10;i++){await page.evaluate(()=>{window.__core.finishReplay();window.__core.apply();window.__core.finishReplay();});if(i===4||i===9){await shot('repeated-'+(i+1));checkpoints.push(await page.evaluate(()=>window.__core.physics()));}}
await page.evaluate(()=>window.__core.setCamera(.5,.12,.7));await shot('repeated-gel-oblique');const gel=await page.evaluate(()=>window.__core.gel());if(!gel.tracks.some(t=>t.count>1))throw Error('Repeated cavities not merged');await page.locator('[data-view="skeleton"]').click();await shot('repeated-bone');await page.locator('[data-view="cutaway"]').click();await shot('repeated-cutaway');const stored=await saved();await page.reload();await page.waitForFunction(()=>window.__core?.ready,{timeout:60000});if(await saved()!==stored)throw Error('Reload lost state');await shot('reload-cutaway');await page.locator('#undo').click();if(await page.evaluate(()=>window.__core.events().length)!==9)throw Error('Undo lost count');
const quality=[];for(const mode of ['mobile','balanced','ultra']){const before=await saved();await page.locator('#quality').selectOption(mode);await shot('quality-'+mode);if(await saved()!==before)throw Error('Quality altered physics');const metrics=await page.evaluate(async()=>{const a=[];const began=performance.now();let last=began;for(let i=0;i<16;i++){window.__core.setCamera(.4+Math.sin(i*.1)*.06,.10,.8);const now=await new Promise(requestAnimationFrame);if(i>5)a.push(now-last);last=now;if(performance.now()-began>5000)break;}return {rafFps:1000/(a.reduce((a,b)=>a+b,0)/a.length),frameMs:a,memory:window.__core.renderer().memory,fragments:window.__core.physics().fragments};});quality.push({mode,...metrics});}
await page.locator('#reset').click();if(await page.evaluate(()=>window.__core.physics().fragments)!==0)throw Error('Reset leaked fragments');await page.locator('[data-view="skin"]').click();await page.locator('[data-focus="head"]').click();await tap([-.035,.51,.065]);await fire();await page.locator('[data-view="skeleton"]').click();await shot('head-fracture');await page.locator('[data-view="organs"]').click();await shot('brain-displacement');await page.locator('[data-view="cutaway"]').click();await shot('head-cutaway');
await page.locator('#reset').click();await page.locator('[data-view="skin"]').click();await page.locator('[data-focus="torso"]').click();await tap([.045,-.09,.13]);await fire();await page.locator('[data-view="organs"]').click();await shot('abdomen-displacement');await page.locator('#inspect').click();await shot('event-inspector');await page.locator('#close-inspect').click();
await page.locator('#reset').click();await page.locator('[data-view="skin"]').click();await page.locator('[data-focus="torso"]').click();await shot('reset');await page.setViewportSize({width:360,height:640});await shot('small-phone');await page.setViewportSize({width:844,height:390});await shot('landscape');
if(errors.length)throw Error(errors.join('\n'));const report={gel,errors,offlineAssets:requests.every(u=>u.startsWith('http://impact.test/')),boneFracture:true,pathReaction:true,persistentCutaway:true,replayByteIdentical:true,persistence:true,qualityStateEquivalent:true,checkpoints:checkpoints.map(p=>({fragments:p.fragments,simulationTimes:p.simulationTimes})),quality,environment:'Chrome 138 / SwiftShader / Linux / 390x844 DPR2 with mode-dependent render resolution. Software browser, not phone FPS.'};await fs.writeFile('qa/v2.1/browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
