import fs from 'node:fs/promises';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/tmp/impact-local-tools/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const errors=[];const requests=[];page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.route('http://impact.test/**',async r=>{let p=new URL(r.request().url()).pathname;if(p==='/')p='/index.html';try{const body=await fs.readFile(path.join(process.cwd(),'dist',p));await r.fulfill({status:200,body,contentType:p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.html')?'text/html':p.endsWith('.json')?'application/json':'application/octet-stream'});}catch{await r.fulfill({status:404,body:'Not found'})}});
await page.goto('http://impact.test/');await page.waitForFunction(()=>window.__core?.ready,{timeout:60000});await fs.mkdir('qa',{recursive:true});
await page.evaluate(()=>window.__core.setCamera(.7,.04,.85));await page.waitForTimeout(350);await page.touchscreen.tap(195,350);if(await page.locator('#apply').isDisabled())throw Error('Rotated/zoomed pick failed');await page.locator('#apply').click();if(await page.evaluate(()=>window.__core.events().length)!==1)throw Error('Rotated apply failed');
await page.evaluate(()=>{window.__core.reset();window.__core.setView('cutaway')});await page.waitForTimeout(350);const before=await page.evaluate(()=>window.__core.renderer().memory.geometries);for(let i=0;i<4;i++){await page.evaluate(()=>{window.__core.setView('skin');window.__core.setView('cutaway')});await page.waitForTimeout(100);}const after=await page.evaluate(()=>window.__core.renderer().memory.geometries);if(after>before+1)throw Error('Section geometries leaked');
await page.route('**/models/torso.glb',r=>r.fulfill({status:404,body:'missing'}));await page.reload();await page.waitForFunction(()=>document.querySelector('#loading')?.textContent.includes('Unable to load'));console.log(JSON.stringify({rotatedZoomedPick:'PASS',apply:'PASS',sectionDisposal:{before,after},missingAssetError:'PASS'}));await fs.writeFile('qa/resilience-report.json',JSON.stringify({rotatedZoomedPick:true,apply:true,sectionGeometriesBefore:before,sectionGeometriesAfter:after,missingAssetError:true},null,2));await browser.close();
