import { createGame, startHand, act, draw, settle, assertInvariants, type GameState, type Variant } from '../engine/index.js';
import { decideBot } from './bot.js'; import { observation, publicView, playerView, type SeatOwner } from './views.js'; import type { Command, PlayerTableView } from './protocol.js'; import type { Store, StoredTable } from './store.js';
type OwnerState = Record<string, SeatOwner & { style?: 'cautious' | 'balanced' | 'aggressive' }>;
const ownersOf = (raw: Record<string, unknown>) => raw as OwnerState;
export class TableService {
  constructor(private readonly store: Store, readonly tableId = 'main') {}
  async initialize(): Promise<void> { await this.store.transaction(async (c) => { if (await this.store.loadForUpdate(c, this.tableId)) return; const state = createGame('HOLD_EM_NO_LIMIT', [{ id: 'seat-0', seat: 0 }, { id: 'seat-1', seat: 1 }]); await c.query('insert into poker_tables(id,version,state,owners) values($1,0,$2,$3)', [this.tableId, JSON.stringify(state), JSON.stringify({})]); }); }
  private view(t: StoredTable, guestId: string | null): PlayerTableView { const owners = ownersOf(t.owners); const entries = new Map<number, SeatOwner>(); for (const [seat, owner] of Object.entries(owners)) entries.set(Number(seat), owner); const ownSeat = Object.entries(owners).find(([, o]) => o.guestId === guestId)?.[0]; const base = publicView(t.id, t.version, t.state, entries, t.deadline, t.nextVariant as Variant | null); return playerView(base, t.state, ownSeat === undefined ? null : Number(ownSeat)); }
  async snapshot(guestId: string | null): Promise<PlayerTableView> { return this.store.transaction(async (c) => { const t = await this.store.loadForUpdate(c, this.tableId); if (!t) throw new Error('Missing permanent table'); return this.view(t, guestId); }); }
  async command(guestId: string, command: Command): Promise<PlayerTableView> { if (command.protocolVersion !== 1 || command.tableId !== this.tableId || !command.actionId) throw new Error('invalid_protocol'); return this.store.transaction(async (c) => { const t = await this.store.loadForUpdate(c, this.tableId); if (!t) throw new Error('missing_table'); const duplicate = await this.store.receipt(c, t.id, command.actionId); if (duplicate) return duplicate as PlayerTableView; if (command.expectedVersion !== t.version) throw new Error('stale_command'); const owners = ownersOf(t.owners); let state = t.state; let nextVariant = t.nextVariant; const seat = Object.entries(owners).find(([, o]) => o.guestId === guestId)?.[0]; if (command.type === 'sit') { if (state.phase !== 'WAITING' && state.phase !== 'INTERMISSION') throw new Error('wait_for_next_hand'); if (command.seat === undefined || command.seat < 0 || command.seat > 4 || owners[String(command.seat)]) throw new Error('seat_unavailable'); owners[String(command.seat)] = { guestId, name: `Guest ${guestId.slice(0, 4)}`, bot: false, connected: true }; }
    else if (command.type === 'bot') { if (state.phase !== 'WAITING' && state.phase !== 'INTERMISSION') throw new Error('bots_change_between_hands'); if (command.seat === undefined || owners[String(command.seat)]) throw new Error('seat_unavailable'); owners[String(command.seat)] = { guestId: `bot-${command.seat}`, name: `Pat ${command.seat + 1}`, bot: true, connected: true, style: command.botStyle ?? 'balanced' }; }
    else if (command.type === 'queueVariant') { if (seat === undefined || state.phase !== 'WAITING' && state.phase !== 'INTERMISSION' || !command.variant) throw new Error('variant_not_allowed'); nextVariant = command.variant; }
    else { if (seat === undefined) throw new Error('not_seated'); const p = state.players.find((x) => x.seat === Number(seat)); if (!p || state.actorId !== p.id) throw new Error('not_your_turn'); if (command.handId !== state.handNumber || command.turnId !== `${state.handNumber}:${state.actorId}`) throw new Error('stale_turn'); state = command.type === 'draw' ? draw(state, p.id, command.indexes ?? []) : act(state, p.id, command.action!); if (state.phase === 'SHOWDOWN') state = settle(state); }
    assertInvariants(state); const updated: StoredTable = { ...t, version: t.version + 1, state, owners, nextVariant, deadline: state.actorId ? Date.now() + 30_000 : null }; const response = this.view(updated, guestId); await this.store.save(c, updated); await this.store.saveReceipt(c, t.id, command.actionId, updated.version, response); return response;
  }); }
  async startIfReady(): Promise<void> { await this.store.transaction(async (c) => { const t = await this.store.loadForUpdate(c, this.tableId); if (!t || !['WAITING','INTERMISSION'].includes(t.state.phase)) return; const owners = ownersOf(t.owners); const occupied = Object.entries(owners); if (occupied.length < 2 || !occupied.some(([, o]) => !o.bot)) return; const variant = (t.nextVariant as Variant | null) ?? t.state.variant; const seating = occupied.map(([seat, o]) => ({ id: o.guestId, seat: Number(seat), stack: 1000 })); const state = startHand(createGame(variant, seating, t.state.buttonSeat)); await this.store.save(c, { ...t, version: t.version + 1, state, nextVariant: null, deadline: state.actorId ? Date.now() + 30_000 : null }); }); }
  async botTurn(): Promise<void> { const snapshot = await this.snapshot(null); const bot = snapshot.seats.find((s) => s.bot && s.seat === snapshot.actorSeat); if (!bot) return; const owners = (await this.store.transaction(async (c) => (await this.store.loadForUpdate(c, this.tableId))!)).owners as OwnerState; const owner = owners[String(bot.seat)]!; const t = await this.store.transaction(async (c) => (await this.store.loadForUpdate(c, this.tableId))!); const action = decideBot(observation(t.state, bot.seat), owner.style ?? 'balanced', { next: () => .5 }); await this.command(owner.guestId, { protocolVersion: 1, tableId: this.tableId, actionId: crypto.randomUUID(), expectedVersion: t.version, handId: t.state.handNumber, turnId: `${t.state.handNumber}:${t.state.actorId}`, type: 'action', action }); }
}
