const assert=require('node:assert/strict');
const P=require('../progression.js');
const LV=require('../levels-v2.js');
const defs={road:{dens:.009},wood:{dens:.004},steel:{dens:.008},cable:{dens:.0015},aluminum:{dens:.0024},concrete:{dens:.015},composite:{dens:.0017}};
const compact={nodes:[[0,0],[1,0],[2,0]],beams:[[0,1,'road'],[1,2,'road'],[0,2,'wood']]};
const fake={...LV.LEVELS[0],brief:{maxBeams:3,reward:30}};
assert(P.briefMet(fake,compact,defs,100,50));
fake.brief.maxBeams=2; assert(!P.briefMet(fake,compact,defs,100,50));
const anchored={nodes:[[13,10],[14,10],[15,10]],beams:[[0,1,'road'],[1,2,'wood']]};
const support={...LV.LEVELS[2]};
assert(P.briefMet(support,anchored,defs,1000,70));
const noAnchor={nodes:[[1,1],[2,1]],beams:[[0,1,'wood']]};
assert(!P.briefMet(support,noAnchor,defs,1000,70));
const state=P.normalize(null);
const awardLv={...LV.LEVELS[0],budget:1000,brief:{label:'Teste',note:'Teste',maxBeams:3,reward:37}};
let out=P.award(state,awardLv,300,50,{design:compact,defs,beams:[]});
assert.equal(out.brief,true); assert.equal(state.briefs[awardLv.id],true);
const xp=state.xp; out=P.award(state,awardLv,300,50,{design:compact,defs,beams:[]});
assert.equal(out.brief,false); assert.equal(state.xp,xp,'brief reward cannot be farmed');
console.log('VÃO engineering briefs evaluate and reward once');
