import * as THREE from 'three';import type {Structure} from './anatomy';import {MAX_EVENTS,localDamage,type DamageEvent} from './damage';
export function installDamageMaterial(s:Structure){const mat=s.mesh.material,previous=mat.onBeforeCompile.bind(mat);s.mesh.geometry.setAttribute('restPosition',new THREE.BufferAttribute(s.base,3));const uniforms={uDamageCount:{value:0},uDamagePoints:{value:Array.from({length:MAX_EVENTS*2},()=>new THREE.Vector4())},uDamageWeights:{value:Array.from({length:MAX_EVENTS*2},()=>new THREE.Vector2())},uDamageNormals:{value:Array.from({length:MAX_EVENTS*2},()=>new THREE.Vector3())},uLayer:{value:s.layer==='skin'?0:s.layer==='muscle'?1:s.layer==='bone'?2:3}};mat.userData.damage=uniforms;
mat.onBeforeCompile=(shader,r)=>{previous(shader,r);Object.assign(shader.uniforms,uniforms);shader.vertexShader='attribute vec3 restPosition;\nvarying vec3 vRestNormal;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('vAnatomy=position;','vAnatomy=restPosition;vRestNormal=normal;');shader.fragmentShader=`
float ihash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453123);}
float inoise(vec3 p){vec3 i=floor(p);vec3 f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(ihash(i),ihash(i+vec3(1,0,0)),f.x),mix(ihash(i+vec3(0,1,0)),ihash(i+vec3(1,1,0)),f.x),f.y),mix(mix(ihash(i+vec3(0,0,1)),ihash(i+vec3(1,0,1)),f.x),mix(ihash(i+vec3(0,1,1)),ihash(i+vec3(1,1,1)),f.x),f.y),f.z);}
varying vec3 vRestNormal;uniform int uDamageCount;uniform vec4 uDamagePoints[${MAX_EVENTS*2}];uniform vec2 uDamageWeights[${MAX_EVENTS*2}];uniform vec3 uDamageNormals[${MAX_EVENTS*2}];uniform float uLayer;\n`+shader.fragmentShader;
shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>',`#include <roughnessmap_fragment>
float damage=0.;float fracture=0.;for(int i=0;i<${MAX_EVENTS*2};i++){if(i>=uDamageCount)break;vec3 delta=vAnatomy-uDamagePoints[i].xyz;float radius=uDamagePoints[i].w;float d=length(delta*vec3(1.,1.13,1.))/radius;float irregular=(inoise(vAnatomy*110.)-.5)*.32+(inoise(vAnatomy*240.)-.5)*.15;float mottled=.65+.35*inoise(vAnatomy*400.);float mask=(1.-smoothstep(.1,1.05,d+irregular))*mottled;if(uLayer<.5&&dot(normalize(vRestNormal),uDamageNormals[i])<.12)mask=0.;
if(uLayer<.5&&uDamageWeights[i].y>.5&&dot(normalize(vRestNormal),uDamageNormals[i])>.1){float axial=dot(delta,uDamageNormals[i]);vec3 lateral=delta-axial*uDamageNormals[i];float angle=atan(lateral.y,lateral.x);float edge=.0065*(1.+.08*sin(angle*5.)+.04*cos(angle*9.));if(length(lateral)<edge&&abs(axial)<.018)discard;}
damage+=mask*uDamageWeights[i].x;float jag=abs(delta.x+.003*sin(delta.y*540.)+.0015*sin(delta.y*1100.));fracture+=mask*uDamageWeights[i].x*(1.-smoothstep(.0004,.0015,jag));}
if(uLayer>1.5&&uLayer<2.5){if(damage>.64)diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.055,.039,.025),clamp(fracture*1.5,0.,.9));}else{vec3 bruised=uLayer<.5?vec3(.21,.052,.074):vec3(.045,.005,.012);diffuseColor.rgb=mix(diffuseColor.rgb,bruised,(1.-exp(-damage*1.05))*(.83+.17*inoise(vAnatomy*400.)));}`);};mat.customProgramCacheKey=()=>`damage-${s.layer}`;mat.needsUpdate=true;}
export function updateDamageMaterials(structures:Structure[],events:DamageEvent[]){for(const s of structures){const regions=localDamage(s,events),u=s.mesh.material.userData.damage;if(!u)continue;u.uDamageCount.value=regions.length;regions.forEach((r,i)=>{u.uDamagePoints.value[i].set(r.point.x,r.point.y,r.point.z,r.radius);u.uDamageWeights.value[i].set(r.strength,r.tool==='projectile'?1:0);u.uDamageNormals.value[i].copy(r.normal??r.event.normal);});}}
