import * as THREE from 'three';import type {Structure} from './anatomy';import {MAX_REGIONS,localDamage,type DamageEvent} from './damage';
export function installDamageMaterial(s:Structure){const mat=s.mesh.material,previous=mat.onBeforeCompile.bind(mat);s.mesh.geometry.setAttribute('restPosition',new THREE.BufferAttribute(s.base,3));const uniforms={uDamageCount:{value:0},uDamagePoints:{value:Array.from({length:MAX_REGIONS},()=>new THREE.Vector4())},uOpenings:{value:Array.from({length:MAX_REGIONS},()=>new THREE.Vector2())},uDamageWeights:{value:Array.from({length:MAX_REGIONS},()=>new THREE.Vector2())},uDamageNormals:{value:Array.from({length:MAX_REGIONS},()=>new THREE.Vector3())},uLayer:{value:s.layer==='skin'?0:s.layer==='muscle'?1:s.layer==='bone'?2:3}};mat.userData.damage=uniforms;
mat.onBeforeCompile=(shader,r)=>{previous(shader,r);Object.assign(shader.uniforms,uniforms);shader.vertexShader='attribute vec3 restPosition;\nvarying vec3 vRestNormal;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('vAnatomy=position;','vAnatomy=restPosition;vRestNormal=normal;');shader.fragmentShader=`
float ihash(vec3 p){return fract(sin(dot(p,vec3(127.1,311.7,74.7)))*43758.5453123);}
float inoise(vec3 p){vec3 i=floor(p);vec3 f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(ihash(i),ihash(i+vec3(1,0,0)),f.x),mix(ihash(i+vec3(0,1,0)),ihash(i+vec3(1,1,0)),f.x),f.y),mix(mix(ihash(i+vec3(0,0,1)),ihash(i+vec3(1,0,1)),f.x),mix(ihash(i+vec3(0,1,1)),ihash(i+vec3(1,1,1)),f.x),f.y),f.z);}
varying vec3 vRestNormal;uniform int uDamageCount;uniform vec4 uDamagePoints[${MAX_REGIONS}];uniform vec2 uDamageWeights[${MAX_REGIONS}];uniform vec2 uOpenings[${MAX_REGIONS}];uniform vec3 uDamageNormals[${MAX_REGIONS}];uniform float uLayer;\n`+shader.fragmentShader;
shader.fragmentShader=shader.fragmentShader.replace('#include <roughnessmap_fragment>',`#include <roughnessmap_fragment>
float damage=0.;float fracture=0.;float irregular=0.;float mottled=1.;bool sampled=false;for(int i=0;i<${MAX_REGIONS};i++){if(i>=uDamageCount)break;vec3 delta=vAnatomy-uDamagePoints[i].xyz;float radius=uDamagePoints[i].w;vec3 localDelta=delta;bool tract=uLayer>.5&&uDamageWeights[i].y>.5;float along=dot(delta,uDamageNormals[i]);if(tract)localDelta-=uDamageNormals[i]*clamp(along,-uOpenings[i].y,uOpenings[i].y);float d=length(localDelta*vec3(1.,1.13,1.))/radius;if(d>1.3)continue;if(uLayer<.5&&dot(normalize(vRestNormal),uDamageNormals[i])<.1)continue;if(!sampled){irregular=(inoise(vAnatomy*110.)-.5)*.32+(inoise(vAnatomy*240.)-.5)*.15;mottled=.65+.35*inoise(vAnatomy*400.);sampled=true;}float mask=(1.-smoothstep(.1,1.05,d+irregular))*mottled;if(uLayer<.5&&dot(normalize(vRestNormal),uDamageNormals[i])<.12)mask=0.;
if(uLayer<.5&&uDamageWeights[i].y>.5&&dot(normalize(vRestNormal),uDamageNormals[i])>.1){float axial=dot(delta,uDamageNormals[i]);vec3 lateral=delta-axial*uDamageNormals[i];vec3 tangent=cross(uDamageNormals[i],vec3(0.,1.,0.));if(length(tangent)<.1)tangent=vec3(1.,0.,0.);tangent=normalize(tangent);vec3 bitangent=normalize(cross(uDamageNormals[i],tangent));float angle=atan(dot(lateral,bitangent),dot(lateral,tangent));float edge=uOpenings[i].x*(1.+.08*sin(angle*5.)+.04*cos(angle*9.));if(length(lateral)<edge&&abs(axial)<uOpenings[i].y+.008)discard;}
if(tract){float radial=length(delta-along*uDamageNormals[i]);float edge=uOpenings[i].x*(1.+.065*sin(along*560.)+.045*sin(dot(delta,vec3(720.,430.,310.))));if(radial<edge&&abs(along)<uOpenings[i].y+.001)discard;}
damage+=mask*uDamageWeights[i].x;float jag=min(abs(delta.x+.004*sin(delta.y*420.)),min(abs(delta.y+delta.z*.4+.003*sin(delta.x*530.)),abs(delta.x*.65-delta.y+.002*sin(delta.z*610.))));fracture+=mask*uDamageWeights[i].x*(1.-smoothstep(.0004,.0015,jag));}
if(uLayer>1.5&&uLayer<2.5){if(damage>.64){diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.40,.22,.15),min(.52,damage*.2));diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.055,.025,.019),clamp(fracture*1.8,0.,.94));}}else if(damage>0.){vec3 bruised=uLayer<.5?vec3(.21,.052,.074):vec3(.045,.005,.012);diffuseColor.rgb=mix(diffuseColor.rgb,bruised,(1.-exp(-damage*1.22))*(.83+.17*(mottled-.65)/.35));}`);};mat.customProgramCacheKey=()=>`damage-${s.layer}`;mat.needsUpdate=true;}
export function updateDamageMaterials(structures:Structure[],events:DamageEvent[]){for(const s of structures){const regions=localDamage(s,events),u=s.mesh.material.userData.damage;if(!u)continue;u.uDamageCount.value=regions.length;regions.forEach((r,i)=>{u.uDamagePoints.value[i].set(r.point.x,r.point.y,r.point.z,r.radius);u.uOpenings.value[i].set(r.opening,r.depth);u.uDamageWeights.value[i].set(r.strength,r.tool==='projectile'?1:0);u.uDamageNormals.value[i].copy(r.normal??r.event.normal);});}}
