import {rifleLaunch,type LaunchReference} from './rifle-reference';
import {profile,type WeaponId} from './shot-profiles';
import {solvePath} from './path-solver';
import {finalizeRecord,type PhysicalRecord} from './physics-state';
import * as THREE from 'three';
import {projectileLesions,priorLocalShots,tissueLesions,tissueRadius} from './lesions';
import type {Structure,Layer} from './anatomy';
export const MAX_EVENTS=30;
export const MAX_REGIONS=MAX_EVENTS*2;
export const IMPACT_LEVELS=[{radius:.025,depth:.032,indent:.0017,strength:.34},{radius:.041,depth:.067,indent:.004,strength:.62},{radius:.056,depth:.10,indent:.007,strength:.95}] as const;
export type Tool='impact'|'projectile';
export interface Interval {id:string;layer:Layer;start:number;end:number;}
export interface Region {id:string;point:THREE.Vector3;radius:number;strength:number;normal?:THREE.Vector3;}
export interface DamageEvent {launch?:LaunchReference;weapon?:WeaponId;shotId?:number;physical?:PhysicalRecord;id:number;skinId?:string;tracks?:{id:string;start:THREE.Vector3;end:THREE.Vector3;direction?:THREE.Vector3}[];tool:Tool;intensity:number;point:THREE.Vector3;anchor:THREE.Vector3;normal:THREE.Vector3;direction:THREE.Vector3;regions:Region[];end:THREE.Vector3;exit:THREE.Vector3|null;radius:number;indent:number;}
export interface Contact {skinId?:string;point:THREE.Vector3;anchor:THREE.Vector3;normal:THREE.Vector3;direction:THREE.Vector3;face:[number,number,number];bary:THREE.Vector3;selectedName:string;}
export function deduplicateHits(hits:{distance:number;facing:number}[],epsilon=1e-5){const out:{distance:number;facing:number}[]=[];for(const h of [...hits].sort((a,b)=>a.distance-b.distance)){const last=out.at(-1);if(last&&Math.abs(h.distance-last.distance)<epsilon){if(Math.abs(h.facing)>Math.abs(last.facing))last.facing=h.facing;}else out.push({...h});}return out;}
export function pairedIntervals(hits:{distance:number;facing:number}[]){const result:{start:number;end:number}[]=[];let start:number|null=null;for(const h of deduplicateHits(hits)){if(Math.abs(h.facing)<1e-6)continue;if(h.facing<0){if(start===null)start=h.distance;}else{if(start===null&&result.length===0)start=0;if(start!==null&&h.distance-start>1e-5)result.push({start,end:h.distance});start=null;}}return result;}
export function traceAnatomy(structures:Structure[],origin:THREE.Vector3,direction:THREE.Vector3):Interval[]{const ray=new THREE.Raycaster(origin,direction.clone().normalize(),0,1.5),out:Interval[]=[];for(const s of structures){s.mesh.updateMatrixWorld();const hits=ray.intersectObject(s.mesh,false).map(h=>({distance:h.distance,facing:h.face!.normal.dot(direction)}));for(const pair of pairedIntervals(hits))out.push({id:s.id,layer:s.layer,...pair});}return out.sort((a,b)=>a.start-b.start||a.end-b.end);}
// The skin envelope is not solid tissue. Cavity gaps consume no budget.
export function tissueIntervals(intervals:Interval[],body:Interval):Interval[]{return intervals.flatMap(i=>i.layer==='skin'?[{...i,end:Math.min(i.end,i.start+.005)},{...i,start:Math.max(i.start,i.end-.005)}]:[i]).map(i=>({...i,start:Math.max(i.start,body.start),end:Math.min(i.end,body.end)})).filter(i=>i.end>i.start+1e-6);}
const resistance:Record<Layer,number>={skin:2,muscle:1.4,bone:4,organ:.55};
export function penetrationEnd(intervals:Interval[],start:number,end:number,budget=.14){const points=[...new Set([start,end,...intervals.flatMap(i=>[Math.max(start,i.start),Math.min(end,i.end)]).filter(x=>x>=start&&x<=end)])].sort((a,b)=>a-b);for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1],mid=(a+b)/2,active=intervals.filter(s=>s.start<=mid&&s.end>=mid),cost=active.length?Math.max(...active.map(s=>resistance[s.layer])):0;if(cost>0&&budget<(b-a)*cost)return a+budget/cost;budget-=(b-a)*cost;}return end;}
export function computeEvent(structures:Structure[],contact:Contact,tool:Tool,intensity:number,id:number,previous:DamageEvent[]=[],weapon:WeaponId='legacy'):DamageEvent|null{
 const direction=contact.direction.clone().normalize(),origin=contact.point.clone().addScaledVector(direction,-.004),central=traceAnatomy(structures,origin,direction),body=central.find(i=>i.layer==='skin'&&i.start<.015&&(!contact.skinId||i.id===contact.skinId));if(!body)return null;
 const skinId=body.id,tracks:{id:string;start:THREE.Vector3;end:THREE.Vector3}[]=[],prior=priorLocalShots(previous,contact.anchor,contact.normal,skinId);
 const level=IMPACT_LEVELS[intensity]??IMPACT_LEVELS[1],regions:Region[]=[];let endDistance=Math.min(body.end,body.start+level.depth),exit:THREE.Vector3|null=null;
 let solved:ReturnType<typeof solvePath>|undefined;
 if(tool==='projectile'){solved=solvePath(structures,contact,previous,profile(weapon).energy);tracks.push(...solved.tracks);exit=solved.exit;for(const t of tracks){const structure=structures.find(s=>s.id===t.id)!;const length=t.start.distanceTo(t.end),samples=Math.max(1,Math.ceil(length/.025));for(let k=0;k<samples;k++)regions.push({id:t.id,point:t.start.clone().lerp(t.end,(k+.5)/samples),radius:structure.layer==='bone'?.026:.041,strength:Math.min(1.8,.9+prior*.12)});}}

 else{const u=new THREE.Vector3().crossVectors(contact.normal,Math.abs(contact.normal.y)>.85?new THREE.Vector3(1,0,0):new THREE.Vector3(0,1,0)).normalize(),v=new THREE.Vector3().crossVectors(contact.normal,u).normalize(),collected=new Map<string,Region>();
  for(let k=0;k<9;k++){const a=(k-1)*Math.PI/4,offset=k===0?new THREE.Vector3():u.clone().multiplyScalar(Math.cos(a)*level.radius*.48).addScaledVector(v,Math.sin(a)*level.radius*.48),sampleOrigin=origin.clone().add(offset),ints=traceAnatomy(structures,sampleOrigin,direction),envelope=ints.find(i=>i.layer==='skin'&&i.start<.06);if(!envelope)continue;
   for(const i of ints){if(i.start>envelope.start+level.depth||i.end<envelope.start||i.start>envelope.end||i.layer==='skin')continue;const depth=Math.max(0,i.start-envelope.start),strength=level.strength*Math.exp(-depth/(level.depth*.68))*(k===0?1:.72);if(strength<.12)continue;const point=sampleOrigin.clone().addScaledVector(direction,Math.max(i.start,envelope.start)+Math.min(.006,(i.end-i.start)/2)),previous=collected.get(i.id);if(!previous||strength>previous.strength)collected.set(i.id,{id:i.id,point,radius:level.radius*.8,strength});}}
  regions.push(...collected.values());}
 const skin=structures.find(s=>s.id===skinId)!;for(let i=regions.length-1;i>=0;i--)if(regions[i].id===skin.id)regions.splice(i,1);
 regions.push({id:skin.id,point:contact.anchor.clone(),radius:tool==='impact'?level.radius:.033,strength:tool==='impact'?level.strength:.95});
 if(exit)regions.push({id:skin.id,point:exit.clone(),radius:.033,strength:.95,normal:direction.clone()});
 return finalizeRecord({id,weapon,launch:tool==='projectile'&&weapon==='rifle'?rifleLaunch():undefined,physical:solved?.physical,skinId,tracks,tool,intensity,point:contact.point.clone(),anchor:contact.anchor.clone(),normal:contact.normal.clone(),direction,regions,end:solved?.end??origin.clone().addScaledVector(direction,endDistance),exit,radius:tool==='impact'?level.radius:.025,indent:tool==='impact'?level.indent:.0035*profile(weapon).width},structures,previous);
}
const deformationCache=new WeakMap<Structure,DamageEvent[]>();
export function applyDeformation(structures:Structure[],events:DamageEvent[]){for(const s of structures){if(s.layer==='bone')continue;const relevant=events.filter(e=>e.regions.some(r=>r.id===s.id)),previous=deformationCache.get(s)??[];if(relevant.length===previous.length&&relevant.every((e,i)=>e===previous[i]))continue;deformationCache.set(s,[...relevant]);const influences:{point:THREE.Vector3;radius:number;direction:THREE.Vector3;amount:number}[]=[];for(const e of relevant)for(const r of e.regions.filter(r=>r.id===s.id)){const direction=e.physical?.contacts.find(c=>c.id===s.id)?.direction??e.direction;const amount=e.indent*(s.layer==='organ'?1.3:s.layer==='muscle'?1.05:1)*(e.tool==='projectile'?1.7:1);const near=influences.find(i=>i.point.distanceTo(r.point)<.008&&i.direction.dot(direction)>.9);if(near)near.amount=Math.min(.025,near.amount+amount);else influences.push({point:r.point,radius:Math.max(r.radius,s.layer==='organ'?.055:.025),direction,amount});}const p=s.mesh.geometry.attributes.position;
 for(let i=0;i<p.count;i++){const rest=new THREE.Vector3().fromArray(s.base,i*3),normal=new THREE.Vector3().fromArray(s.normals,i*3),shift=new THREE.Vector3();for(const f of influences){const d=rest.distanceTo(f.point)/f.radius;if(d>1.6||(s.layer==='skin'&&normal.dot(f.direction)>.15))continue;const w=Math.exp(-d*d*3),tangent=f.direction.clone().addScaledVector(normal,-f.direction.dot(normal));shift.addScaledVector(f.direction,f.amount*w).addScaledVector(tangent,f.amount*.35*w);shift.addScaledVector(normal,f.amount*.14*Math.exp(-Math.pow(d-.83,2)*28));}shift.clampLength(0,.012);rest.add(shift);p.setXYZ(i,rest.x,rest.y,rest.z);}p.needsUpdate=true;s.mesh.geometry.computeVertexNormals();s.mesh.geometry.computeBoundingBox();s.mesh.geometry.computeBoundingSphere();s.mesh.geometry.boundsTree?.refit();}}
export function localDamage(s:Structure,events:DamageEvent[]){
 const marks=events.flatMap(e=>e.regions.filter(r=>r.id===s.id&&e.tool==='impact').map(r=>({...r,tool:e.tool,event:e,opening:0,depth:0})));
 if(s.layer==='skin')for(const l of projectileLesions(events).filter(l=>l.skinId===s.id))marks.push({id:s.id,point:l.point,normal:l.normal,radius:l.radius*2.8,strength:Math.min(2.8,.95+l.count*.24),tool:'projectile',event:l.event,opening:l.radius,depth:l.depth});
 if(s.layer!=='skin'&&!(s.layer==='bone'&&events.some(e=>e.physical?.fractures.some(f=>f.id===(s.mesh.userData.parentId??s.id)))))for(const t of tissueLesions(events).filter(t=>t.id===s.id)){const opening=tissueRadius(s.layer,t.count);marks.push({id:s.id,point:t.start.clone().add(t.end).multiplyScalar(.5),normal:t.direction,radius:opening*2.6,strength:Math.min(3,1.4+t.count*.25),tool:'projectile',event:events.find(e=>e.tool==='projectile')!,opening,depth:t.start.distanceTo(t.end)*.5});}
 // Merge close tissue samples so a long tract and repeat hits remain GPU-bounded.
 const merged:typeof marks=[];for(const r of marks){const near=merged.find(m=>m.tool===r.tool&&m.point.distanceTo(r.point)<.012&&(s.layer!=='skin'||(m.normal??m.event.normal).dot(r.normal??r.event.normal)>.65));if(near&&s.layer!=='skin'&&r.tool==='impact'){near.strength=Math.min(3,near.strength+r.strength*.55);near.radius=Math.max(near.radius,r.radius);}else merged.push(r);}
 return merged.slice(-MAX_REGIONS);
}
