import * as THREE from 'three';
import type {Structure,Layer} from './anatomy';
export const MAX_EVENTS=12;
export const IMPACT_LEVELS=[{radius:.025,depth:.032,indent:.0017,strength:.34},{radius:.041,depth:.067,indent:.004,strength:.62},{radius:.056,depth:.10,indent:.007,strength:.95}] as const;
export type Tool='impact'|'projectile';
export interface Interval {id:string;layer:Layer;start:number;end:number;}
export interface Region {id:string;point:THREE.Vector3;radius:number;strength:number;normal?:THREE.Vector3;}
export interface DamageEvent {id:number;tool:Tool;intensity:number;point:THREE.Vector3;anchor:THREE.Vector3;normal:THREE.Vector3;direction:THREE.Vector3;regions:Region[];end:THREE.Vector3;exit:THREE.Vector3|null;radius:number;indent:number;}
export interface Contact {point:THREE.Vector3;anchor:THREE.Vector3;normal:THREE.Vector3;direction:THREE.Vector3;face:[number,number,number];bary:THREE.Vector3;selectedName:string;}
export function deduplicateHits(hits:{distance:number;facing:number}[],epsilon=1e-5){const out:{distance:number;facing:number}[]=[];for(const h of [...hits].sort((a,b)=>a.distance-b.distance)){const last=out.at(-1);if(last&&Math.abs(h.distance-last.distance)<epsilon){if(Math.abs(h.facing)>Math.abs(last.facing))last.facing=h.facing;}else out.push({...h});}return out;}
export function pairedIntervals(hits:{distance:number;facing:number}[]){const result:{start:number;end:number}[]=[];let start:number|null=null;for(const h of deduplicateHits(hits)){if(Math.abs(h.facing)<1e-6)continue;if(h.facing<0){if(start===null)start=h.distance;}else{if(start===null&&result.length===0)start=0;if(start!==null&&h.distance-start>1e-5)result.push({start,end:h.distance});start=null;}}return result;}
export function traceAnatomy(structures:Structure[],origin:THREE.Vector3,direction:THREE.Vector3):Interval[]{const ray=new THREE.Raycaster(origin,direction.clone().normalize(),0,1.5),out:Interval[]=[];for(const s of structures){s.mesh.updateMatrixWorld();const hits=ray.intersectObject(s.mesh,false).map(h=>({distance:h.distance,facing:h.face!.normal.dot(direction)}));for(const pair of pairedIntervals(hits))out.push({id:s.id,layer:s.layer,...pair});}return out.sort((a,b)=>a.start-b.start||a.end-b.end);}
// The skin envelope is not solid tissue. Cavity gaps consume no budget.
export function tissueIntervals(intervals:Interval[],body:Interval):Interval[]{return intervals.flatMap(i=>i.layer==='skin'?[{...i,end:Math.min(i.end,i.start+.005)},{...i,start:Math.max(i.start,i.end-.005)}]:[i]).map(i=>({...i,start:Math.max(i.start,body.start),end:Math.min(i.end,body.end)})).filter(i=>i.end>i.start+1e-6);}
const resistance:Record<Layer,number>={skin:2,muscle:1.4,bone:4,organ:.55};
export function penetrationEnd(intervals:Interval[],start:number,end:number,budget=.14){const points=[...new Set([start,end,...intervals.flatMap(i=>[Math.max(start,i.start),Math.min(end,i.end)]).filter(x=>x>=start&&x<=end)])].sort((a,b)=>a-b);for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1],mid=(a+b)/2,active=intervals.filter(s=>s.start<=mid&&s.end>=mid),cost=active.length?Math.max(...active.map(s=>resistance[s.layer])):0;if(cost>0&&budget<(b-a)*cost)return a+budget/cost;budget-=(b-a)*cost;}return end;}
export function computeEvent(structures:Structure[],contact:Contact,tool:Tool,intensity:number,id:number):DamageEvent|null{
 const direction=contact.direction.clone().normalize(),origin=contact.point.clone().addScaledVector(direction,-.004),central=traceAnatomy(structures,origin,direction),body=central.find(i=>i.layer==='skin'&&i.start<.015);if(!body)return null;
 const level=IMPACT_LEVELS[intensity]??IMPACT_LEVELS[1],regions:Region[]=[];let endDistance=Math.min(body.end,body.start+level.depth),exit:THREE.Vector3|null=null;
 if(tool==='projectile'){const intervals=tissueIntervals(central,body);endDistance=penetrationEnd(intervals,body.start,Math.min(body.end,body.start+.31));for(const i of intervals){const a=Math.max(i.start,body.start),b=Math.min(i.end,endDistance);if(b>a+1e-5)regions.push({id:i.id,point:origin.clone().addScaledVector(direction,(a+b)/2),radius:i.layer==='skin'?.021:.018,strength:.94});}if(endDistance>=body.end-1e-5)exit=origin.clone().addScaledVector(direction,body.end);}
 else{const u=new THREE.Vector3().crossVectors(contact.normal,Math.abs(contact.normal.y)>.85?new THREE.Vector3(1,0,0):new THREE.Vector3(0,1,0)).normalize(),v=new THREE.Vector3().crossVectors(contact.normal,u).normalize(),collected=new Map<string,Region>();
  for(let k=0;k<9;k++){const a=(k-1)*Math.PI/4,offset=k===0?new THREE.Vector3():u.clone().multiplyScalar(Math.cos(a)*level.radius*.48).addScaledVector(v,Math.sin(a)*level.radius*.48),sampleOrigin=origin.clone().add(offset),ints=traceAnatomy(structures,sampleOrigin,direction),envelope=ints.find(i=>i.layer==='skin'&&i.start<.06);if(!envelope)continue;
   for(const i of ints){if(i.start>envelope.start+level.depth||i.end<envelope.start||i.start>envelope.end||i.layer==='skin')continue;const depth=Math.max(0,i.start-envelope.start),strength=level.strength*Math.exp(-depth/(level.depth*.68))*(k===0?1:.72);if(strength<.12)continue;const point=sampleOrigin.clone().addScaledVector(direction,Math.max(i.start,envelope.start)+Math.min(.006,(i.end-i.start)/2)),previous=collected.get(i.id);if(!previous||strength>previous.strength)collected.set(i.id,{id:i.id,point,radius:level.radius*.8,strength});}}
  regions.push(...collected.values());}
 const skin=structures.find(s=>s.layer==='skin')!;for(let i=regions.length-1;i>=0;i--)if(regions[i].id===skin.id)regions.splice(i,1);
 regions.push({id:skin.id,point:contact.anchor.clone(),radius:tool==='impact'?level.radius:.021,strength:tool==='impact'?level.strength:.95});
 if(exit)regions.push({id:skin.id,point:exit.clone(),radius:.021,strength:.95,normal:direction.clone()});
 return {id,tool,intensity,point:contact.point.clone(),anchor:contact.anchor.clone(),normal:contact.normal.clone(),direction,regions,end:origin.clone().addScaledVector(direction,endDistance),exit,radius:tool==='impact'?level.radius:.0065,indent:tool==='impact'?level.indent:0};
}
export function applyDeformation(structures:Structure[],events:DamageEvent[]){for(const s of structures){if(s.layer!=='skin'&&s.layer!=='muscle')continue;const p=s.mesh.geometry.attributes.position,n=s.normals;for(let i=0;i<p.count;i++){const x=s.base[i*3],y=s.base[i*3+1],z=s.base[i*3+2];let displacement=0;for(const e of events){if(e.tool!=='impact')continue;const region=s.layer==='skin'?{point:e.anchor,radius:e.radius}:e.regions.find(r=>r.id===s.id);if(!region)continue;const dx=x-region.point.x,dy=y-region.point.y,dz=z-region.point.z,r2=(dx*dx+dy*dy+dz*dz)/(region.radius*region.radius),facing=n[i*3]*e.normal.x+n[i*3+1]*e.normal.y+n[i*3+2]*e.normal.z;if(r2>2||facing<.12)continue;displacement+=-e.indent*Math.exp(-r2*3.6)*(s.layer==='muscle'?.45:1)+e.indent*.2*Math.exp(-Math.pow(Math.sqrt(r2)-.8,2)*25);}displacement=THREE.MathUtils.clamp(displacement,-.012,.003);p.setXYZ(i,x+n[i*3]*displacement,y+n[i*3+1]*displacement,z+n[i*3+2]*displacement);}p.needsUpdate=true;s.mesh.geometry.computeVertexNormals();s.mesh.geometry.computeBoundingSphere();s.mesh.geometry.computeBoundingBox();}}
export function localDamage(s:Structure,events:DamageEvent[]){return events.flatMap(e=>e.regions.filter(r=>r.id===s.id).map(r=>({...r,tool:e.tool,event:e}))).slice(-MAX_EVENTS*2);}
