import * as THREE from 'three';
import {MeshBVH,acceleratedRaycast} from 'three-mesh-bvh';
import {tissueMaterial,type Structure} from './anatomy';
import type {DamageEvent} from './damage';
import {MAX_FRAGMENTS,type Fracture} from './physics-state';
interface Piece {s:Structure;rest:Float32Array;f:Fracture;eventId:number;}
function closedSubset(source:THREE.BufferGeometry,indices:number[]){const original=source.attributes.position,positions=Array.from(original.array),edges=new Map<string,{a:number;b:number;count:number}>();for(let i=0;i<indices.length;i+=3)for(let k=0;k<3;k++){const a=indices[i+k],b=indices[i+(k+1)%3],key=a<b?`${a}:${b}`:`${b}:${a}`;const edge=edges.get(key);if(edge)edge.count++;else edges.set(key,{a,b,count:1});}const boundary=[...edges.values()].filter(e=>e.count===1),used=new Set<number>(),loops:number[][]=[];for(let i=0;i<boundary.length;i++){if(used.has(i))continue;const loop=[boundary[i].a,boundary[i].b];used.add(i);for(let guard=0;guard<boundary.length;guard++){const end=loop.at(-1)!;if(end===loop[0])break;const j=boundary.findIndex((e,j)=>!used.has(j)&&(e.a===end||e.b===end));if(j<0)break;used.add(j);loop.push(boundary[j].a===end?boundary[j].b:boundary[j].a);}if(loop.at(-1)===loop[0]&&loop.length>=4){loop.pop();loops.push(loop);}}
 const point=(i:number)=>new THREE.Vector3().fromBufferAttribute(original,i),centers=loops.map(loop=>loop.reduce((a,i)=>a.add(point(i)),new THREE.Vector3()).divideScalar(loop.length)),capped=new Set<number>();
 for(let l=0;l<loops.length;l++){if(capped.has(l))continue;const loop=loops[l],center=centers[l];const mate=loops.findIndex((other,j)=>j!==l&&!capped.has(j)&&other.length>6&&loop.length>6&&centers[j].distanceTo(center)<.014);if(mate>=0){const ringA=loop,ringB=loops[mate],normal=new THREE.Vector3();for(let j=0;j<ringA.length;j++)normal.add(new THREE.Vector3().crossVectors(point(ringA[j]).sub(center),point(ringA[(j+1)%ringA.length]).sub(center)));normal.normalize();const u=point(ringA[0]).sub(center).normalize(),v=new THREE.Vector3().crossVectors(normal,u).normalize(),xy=(ring:number[])=>ring.map(i=>{const p=point(i).sub(center);return new THREE.Vector2(p.dot(u),p.dot(v));});let outer=ringA,inner=ringB;if(Math.abs(THREE.ShapeUtils.area(xy(outer)))<Math.abs(THREE.ShapeUtils.area(xy(inner))))[outer,inner]=[inner,outer];const all=[...outer,...inner];for(const tri of THREE.ShapeUtils.triangulateShape(xy(outer),[xy(inner)]))indices.push(...tri.map(i=>all[i]));capped.add(l);capped.add(mate);}else{const ci=positions.length/3;positions.push(center.x,center.y,center.z);for(let j=0;j<loop.length;j++)indices.push(loop[(j+1)%loop.length],loop[j],ci);capped.add(l);}}
 const remap=new Map<number,number>(),compact:number[]=[],newIndex=indices.map(i=>{if(!remap.has(i)){remap.set(i,compact.length/3);compact.push(positions[i*3],positions[i*3+1],positions[i*3+2]);}return remap.get(i)!;});const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(compact,3));g.setIndex(newIndex);g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();g.boundsTree=new MeshBVH(g,{indirect:true,maxLeafTris:10});return g;
}
export class FractureGeometry {pieces:Piece[]=[];private originals=new Map<string,{g:THREE.BufferGeometry;base:Float32Array;normals:Float32Array}>();private signature='';private boneSignatures=new Map<string,string>();constructor(private roots:Structure[],private setup:(s:Structure)=>void=()=>{}){for(const s of roots.filter(s=>s.layer==='bone'))this.originals.set(s.id,{g:s.mesh.geometry.clone(),base:s.base.slice(),normals:s.normals.slice()});}
 update(events:DamageEvent[]){const all=events.flatMap(e=>(e.physical?.fractures??[]).map(f=>({f,eventId:e.id})));const signature=JSON.stringify(all.map(x=>[x.eventId,x.f.id,x.f.point.toArray()]));if(signature===this.signature)return;this.signature=signature;const changed=new Set<string>();for(const s of this.roots.filter(s=>s.layer==='bone')){const key=JSON.stringify(all.filter(x=>x.f.id===s.id));if(key!==(this.boneSignatures.get(s.id)??'[]')){changed.add(s.id);this.boneSignatures.set(s.id,key);}}for(const p of this.pieces.filter(p=>changed.has(p.f.id))){p.s.mesh.removeFromParent();p.s.mesh.geometry.dispose();p.s.mesh.material.dispose();}this.pieces=this.pieces.filter(p=>!changed.has(p.f.id));
 for(const s of this.roots.filter(s=>s.layer==='bone'&&changed.has(s.id))){const source=this.originals.get(s.id)!;if(s.mesh.geometry!==source.g)s.mesh.geometry.dispose();s.mesh.geometry=source.g.clone();s.mesh.geometry.boundsTree=new MeshBVH(s.mesh.geometry,{indirect:true,maxLeafTris:10});s.base=source.base.slice();s.normals=source.normals.slice();s.mesh.material.dispose();s.mesh.material=tissueMaterial('bone',s.name);const fractures=all.filter(x=>x.f.id===s.id);if(!fractures.length){this.setup(s);continue;}const clusters:{f:Fracture;eventId:number}[]=[];for(const x of fractures){const old=clusters.find(c=>c.f.point.distanceTo(x.f.point)<.055);if(old){old.f={...old.f,displacement:Math.min(.036,old.f.displacement+x.f.displacement*.35),angle:Math.min(.6,old.f.angle+x.f.angle*.2)};}else clusters.push({f:{...x.f},eventId:x.eventId});}
 for(const {f,eventId} of clusters){if(this.pieces.length>=MAX_FRAGMENTS)break;const g=s.mesh.geometry,p=g.attributes.position,idx=g.index!,keep:number[]=[],take:number[]=[],center=new THREE.Vector3();for(let i=0;i<idx.count;i+=3){center.set(0,0,0);for(let k=0;k<3;k++)center.add(new THREE.Vector3().fromBufferAttribute(p,idx.getX(i+k)));center.multiplyScalar(1/3);const delta=center.clone().sub(f.point);const target=delta.length()<f.radius*(1+.07*Math.sin(center.y*280.)+.05*Math.cos(center.x*360.))?take:keep;target.push(idx.getX(i),idx.getX(i+1),idx.getX(i+2));}if(take.length<9||keep.length<9)continue;
 const fragmentGeometry=closedSubset(g,[...take]),remaining=closedSubset(g,[...keep]);const mesh=new THREE.Mesh(fragmentGeometry,tissueMaterial('bone',s.name));mesh.raycast=acceleratedRaycast;mesh.userData={...s.mesh.userData,parentId:s.id,fragment:true};const fragment:Structure={id:`${s.id}__fragment_${this.pieces.length}`,name:`${s.name} · fragment`,layer:'bone',mesh,base:new Float32Array(fragmentGeometry.attributes.position.array),normals:new Float32Array(fragmentGeometry.attributes.normal.array)};mesh.name=fragment.id;this.setup(fragment);this.pieces.push({s:fragment,rest:fragment.base.slice(),f,eventId});s.mesh.geometry=remaining;s.base=new Float32Array(remaining.attributes.position.array);s.normals=new Float32Array(remaining.attributes.normal.array);g.dispose();}
 this.setup(s);}this.pose(1);
 }
 pose(fraction:number,lastId=Infinity){for(const piece of this.pieces){const t=piece.eventId===lastId?fraction:1,axis=new THREE.Vector3().crossVectors(piece.f.direction,new THREE.Vector3(.13,1,.21)).normalize(),q=new THREE.Quaternion().setFromAxisAngle(axis,piece.f.angle*t),p=piece.s.mesh.geometry.attributes.position;for(let i=0;i<p.count;i++){const v=new THREE.Vector3().fromArray(piece.rest,i*3).sub(piece.f.point).applyQuaternion(q).add(piece.f.point).addScaledVector(piece.f.direction,piece.f.displacement*t).addScaledVector(axis,piece.f.displacement*.32*t);p.setXYZ(i,v.x,v.y,v.z);}p.needsUpdate=true;piece.s.mesh.geometry.computeVertexNormals();piece.s.mesh.geometry.computeBoundingSphere();piece.s.mesh.geometry.computeBoundingBox();piece.s.mesh.geometry.boundsTree?.refit();}}
 structures(){return this.pieces.map(p=>p.s);}
}
