import * as THREE from 'three';
import {profile} from './shot-profiles';
import type {Layer} from './anatomy';
import type {DamageEvent} from './damage';
export interface Lesion {id:string;skinId:string;point:THREE.Vector3;normal:THREE.Vector3;count:number;radius:number;depth:number;event:DamageEvent;exit:boolean;}
// Bounded visual units, not wound dimensions predicted from a weapon.
export function lesionRadius(count:number){return Math.min(.033,.0115+.005*Math.sqrt(Math.max(0,count-1)));}
export function projectileLesions(events:DamageEvent[]):Lesion[]{const out:Lesion[]=[];for(const event of events){if(event.tool!=='projectile')continue;const skinId=event.skinId??'skin';for(const exit of [false,true]){if(exit&&!event.exit)continue;const point=exit?event.exit!:event.anchor,normal=exit?(event.physical?.path.at(-1)?.end.clone().sub(event.physical.path.at(-1)!.start).normalize()??event.direction):event.normal;let l=out.find(l=>l.skinId===skinId&&l.exit===exit&&l.normal.dot(normal)>.65&&l.point.distanceTo(point)<.017);if(l){l.count++;l.event=event;l.radius=Math.max(l.radius,lesionRadius(l.count)*(exit?1.12:1)*profile(event.weapon).width);l.depth=Math.min(.032,.018+.002*l.count);}else out.push({id:`${event.id}-${exit?'exit':'entry'}`,skinId,point:point.clone(),normal:normal.clone(),count:1,radius:lesionRadius(1)*(exit?1.12:1)*profile(event.weapon).width,depth:.020,event,exit});}}return out;}
export function priorLocalShots(events:DamageEvent[],point:THREE.Vector3,normal:THREE.Vector3,skinId:string){return events.filter(e=>e.tool==='projectile'&&(e.skinId??'skin')===skinId&&e.anchor.distanceTo(point)<.028&&e.normal.dot(normal)>.65).length;}

export interface TissueLesion {id:string;start:THREE.Vector3;end:THREE.Vector3;direction:THREE.Vector3;count:number;}
export function tissueRadius(layer:Layer,count:number){const initial=layer==='bone'?.009:layer==='muscle'?.014:.018;return Math.min(initial*1.9,initial+.003*Math.sqrt(Math.max(0,count-1)));}
// Union only aligned tracks through the same actual structure; cavity gaps stay empty.
export function tissueLesions(events:DamageEvent[]):TissueLesion[]{const out:TissueLesion[]=[];for(const e of events){if(e.tool!=='projectile')continue;for(const t of e.tracks??[]){const center=t.start.clone().add(t.end).multiplyScalar(.5);const found=out.find(l=>l.id===t.id&&l.direction.dot(t.direction??e.direction)>.95&&new THREE.Line3(l.start,l.end).closestPointToPoint(center,true,new THREE.Vector3()).distanceTo(center)<.02);if(found){found.count++;const a=t.start.clone().sub(found.start).dot(found.direction),b=t.end.clone().sub(found.start).dot(found.direction),length=found.start.distanceTo(found.end);if(b>length)found.end.copy(found.start).addScaledVector(found.direction,b);if(a<0)found.start.addScaledVector(found.direction,a);}else out.push({id:t.id,start:t.start.clone(),end:t.end.clone(),direction:(t.direction??e.direction).clone(),count:1});}}return out;}
