import './style.css';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {loadAnatomy,type View,type Structure} from './anatomy';
import {computeEvent,applyDeformation,MAX_EVENTS,type DamageEvent,type Contact,type Tool} from './damage';
import {installDamageMaterial,updateDamageMaterials} from './damage-render';
import {pickContact,refreshContact,GestureGuard} from './interaction';
import {SectionRenderer} from './section';
import {projectileLesions} from './lesions';
import {FractureGeometry} from './fractures';
import {EventReplay} from './replay';
import {serializeEvents,restoreEvents,summarizeState} from './physics-state';
import type {SectionMode} from './section';
import {WoundRenderer} from './wounds';
const stage=document.querySelector<HTMLElement>('#stage')!;
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});
renderer.localClippingEnabled=true;renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.shadowMap.enabled=false;renderer.setClearColor('#e9e7df',1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;stage.append(renderer.domElement);
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(37,1,.01,10);camera.position.set(0,.13,1.65);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.09,0);controls.enablePan=false;controls.enableDamping=true;controls.minDistance=.58;controls.maxDistance=1.9;controls.minPolarAngle=.4;controls.maxPolarAngle=2.65;controls.rotateSpeed=.8;controls.dampingFactor=.10;
scene.add(new THREE.HemisphereLight('#fff5e4','#788b7c',1.65));
function light(x:number,y:number,z:number,intensity:number){const l=new THREE.DirectionalLight('#fff5e8',intensity);l.position.set(x,y,z);scene.add(l);return l;}
light(-1,1.4,1.4,2.6);
light(1,.4,-1,1.9);light(1,.2,1,.65);
const standMat=new THREE.MeshStandardMaterial({color:'#788b7f',roughness:.86});
const post=new THREE.Mesh(new THREE.CylinderGeometry(.019,.022,.10,32),standMat);post.position.set(0,-.36,0);scene.add(post);
const base=new THREE.Mesh(new THREE.CylinderGeometry(.105,.115,.018,48),standMat);base.position.y=-.407;base.receiveShadow=true;scene.add(base);
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=128;const shadowContext=shadowCanvas.getContext('2d')!;const gradient=shadowContext.createRadialGradient(64,64,8,64,64,62);gradient.addColorStop(0,'rgba(32,49,39,.20)');gradient.addColorStop(.45,'rgba(32,49,39,.12)');gradient.addColorStop(1,'rgba(32,49,39,0)');shadowContext.fillStyle=gradient;shadowContext.fillRect(0,0,128,128);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(.46,.46),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));ground.rotation.x=-Math.PI/2;ground.position.y=-.42;scene.add(ground);
const section=new SectionRenderer(),wounds=new WoundRenderer();scene.add(section.group,wounds.group);
let roots:Structure[]=[],bones:FractureGeometry;const replay=new EventReplay();let quality='balanced',selectedEvent=-1,lastTick=0,replayMarks=true;let structures:Structure[]=[],view:View='skin',events:DamageEvent[]=[],contact:Contact|null=null,tool:Tool='impact',intensity=1,showMarker=false,sectionOffset=0,dirty=true;
const marker=new THREE.Mesh(new THREE.RingGeometry(.007,.009,32),new THREE.MeshBasicMaterial({color:'#fff9e9',side:THREE.DoubleSide}));marker.visible=false;scene.add(marker);
let frameId=0,running=true;function render(){dirty=true;if(running&&!frameId)frameId=requestAnimationFrame(loop);}
function saveSettings(){try{localStorage.setItem('impact-core-settings',JSON.stringify({view,tool,intensity,quality}));}catch{}}
function updateUI(){document.querySelector<HTMLButtonElement>('#apply')!.disabled=!contact||events.length>=MAX_EVENTS||replay.playing||(!!replay.event&&replay.frame<96);document.querySelector<HTMLButtonElement>('#undo')!.disabled=!events.length;document.querySelector('#status')!.textContent=events.length>=MAX_EVENTS?'Session limit · Undo or reset':events.length?'Localized change':tool==='impact'?'Intact · '+['Light','Medium','Strong'][intensity]+' impact':'Intact · Fictional projectile';marker.visible=!!contact&&showMarker&&view==='skin';if(contact){refreshContact(contact,structures.find(s=>s.id===(contact?.skinId??'skin'))!);marker.position.copy(contact.point).addScaledVector(contact.normal,.0015);marker.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),contact.normal);}document.querySelector('#selection')!.textContent=contact?(contact.selectedName==='Skin'?'Surface contact':contact.selectedName):'Tap to select · Drag to rotate · Pinch to zoom';render();}
function saveDamage(){try{localStorage.setItem('impact-core-damage-v2',serializeEvents(events));}catch{document.querySelector('#status')!.textContent='Damage kept in session; save storage full';}}
function redrawDamage(){if(bones){bones.update(events);structures=[...roots,...bones.structures()];for(const p of bones.structures())if(!p.mesh.parent)scene.add(p.mesh);}applyDeformation(structures,events);updateDamageMaterials(structures,events);wounds.update(structures,events);section.update(structures,events,view==='cutaway',sectionOffset);wounds.setView(view,section.plane);for(const s of structures)s.mesh.visible=layerVisible(s,view);updateUI();updateReplayUI();updatePath();}
function apply(){if(!contact||events.length>=MAX_EVENTS||replay.playing)return;finishReplay();refreshContact(contact,structures.find(s=>s.id===(contact?.skinId??'skin'))!);replay.captureBefore(structures);const started=performance.now(),e=computeEvent(structures,contact,tool,intensity,events.length,events);if(e){events.push(e);selectedEvent=e.id;showMarker=false;redrawDamage();replay.captureAfter(structures,e);simulationTimes.push(performance.now()-started);saveDamage();startReplay(1);}else document.querySelector('#status')!.textContent='No enclosed tissue at this contact';}
function reset(){finishReplay();replay.clear();section.clear();events=[];selectedEvent=-1;contact=null;sectionOffset=0;document.querySelector<HTMLInputElement>('#section')!.value='50';redrawDamage();saveDamage();}
function undo(){finishReplay();replay.clear();events.pop();selectedEvent=events.length-1;section.clear();redrawDamage();saveDamage();}
function layerVisible(s:Structure,v:View){return v==='skin'?s.layer==='skin':v==='muscle'?s.layer==='muscle'||s.layer==='bone':v==='skeleton'?s.layer==='bone':v==='organs'?s.layer==='organ'&&s.name!=='Diaphragm':true;}
const simulationTimes:number[]=[];
const pathMaterial=new THREE.LineBasicMaterial({color:'#b8914c',transparent:true,opacity:.85}),pathLine=new THREE.Line(new THREE.BufferGeometry(),pathMaterial);scene.add(pathLine);const projectileTip=new THREE.Mesh(new THREE.SphereGeometry(.003,8,6),new THREE.MeshBasicMaterial({color:'#e9c46d'}));projectileTip.visible=false;scene.add(projectileTip);
function updatePath(){const e=events[selectedEvent]??events.at(-1);pathLine.geometry.dispose();const points=e?.physical?.path.flatMap((l,i)=>i?[l.end]:[l.start,l.end])??[];pathLine.geometry=new THREE.BufferGeometry().setFromPoints(points);pathLine.visible=view==='cutaway'&&points.length>1;pathMaterial.clippingPlanes=view==='cutaway'?[section.plane]:[];}
function updateReplayUI(){const available=!!replay.event;for(const id of ['replay','step','timeline'])document.querySelector<HTMLButtonElement>('#'+id)!.disabled=!available;document.querySelector<HTMLButtonElement>('#inspect')!.disabled=!events.length;document.querySelector<HTMLInputElement>('#timeline')!.value=String(replay.frame);document.querySelector('#replay')!.textContent=replay.playing?'Pause':'Replay';document.body.classList.toggle('replaying',replay.playing);}
function replayPose(){const marks=replay.frame>=10;if(marks!==replayMarks){replayMarks=marks;const shown=marks?events:events.slice(0,-1);updateDamageMaterials(structures,shown);wounds.update(structures,shown);wounds.setView(view,section.plane);}const factor=replay.event?.physical?.response[replay.frame]??1;bones?.pose(Math.min(1,Math.max(0,(factor-.22)/.78)),replay.event?.id);const e=replay.event;projectileTip.visible=!!e&&e.tool==='projectile'&&replay.frame<28&&replay.frame>0;if(projectileTip.visible){const legs=e!.physical!.path,total=legs.reduce((a,l)=>a+l.start.distanceTo(l.end),0);let distance=total*Math.min(1,replay.frame/28);for(const leg of legs){const len=leg.start.distanceTo(leg.end);if(distance<=len){projectileTip.position.copy(leg.start).lerp(leg.end,distance/Math.max(.000001,len));break;}distance-=len;}}if(view==='cutaway'){section.clear();section.update(structures,events,true,sectionOffset);wounds.setView(view,section.plane);}updateReplayUI();render();}
function finishReplay(){replay.finish();if(!replayMarks){replayMarks=true;updateDamageMaterials(structures,events);wounds.update(structures,events);wounds.setView(view,section.plane);}bones?.pose(1);projectileTip.visible=false;updateReplayUI();updateUI();}
function startReplay(rate=Number(document.querySelector<HTMLSelectElement>('#speed')!.value)){if(!replay.event)return;replay.rate=rate;replay.clock=0;replay.seek(0);replay.playing=true;replayPose();updateUI();lastTick=performance.now();render();}
document.querySelector('#replay')!.addEventListener('click',()=>{if(replay.playing){replay.playing=false;updateReplayUI();updateUI();}else startReplay();});document.querySelector('#step')!.addEventListener('click',()=>{replay.playing=false;replay.seek(replay.frame>=96?0:replay.frame+1);replay.clock=replay.frame/120;replayPose();updateUI();});document.querySelector('#timeline')!.addEventListener('input',e=>{replay.playing=false;replay.seek(Number((e.target as HTMLInputElement).value));replay.clock=replay.frame/120;replayPose();updateUI();});
function setQuality(q:string){quality=['mobile','balanced','ultra'].includes(q)?q:'balanced';renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='mobile'?1:quality==='ultra'?1.75:1.25));document.querySelector<HTMLSelectElement>('#quality')!.value=quality;resize();saveSettings();}document.querySelector('#quality')!.addEventListener('change',e=>setQuality((e.target as HTMLSelectElement).value));
function setSectionMode(mode:SectionMode){section.mode=mode;section.freeNormal=null;section.clear();sectionOffset=0;document.querySelector<HTMLInputElement>('#section')!.value='50';document.querySelector<HTMLSelectElement>('#section-mode')!.value=mode;section.update(structures,events,view==='cutaway',0);wounds.setView(view,section.plane);if(view==='cutaway'){stopOrbit();const distance=Math.max(.55,camera.position.distanceTo(controls.target));const point=events.at(-1)?.point??controls.target;controls.target.copy(point);camera.position.copy(point).addScaledVector(section.plane.normal,-distance);if(mode==='axial')camera.position.z+=.12;else camera.position.y+=.04;controls.update();}updatePath();render();}
document.querySelector('#section-mode')!.addEventListener('change',e=>setSectionMode((e.target as HTMLSelectElement).value as SectionMode));document.querySelector('#align-plane')!.addEventListener('click',()=>{section.mode='free';section.freeNormal=camera.getWorldDirection(new THREE.Vector3());document.querySelector<HTMLSelectElement>('#section-mode')!.value='free';section.clear();section.update(structures,events,view==='cutaway',sectionOffset);wounds.setView(view,section.plane);updatePath();render();});
const inspectDialog=document.querySelector<HTMLDialogElement>('#event-dialog')!;
function inspectEvent(id:number){selectedEvent=id;const e=events[id];if(!e)return;updatePath();const list=document.querySelector('#event-detail')!;list.replaceChildren();const p=document.createElement('p');p.textContent=`${e.tool==='impact'?'Impact':'Projectile'} · SIMULATED CONTACT`;list.append(p);const path=document.createElement('p');path.textContent=`${e.physical?.path.length??1} path segments · ${e.physical?.fractures.length??0} structural failures`;list.append(path);const pos=document.createElement('small');pos.textContent=`Entry ${e.point.toArray().map(x=>x.toFixed(3)).join(', ')} · model coordinates`;list.append(pos);const ul=document.createElement('ul');for(const c of e.physical?.contacts??[]){const li=document.createElement('li');li.textContent=`${structures.find(s=>s.id===c.id)?.name??c.id}: ${c.state}`;ul.append(li);}list.append(ul);const note=document.createElement('small');note.textContent='Illustrative disruption. Local displacement and openings persist until undo/reset. Latest event has recorded replay.';list.append(note);render();}
document.querySelector('#inspect')!.addEventListener('click',()=>{const list=document.querySelector<HTMLSelectElement>('#event-list')!;list.replaceChildren();for(const e of events){const o=document.createElement('option');o.value=String(e.id);o.textContent=`Event ${e.id+1} · ${e.tool}`;list.append(o);}list.value=String(selectedEvent<0?events.length-1:selectedEvent);inspectEvent(Number(list.value));inspectDialog.showModal();});document.querySelector('#event-list')!.addEventListener('change',e=>inspectEvent(Number((e.target as HTMLSelectElement).value)));document.querySelector('#close-inspect')!.addEventListener('click',()=>inspectDialog.close());
const guard=new GestureGuard();renderer.domElement.addEventListener('pointerdown',e=>guard.down(e.pointerId,e.clientX,e.clientY,e.timeStamp));renderer.domElement.addEventListener('pointermove',e=>guard.move(e.pointerId,e.clientX,e.clientY));renderer.domElement.addEventListener('pointercancel',()=>guard.cancel());renderer.domElement.addEventListener('pointerup',e=>{if(!guard.up(e.pointerId,e.timeStamp)||!structures.length)return;const r=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);contact=pickContact(structures,ray,view==='cutaway'?section.plane:undefined);showMarker=!!contact;updateUI();});
document.querySelector<HTMLButtonElement>('#apply')!.onclick=apply;document.querySelector<HTMLButtonElement>('#undo')!.onclick=undo;document.querySelector<HTMLButtonElement>('#reset')!.onclick=reset;
function setIntensity(i:number){intensity=i;document.querySelectorAll<HTMLButtonElement>('[data-intensity]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.intensity)===i)));updateUI();saveSettings();}document.querySelectorAll<HTMLButtonElement>('[data-intensity]').forEach(b=>b.onclick=()=>setIntensity(Number(b.dataset.intensity)));
function setTool(t:Tool){tool=t;document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===t)));document.querySelector<HTMLElement>('#intensities')!.hidden=t==='projectile';document.querySelector<HTMLElement>('#projectile-note')!.hidden=t!=='projectile';document.querySelector('#apply')!.textContent=t==='impact'?'APPLY IMPACT':'FIRE PROJECTILE';updateUI();saveSettings();}document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool as Tool));
let previousCamera:THREE.Vector3|null=null;
function setView(v:View){if(view==='cutaway'&&v!=='cutaway'&&previousCamera){camera.position.copy(previousCamera);controls.update();previousCamera=null;}const entering=v==='cutaway'&&view!=='cutaway';view=v;for(const s of structures)s.mesh.visible=layerVisible(s,v);section.update(structures,events,v==='cutaway',sectionOffset);wounds.setView(v,section.plane);document.querySelector<HTMLElement>('#cut-controls')!.hidden=v!=='cutaway';if(entering){previousCamera=camera.position.clone();const distance=camera.position.distanceTo(controls.target);camera.position.copy(controls.target).addScaledVector(section.plane.normal,-distance*.62).add(new THREE.Vector3(0,.035,distance*.64));controls.update();}document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===v)));updateUI();saveSettings();updatePath();}
function stopOrbit(){controls.enableDamping=false;controls.update();controls.enableDamping=true;}
function focus(part:string){stopOrbit();previousCamera=null;if(part==='head'){controls.target.set(0,.465,-.02);camera.position.set(0,.47,.63);}else{controls.target.set(0,-.015,0);camera.position.set(0,.015,1.28);}controls.update();render();}document.querySelectorAll<HTMLButtonElement>('[data-focus]').forEach(b=>b.onclick=()=>focus(b.dataset.focus!));
document.querySelector<HTMLButtonElement>('#home')!.onclick=()=>{stopOrbit();previousCamera=null;camera.position.set(0,.13,1.65);controls.target.set(0,.09,0);controls.update();camera.updateMatrixWorld();render();};
document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view as View));let sectionFrame=0;document.querySelector<HTMLInputElement>('#section')!.oninput=e=>{sectionOffset=(Number((e.target as HTMLInputElement).value)-50)*(section.mode==='axial'?.008:.004);if(!sectionFrame)sectionFrame=requestAnimationFrame(()=>{sectionFrame=0;section.update(structures,events,view==='cutaway',sectionOffset);wounds.setView(view,section.plane);updatePath();render();});};
function resize(){const r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();render();}new ResizeObserver(resize).observe(stage);
const frameTimes:number[]=[];function loop(){frameId=0;if(!running)return;const now=performance.now();const advanced=replay.tick((now-lastTick)/1000);lastTick=now;if(advanced){replayPose();if(!replay.playing){finishReplay();updateUI();}}const moving=controls.update();if(dirty||moving){const start=performance.now();renderer.render(scene,camera);frameTimes.push(performance.now()-start);if(frameTimes.length>300)frameTimes.shift();dirty=false;const a=Math.atan2(camera.position.x,camera.position.z);document.querySelector('#direction')!.textContent=Math.abs(a)<.4?'ANTERIOR':Math.abs(a)>2.7?'POSTERIOR':a>0?'LEFT ASPECT':'RIGHT ASPECT';document.querySelector('#sides')!.textContent=Math.abs(a)<.4?'R · L':Math.abs(a)>2.7?'L · R':'';}if((moving||replay.playing)&&!frameId)frameId=requestAnimationFrame(loop);}
document.addEventListener('visibilitychange',()=>{running=!document.hidden;guard.cancel();if(!running){cancelAnimationFrame(frameId);frameId=0;}else{lastTick=performance.now();render();}});controls.addEventListener('change',render);render();
const dialog=document.querySelector<HTMLDialogElement>('#about-dialog')!;document.querySelector<HTMLButtonElement>('#about')!.onclick=()=>dialog.showModal();document.querySelector<HTMLButtonElement>('#close-about')!.onclick=()=>dialog.close();document.querySelector<HTMLButtonElement>('#credits')!.onclick=async()=>{const n=document.querySelector<HTMLElement>('#notices')!;n.hidden=!n.hidden;if(!n.textContent){try{n.textContent=(await Promise.all(['Z-Anatomy.txt','BodyParts3D.txt'].map(p=>fetch('./licenses/'+p).then(r=>r.text())))).join('\n\n')}catch{n.textContent='Notices are bundled in the source under public/licenses.';}}};
loadAnatomy().then(s=>{roots=s;structures=s;bones=new FractureGeometry(roots,installDamageMaterial);for(const a of s){installDamageMaterial(a);scene.add(a.mesh);}let saved:any={};try{saved=JSON.parse(localStorage.getItem('impact-core-settings')??'{}')}catch{};setQuality(saved.quality??'balanced');setIntensity([0,1,2].includes(saved.intensity)?saved.intensity:1);setTool(saved.tool==='projectile'?'projectile':'impact');setView(['skin','muscle','skeleton','organs','cutaway'].includes(saved.view)?saved.view:'skin');try{const savedDamage=localStorage.getItem('impact-core-damage-v2');if(savedDamage){const restored=restoreEvents(savedDamage);events=restored.slice(0,-1);redrawDamage();replay.captureBefore(structures);events=restored;redrawDamage();if(events.length)replay.captureAfter(structures,events.at(-1)!);selectedEvent=events.length-1;}}catch{localStorage.removeItem('impact-core-damage-v2');}document.querySelector('#loading')!.remove();(window as any).__core={setView,setTool,setIntensity,apply,reset,undo,setQuality,setSectionMode,finishReplay,seekReplay:(frame:number)=>{replay.playing=false;replay.seek(frame);replayPose();},replayState:()=>({frame:replay.frame,playing:replay.playing,bytes:replay.memoryBytes()}),probePoint:(x:number,y:number,z:number)=>{const ray=new THREE.Raycaster(camera.position,new THREE.Vector3(x,y,z).sub(camera.position).normalize()),c=pickContact(structures,ray);const e=c?computeEvent(structures,c,'projectile',1,events.length,events):null;return {fractures:e?.physical?.fractures.map(f=>f.id),point:c?.point.toArray()};},physics:()=>({state:[...summarizeState(events)],fragments:bones.pieces.length,simulationTimes,records:events.map(e=>e.physical)}),save:()=>serializeEvents(events),events:()=>events.map(e=>({tool:e.tool,point:e.point.toArray(),end:e.end.toArray(),exit:e.exit?.toArray(),regions:e.regions.map(r=>({id:r.id,strength:r.strength,point:r.point.toArray()}))})),setCamera:(x:number,y:number,z:number)=>{camera.position.set(x,y,z);controls.update();render()},lesions:()=>projectileLesions(events).map(l=>({skinId:l.skinId,count:l.count,radius:l.radius,depth:l.depth,exit:l.exit})),section:()=>({caps:section.caps.length}),structures:()=>structures.map(s=>({id:s.id,name:s.name,layer:s.layer,vertices:s.base.length/3})),frameTimes:()=>frameTimes,renderer:()=>renderer.info,rawPositions:()=>roots.filter(s=>s.layer!=='bone').map(s=>({id:s.id,positions:Array.from(s.mesh.geometry.attributes.position.array)})),projectPoint:(x:number,y:number,z:number)=>{const p=new THREE.Vector3(x,y,z).project(camera),r=renderer.domElement.getBoundingClientRect();return [r.left+(p.x+1)*r.width/2,r.top+(1-p.y)*r.height/2]},focus,ready:true};resize();}).catch(e=>{document.querySelector('#loading')!.textContent='Unable to load bundled anatomy. Reopen the app.';console.error(e)});
