import './style.css';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {loadAnatomy,type View,type Structure} from './anatomy';
import {computeEvent,applyDeformation,MAX_EVENTS,type DamageEvent,type Contact,type Tool} from './damage';
import {installDamageMaterial,updateDamageMaterials} from './damage-render';
import {pickContact,refreshContact,GestureGuard} from './interaction';
import {SectionRenderer} from './section';
import {WoundRenderer} from './wounds';
const stage=document.querySelector<HTMLElement>('#stage')!;
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});
renderer.localClippingEnabled=true;renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor('#e9e7df',1);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;stage.append(renderer.domElement);
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(37,1,.01,10);camera.position.set(0,.015,1.28);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,-.015,0);controls.enablePan=false;controls.enableDamping=true;controls.minDistance=.58;controls.maxDistance=1.9;controls.minPolarAngle=.4;controls.maxPolarAngle=2.65;controls.rotateSpeed=.65;
scene.add(new THREE.HemisphereLight('#fff5e4','#788b7c',1.65));
function light(x:number,y:number,z:number,intensity:number){const l=new THREE.DirectionalLight('#fff5e8',intensity);l.position.set(x,y,z);scene.add(l);return l;}
const key=light(-1,1.4,1.4,2.6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-.55;key.shadow.camera.right=.55;key.shadow.camera.top=.7;key.shadow.camera.bottom=-.6;key.shadow.camera.near=.1;key.shadow.camera.far=5;key.shadow.bias=-.00015;key.shadow.normalBias=.002;
light(1,.4,-1,1.9);light(1,.2,1,.65);
const standMat=new THREE.MeshStandardMaterial({color:'#777c70',roughness:.86});
const post=new THREE.Mesh(new THREE.CylinderGeometry(.019,.022,.10,32),standMat);post.position.set(0,-.36,0);scene.add(post);
const base=new THREE.Mesh(new THREE.CylinderGeometry(.14,.15,.025,64),standMat);base.position.y=-.416;base.receiveShadow=true;scene.add(base);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),new THREE.ShadowMaterial({opacity:.13}));ground.rotation.x=-Math.PI/2;ground.position.y=-.43;ground.receiveShadow=true;scene.add(ground);
const section=new SectionRenderer(),wounds=new WoundRenderer();scene.add(section.group,wounds.group);
let structures:Structure[]=[],view:View='skin',events:DamageEvent[]=[],contact:Contact|null=null,tool:Tool='impact',intensity=1,showMarker=false,sectionOffset=0,dirty=true;
const marker=new THREE.Mesh(new THREE.RingGeometry(.007,.009,32),new THREE.MeshBasicMaterial({color:'#e3bd68',side:THREE.DoubleSide}));marker.visible=false;scene.add(marker);
function render(){dirty=true;}
function saveSettings(){try{localStorage.setItem('impact-core-settings',JSON.stringify({view,tool,intensity}));}catch{}}
function updateUI(){document.querySelector<HTMLButtonElement>('#apply')!.disabled=!contact||events.length>=MAX_EVENTS;document.querySelector<HTMLButtonElement>('#undo')!.disabled=!events.length;document.querySelector('#status')!.textContent=events.length>=MAX_EVENTS?'Session limit · Undo or reset':events.length?'Localized illustrative damage':tool==='impact'?'Intact · '+['Light','Medium','Strong'][intensity]+' impact':'Intact · Fictional projectile';marker.visible=!!contact&&showMarker&&view==='skin';if(contact){refreshContact(contact,structures.find(s=>s.layer==='skin')!);marker.position.copy(contact.point).addScaledVector(contact.normal,.0015);marker.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),contact.normal);}document.querySelector('#selection')!.textContent=contact?(contact.selectedName==='Skin'?'Surface contact':contact.selectedName):'Tap the torso to select a contact';render();}
function redrawDamage(){applyDeformation(structures,events);updateDamageMaterials(structures,events);wounds.update(structures,events);section.update(structures,events,view==='cutaway',sectionOffset);wounds.setView(view,section.plane);updateUI();}
function apply(){if(!contact||events.length>=MAX_EVENTS)return;refreshContact(contact,structures.find(s=>s.layer==='skin')!);const e=computeEvent(structures,contact,tool,intensity,events.length);if(e){events.push(e);showMarker=false;redrawDamage();}else document.querySelector('#status')!.textContent='No enclosed tissue at this contact';}
function reset(){events=[];contact=null;sectionOffset=0;document.querySelector<HTMLInputElement>('#section')!.value='50';redrawDamage();}
const guard=new GestureGuard();renderer.domElement.addEventListener('pointerdown',e=>guard.down(e.pointerId,e.clientX,e.clientY,e.timeStamp));renderer.domElement.addEventListener('pointermove',e=>guard.move(e.pointerId,e.clientX,e.clientY));renderer.domElement.addEventListener('pointercancel',()=>guard.cancel());renderer.domElement.addEventListener('pointerup',e=>{if(!guard.up(e.pointerId,e.timeStamp)||!structures.length)return;const r=renderer.domElement.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);contact=pickContact(structures,ray,view==='cutaway'?section.plane:undefined);showMarker=!!contact;updateUI();});
document.querySelector<HTMLButtonElement>('#apply')!.onclick=apply;document.querySelector<HTMLButtonElement>('#undo')!.onclick=()=>{events.pop();redrawDamage()};document.querySelector<HTMLButtonElement>('#reset')!.onclick=reset;
function setIntensity(i:number){intensity=i;document.querySelectorAll<HTMLButtonElement>('[data-intensity]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.intensity)===i)));updateUI();saveSettings();}document.querySelectorAll<HTMLButtonElement>('[data-intensity]').forEach(b=>b.onclick=()=>setIntensity(Number(b.dataset.intensity)));
function setTool(t:Tool){tool=t;document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===t)));document.querySelectorAll<HTMLButtonElement>('[data-intensity]').forEach(b=>b.disabled=t==='projectile');document.querySelector('#apply')!.textContent=t==='impact'?'APPLY IMPACT':'APPLY PROJECTILE';updateUI();saveSettings();}document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool as Tool));
function setView(v:View){const entering=v==='cutaway'&&view!=='cutaway';view=v;for(const s of structures)s.mesh.visible=v==='skin'?s.layer==='skin':v==='muscle'?s.layer==='muscle'||s.layer==='bone':v==='skeleton'?s.layer==='bone':v==='organs'?s.layer==='organ'&&s.name!=='Diaphragm':true;section.update(structures,events,v==='cutaway',sectionOffset);wounds.setView(v,section.plane);document.querySelector<HTMLElement>('#cut-controls')!.hidden=v!=='cutaway';if(entering){camera.position.copy(section.plane.normal).multiplyScalar(-.84).add(new THREE.Vector3(0,.10,.83));controls.update();}document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===v)));updateUI();saveSettings();}
document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view as View));document.querySelector<HTMLInputElement>('#section')!.oninput=e=>{sectionOffset=(Number((e.target as HTMLInputElement).value)-50)*.0025;section.update(structures,events,view==='cutaway',sectionOffset);render();};
function resize(){const r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();render();}new ResizeObserver(resize).observe(stage);
let lastFrame=0,running=true;const frameTimes:number[]=[];function loop(t:number){requestAnimationFrame(loop);if(!running||t-lastFrame<32)return;lastFrame=t;const moving=controls.update();if(dirty||moving){const start=performance.now();renderer.render(scene,camera);frameTimes.push(performance.now()-start);if(frameTimes.length>300)frameTimes.shift();dirty=false;const a=Math.atan2(camera.position.x,camera.position.z);document.querySelector('#direction')!.textContent=Math.abs(a)<.4?'ANTERIOR':Math.abs(a)>2.7?'POSTERIOR':a>0?'LEFT ASPECT':'RIGHT ASPECT';document.querySelector('#sides')!.textContent=Math.abs(a)<.4?'R · L':Math.abs(a)>2.7?'L · R':'';}}document.addEventListener('visibilitychange',()=>{running=!document.hidden;guard.cancel();if(running)render()});controls.addEventListener('change',render);requestAnimationFrame(loop);
const dialog=document.querySelector<HTMLDialogElement>('#about-dialog')!;document.querySelector<HTMLButtonElement>('#about')!.onclick=()=>dialog.showModal();document.querySelector<HTMLButtonElement>('#close-about')!.onclick=()=>dialog.close();document.querySelector<HTMLButtonElement>('#credits')!.onclick=async()=>{const n=document.querySelector<HTMLElement>('#notices')!;n.hidden=!n.hidden;if(!n.textContent){try{n.textContent=await(await fetch('./licenses/Z-Anatomy.txt')).text()}catch{n.textContent='Notices are bundled in the source under public/licenses.';}}};
loadAnatomy().then(s=>{structures=s;for(const a of s){installDamageMaterial(a);scene.add(a.mesh);}let saved:any={};try{saved=JSON.parse(localStorage.getItem('impact-core-settings')??'{}')}catch{};setIntensity([0,1,2].includes(saved.intensity)?saved.intensity:1);setTool(saved.tool==='projectile'?'projectile':'impact');setView(['skin','muscle','skeleton','organs','cutaway'].includes(saved.view)?saved.view:'skin');document.querySelector('#loading')!.remove();(window as any).__core={setView,setTool,setIntensity,apply,reset,events:()=>events.map(e=>({tool:e.tool,point:e.point.toArray(),end:e.end.toArray(),exit:e.exit?.toArray(),regions:e.regions.map(r=>({id:r.id,strength:r.strength,point:r.point.toArray()}))})),setCamera:(x:number,y:number,z:number)=>{camera.position.set(x,y,z);controls.update();render()},section:()=>({caps:section.caps.length}),structures:()=>structures.map(s=>({id:s.id,name:s.name,layer:s.layer,vertices:s.base.length/3})),frameTimes:()=>frameTimes,renderer:()=>renderer.info,ready:true};resize();}).catch(e=>{document.querySelector('#loading')!.textContent='Unable to load bundled anatomy. Reopen the app.';console.error(e)});
