import * as THREE from 'three';
import type {Structure} from './anatomy';
import type {DamageEvent,Contact} from './damage';
import {projectileLesions,tissueLesions,tissueRadius} from './lesions';
import {materialResistance,damageStage,accumulatedLoad,type PhysicalRecord} from './physics-state';
// Continuous synthetic host fills spaces between embedded anatomy; fictional units.
export function gelResistanceAt(point:THREE.Vector3,previous:DamageEvent[]){return previous.some(e=>e.tool==='projectile'&&e.physical?.path.some(l=>new THREE.Line3(l.start,l.end).closestPointToPoint(point,true,new THREE.Vector3()).distanceTo(point)<.006))?.08:.70;}
interface Crossing {distance:number;point:THREE.Vector3;normal:THREE.Vector3;s:Structure;}
// Continuous ray segments consume state-aware material energy. At most two bone
// responses per shot; no sampled-position projectile can tunnel through a shell.
export function solvePath(structures:Structure[],contact:Contact,previous:DamageEvent[],initialEnergy=1){let origin=contact.point.clone().addScaledVector(contact.direction,-.002),direction=contact.direction.clone().normalize(),energy=initialEnergy,travel=0,bends=0;const record:PhysicalRecord={contacts:[],fractures:[],path:[],response:[],duration:.8},tracks:{id:string;start:THREE.Vector3;end:THREE.Vector3;direction:THREE.Vector3}[]=[];let exit:THREE.Vector3|null=null;const hitBones=new Set<string>(),openings=projectileLesions(previous),channels=tissueLesions(previous);const effectiveResistance=(s:Structure,point:THREE.Vector3)=>{if(s.layer!=='bone'&&channels.some(c=>c.id===s.id&&new THREE.Line3(c.start,c.end).closestPointToPoint(point,true,new THREE.Vector3()).distanceTo(point)<tissueRadius(s.layer,c.count)*.85))return .06;return materialResistance(s,point,previous);};
 for(let leg=0;leg<4&&energy>.025&&travel<.60;leg++){const ray=new THREE.Raycaster(origin,direction,0,.60-travel),hits:Crossing[]=[];for(const s of structures){s.mesh.updateMatrixWorld();for(const h of ray.intersectObject(s.mesh,false)){if(h.distance<.00008)continue;const normal=h.face!.normal.clone();const last=hits.at(-1);if(last?.s===s&&Math.abs(last.distance-h.distance)<.000015)continue;hits.push({distance:h.distance,point:h.point.clone(),normal,s});}}hits.sort((a,b)=>a.distance-b.distance);const unique=hits.filter((h,i)=>!i||h.s.id!==hits[i-1].s.id||Math.abs(h.distance-hits[i-1].distance)>.00002);const inside=new Map<string,{s:Structure;start:number}>();for(const s of structures){const first=unique.find(h=>h.s===s);if(first&&first.normal.dot(direction)>0&&s.layer!=='skin')inside.set(s.id,{s,start:0});}
 let inGel=unique.find(h=>h.s.layer==='skin')?.normal.dot(direction)!>0;let cursor=0,changed=false,stopped=false;const legEnergy=energy,legStart=origin.clone();
 const consume=(to:number)=>{const active=[...inside.values()];const midpoint=origin.clone().addScaledVector(direction,(cursor+to)*.5);const cost=Math.max(inGel?gelResistanceAt(midpoint,previous):.045,...active.map(a=>effectiveResistance(a.s,midpoint)));const length=Math.max(0,to-cursor),possible=energy/(cost*5);const end=cursor+Math.min(length,possible);for(const a of active){if(end>cursor+.00001){const start=origin.clone().addScaledVector(direction,cursor),finish=origin.clone().addScaledVector(direction,end);const last=tracks.at(-1);if(last&&last.id===a.s.id&&last.end.distanceTo(start)<.00005)last.end.copy(finish);else tracks.push({id:a.s.id,start,end:finish,direction:direction.clone()});}}energy=Math.max(0,energy-(end-cursor)*cost*5);cursor=end;return end>=to-.000001;};
 for(const h of unique){if(!consume(h.distance)){stopped=true;break;}const facing=h.normal.dot(direction),entry=facing<0;
  if(h.s.layer==='skin'){if(entry){inGel=true;const before=energy;const open=openings.some(l=>l.skinId===h.s.id&&l.point.distanceTo(h.point)<l.radius&&l.normal.dot(direction)<-.1);energy=Math.max(0,energy-(open?.006:.045));record.contacts.push({id:h.s.id,layer:'skin',point:h.point.clone(),direction:direction.clone(),energyIn:before,energyOut:energy,state:'disrupted'});}else if(h.distance>.008||travel>.008){exit=h.point.clone();cursor=h.distance;stopped=true;break;}continue;}
  if(entry){const before=energy,prior=accumulatedLoad(previous,h.s.mesh.userData.parentId??h.s.id,h.point),bone=h.s.layer==='bone';const loss=bone?Math.min(energy,.19*Math.max(.25,1-prior*.3)):.018;energy=Math.max(0,energy-loss);record.contacts.push({id:h.s.id,layer:h.s.layer,point:h.point.clone(),direction:direction.clone(),energyIn:before,energyOut:energy,state:damageStage(h.s.layer,bone?before+prior*.45:before)});inside.set(h.s.id,{s:h.s,start:h.distance});
   if(bone&&!hitBones.has(h.s.id)&&bends<2&&energy>.04){hitBones.add(h.s.id);bends++;const outward=h.normal.clone();if(outward.dot(direction)>0)outward.negate();let tangent=outward.addScaledVector(direction,-outward.dot(direction));if(tangent.lengthSq()<.002)tangent.crossVectors(direction,new THREE.Vector3(.31,1,.17));tangent.normalize();const turn=.20+.18*(1-Math.abs(facing));const next=direction.clone().addScaledVector(tangent,turn).normalize();record.path.push({start:legStart,end:h.point.clone(),energyIn:legEnergy,energyOut:energy});travel+=h.distance;origin=h.point.clone().addScaledVector(next,.00025);direction=next;changed=true;break;}
  }else inside.delete(h.s.id);
 }
 if(changed)continue;if(!stopped)consume(Math.min(.60-travel,unique.at(-1)?.distance??.03));const end=origin.clone().addScaledVector(direction,cursor);record.path.push({start:legStart,end,energyIn:legEnergy,energyOut:energy});travel+=cursor;break;
 }
 return {physical:record,tracks,end:record.path.at(-1)?.end.clone()??contact.point.clone(),exit};
}
