import * as THREE from 'three';
import type {Structure,Layer} from './anatomy';
import type {DamageEvent} from './damage';
export type DamageStage='intact'|'stressed'|'deformed'|'disrupted'|'fractured'|'separated';
export interface ContactStep {id:string;layer:Layer;point:THREE.Vector3;direction:THREE.Vector3;energyIn:number;energyOut:number;state:DamageStage;}
export interface Fracture {id:string;point:THREE.Vector3;direction:THREE.Vector3;radius:number;displacement:number;angle:number;}
export interface PathLeg {start:THREE.Vector3;end:THREE.Vector3;energyIn:number;energyOut:number;}
export interface PhysicalRecord {contacts:ContactStep[];fractures:Fracture[];path:PathLeg[];response:number[];responseById?:Record<string,number[]>;duration:number;}
export const FIXED_DT=1/120,REPLAY_FRAMES=97,MAX_FRAGMENTS=12;
// One damped, anchored degree of freedom drives a sparse vector deformation field.
// Fixed steps and a recorded response make playback independent of render rate.
export function solveResponse(stiffness=190,damping=25){let x=0,v=13;const frames:number[]=[];for(let i=0;i<REPLAY_FRAMES;i++){frames.push(THREE.MathUtils.clamp(x,0,1.65));v+=(-stiffness*(x-1)-damping*v)*FIXED_DT;x+=v*FIXED_DT;}frames[frames.length-1]=1;return frames;}
export function solveCoupledResponse(contacts:ContactStep[]){const nodes=[...new Map(contacts.map(c=>[c.id,c])).values()].slice(0,48),x=nodes.map(()=>0),v=nodes.map(()=>0),curves:Record<string,number[]>={};for(const n of nodes)curves[n.id]=[];const neighbors=nodes.map(a=>nodes.map((b,j)=>a.point.distanceTo(b.point)<.09?j:-1).filter(j=>j>=0));for(let frame=0;frame<REPLAY_FRAMES;frame++){const next=[...v];for(let i=0;i<nodes.length;i++){const n=nodes[i],delay=Math.min(18,Math.round(i*1.5)),active=frame>=delay;if(frame===delay)v[i]=10*Math.max(.3,n.energyIn);curves[n.id].push(THREE.MathUtils.clamp(x[i],0,1.45));if(!active)continue;const mass=n.layer==='bone'?3:n.layer==='muscle'?1.3:.9,stiffness=n.layer==='bone'?440:n.layer==='skin'?180:140;let force=stiffness*(1-x[i])-26*Math.sqrt(mass)*v[i];for(const j of neighbors[i])if(j!==i)force+=24*(x[j]-x[i]);next[i]=v[i]+force/mass*FIXED_DT;}for(let i=0;i<nodes.length;i++){v[i]=next[i];x[i]=THREE.MathUtils.clamp(x[i]+v[i]*FIXED_DT,0,1.45);}}for(const curve of Object.values(curves))curve[curve.length-1]=1;return curves;}
export function damageStage(layer:Layer,load:number):DamageStage{if(load<.25)return 'stressed';if(layer==='bone')return load>=1.45?'separated':load>=.65?'fractured':'stressed';return load>=.85?'disrupted':'deformed';}
export function accumulatedLoad(events:DamageEvent[],id:string,point:THREE.Vector3){let value=0;for(const e of events)for(const c of e.physical?.contacts??[])if(c.id===id&&c.point.distanceTo(point)<.05)value+=Math.max(.08,c.energyIn-c.energyOut);return Math.min(3,value);}
export function materialResistance(s:Structure,point:THREE.Vector3,events:DamageEvent[]){const parent=s.mesh.userData.parentId??s.id;const previous=accumulatedLoad(events,parent,point);const base=s.layer==='bone'?6:s.layer==='muscle'?1.65:s.layer==='skin'?1.5:.85;return base*Math.max(.22,1-previous*.48)*(s.mesh.userData.fragment?.55:1);}
export function finalizeRecord(e:DamageEvent,structures:Structure[],previous:DamageEvent[]){const record=e.physical??{contacts:[],fractures:[],path:[{start:e.point.clone(),end:e.end.clone(),energyIn:1,energyOut:0}],response:[],duration:.8};
 if(e.tool==='impact'){const seen=new Set<string>();for(const r of e.regions){if(seen.has(r.id))continue;seen.add(r.id);const s=structures.find(s=>s.id===r.id);if(!s)continue;const load=r.strength*(s.layer==='bone'?1.65:1)+accumulatedLoad(previous,s.id,r.point)*.5;record.contacts.push({id:s.id,layer:s.layer,point:r.point.clone(),direction:e.direction.clone(),energyIn:load,energyOut:load*.35,state:damageStage(s.layer,load)});}}
 const previousFractures=previous.flatMap(e=>e.physical?.fractures??[]);for(const c of record.contacts){if(c.layer!=='bone')continue;const old=accumulatedLoad(previous,c.id,c.point),load=c.energyIn+old*.55;const s=structures.find(s=>s.id===c.id);if(!s||load<(s.mesh.userData.fragment?.12:.65))continue;let fractureId=c.id,fracturePoint=c.point.clone();if(s.mesh.userData.fragment){fractureId=s.mesh.userData.parentId;const parent=previousFractures.find(f=>f.id===fractureId);if(parent)fracturePoint.copy(parent.point);c.state='separated';}const nearby=previousFractures.filter(f=>f.id===fractureId&&f.point.distanceTo(fracturePoint)<.055);if(previousFractures.length+record.fractures.length>=MAX_FRAGMENTS&&!nearby.length)continue;c.state=load>=1.45?'separated':'fractured';record.fractures.push({id:fractureId,point:fracturePoint,direction:c.direction.clone(),radius:/rib/i.test(s.name)?.027:.038,displacement:Math.min(.025,.010+load*.007),angle:Math.min(.42,.13+load*.10)});}
 record.responseById=solveCoupledResponse(record.contacts);record.response=solveResponse(e.tool==='impact'?180:230,e.tool==='impact'?24:29);record.duration=(record.response.length-1)*FIXED_DT;e.physical=record;return e;
}
export function summarizeState(events:DamageEvent[]){const state=new Map<string,{stage:DamageStage;events:number;load:number}>();const rank:DamageStage[]=['intact','stressed','deformed','disrupted','fractured','separated'];for(const e of events)for(const c of e.physical?.contacts??[]){const old=state.get(c.id)??{stage:'intact' as DamageStage,events:0,load:0};state.set(c.id,{stage:rank.indexOf(c.state)>rank.indexOf(old.stage)?c.state:old.stage,events:old.events+1,load:Math.min(6,old.load+Math.max(0,c.energyIn-c.energyOut))});}return state;}
const vectorKeys=new Set(['point','anchor','normal','direction','end','start','exit','bary']);
export function serializeEvents(events:DamageEvent[]){return JSON.stringify({schema:2,events},(_k,v)=>v?.isVector3?[v.x,v.y,v.z]:v);}
export function restoreEvents(raw:string):DamageEvent[]{if(raw.length>4000000)throw Error('Oversized damage save');const data=JSON.parse(raw,(k,v)=>vectorKeys.has(k)&&Array.isArray(v)&&v.length===3?v.every(Number.isFinite)?new THREE.Vector3(...v):null:v);if(data.schema!==2||!Array.isArray(data.events)||data.events.length>30)throw Error('Unsupported damage save');for(const e of data.events){if((e.weapon!==undefined&&!['legacy','pistol','rifle','shotgun'].includes(e.weapon))||(e.shotId!==undefined&&(!Number.isInteger(e.shotId)||e.shotId<0))||!['impact','projectile'].includes(e.tool)||!e.point?.isVector3||!e.anchor?.isVector3||!e.direction?.isVector3||!Array.isArray(e.regions)||e.regions.length>2048||!e.physical?.response?.every(Number.isFinite)||e.physical.response.length!==97||e.physical.path.length>4||e.physical.fractures.length>12||e.physical.contacts.length>128)throw Error('Invalid damage record');}return data.events;}
