import * as THREE from 'three';
import type {Structure} from './anatomy';
import type {DamageEvent} from './damage';
export interface SparsePatch {s:Structure;indices:Uint32Array;before:Float32Array;after:Float32Array;}
export class EventReplay {patches:SparsePatch[]=[];event:DamageEvent|null=null;frame=0;playing=false;rate=1;clock=0;private snapshots=new Map<string,Float32Array>();
 captureBefore(structures:Structure[]){this.snapshots.clear();for(const s of structures)if(s.layer!=='bone'||s.mesh.userData.fragment)this.snapshots.set(s.id,new Float32Array(s.mesh.geometry.attributes.position.array));}
 captureAfter(structures:Structure[],event:DamageEvent){this.event=event;this.patches=[];for(const s of structures){let before=this.snapshots.get(s.id);const p=s.mesh.geometry.attributes.position.array;if(s.mesh.userData.fragment&&(!before||before.length!==p.length))before=s.base;if(!before)continue;const indices:number[]=[],a:number[]=[],b:number[]=[];for(let i=0;i<p.length;i+=3)if(Math.abs(p[i]-before[i])+Math.abs(p[i+1]-before[i+1])+Math.abs(p[i+2]-before[i+2])>1e-8){indices.push(i/3);a.push(before[i],before[i+1],before[i+2]);b.push(p[i],p[i+1],p[i+2]);}if(indices.length)this.patches.push({s,indices:new Uint32Array(indices),before:new Float32Array(a),after:new Float32Array(b)});}this.snapshots.clear();this.frame=(event.physical?.response.length??1)-1;this.clock=this.frame/120;}
 seek(frame:number){if(!this.event)return;const curve=this.event.physical!.response;this.frame=THREE.MathUtils.clamp(Math.round(frame),0,curve.length-1);const factor=curve[this.frame];for(const patch of this.patches){const factor=this.event.physical?.responseById?.[patch.s.mesh.userData.parentId??patch.s.id]?.[this.frame]??curve[this.frame];const p=patch.s.mesh.geometry.attributes.position;for(let j=0;j<patch.indices.length;j++){const i=j*3;p.setXYZ(patch.indices[j],patch.before[i]+(patch.after[i]-patch.before[i])*factor,patch.before[i+1]+(patch.after[i+1]-patch.before[i+1])*factor,patch.before[i+2]+(patch.after[i+2]-patch.before[i+2])*factor);}p.needsUpdate=true;patch.s.mesh.geometry.computeVertexNormals();patch.s.mesh.geometry.computeBoundingSphere();patch.s.mesh.geometry.computeBoundingBox();patch.s.mesh.geometry.boundsTree?.refit();}return factor;}
 tick(dt:number){if(!this.playing||!this.event)return false;this.clock=Math.min(this.event.physical!.duration,this.clock+Math.min(.05,dt)*this.rate);this.seek(this.clock*120);if(this.clock>=this.event.physical!.duration)this.playing=false;return true;}
 finish(){this.playing=false;if(this.event)this.seek(this.event.physical!.response.length-1);}
 clear(){this.finish();this.event=null;this.patches=[];this.snapshots.clear();this.frame=0;}
 memoryBytes(){return this.patches.reduce((a,p)=>a+p.indices.byteLength+p.before.byteLength+p.after.byteLength,0);}
}
