import * as THREE from 'three';import {tissueMaterial,type Structure} from './anatomy';import {installDamageMaterial,updateDamageMaterials} from './damage-render';import type {DamageEvent} from './damage';
export function sectionLoops(g:THREE.BufferGeometry,plane:THREE.Plane){const p=g.attributes.position,idx=g.index,segments:[THREE.Vector3,THREE.Vector3][]=[];const a=new THREE.Vector3(),b=new THREE.Vector3(),c=new THREE.Vector3();
for(let i=0;i<(idx?.count??p.count);i+=3){a.fromBufferAttribute(p,idx?idx.getX(i):i);b.fromBufferAttribute(p,idx?idx.getX(i+1):i+1);c.fromBufferAttribute(p,idx?idx.getX(i+2):i+2);const vertices=[a,b,c],ds=vertices.map(v=>plane.distanceToPoint(v));if(ds.every(d=>d>=0)||ds.every(d=>d<0))continue;const hits:THREE.Vector3[]=[];for(let j=0;j<3;j++){const k=(j+1)%3;if((ds[j]<0)!==(ds[k]<0))hits.push(vertices[j].clone().lerp(vertices[k],ds[j]/(ds[j]-ds[k])));}if(hits.length===2&&hits[0].distanceToSquared(hits[1])>1e-14)segments.push([hits[0],hits[1]]);}
const key=(v:THREE.Vector3)=>`${Math.round(v.x*100000)},${Math.round(v.y*100000)},${Math.round(v.z*100000)}`,edges=new Map<string,number[]>();segments.forEach((s,i)=>s.forEach(v=>{const k=key(v);edges.set(k,[...(edges.get(k)??[]),i]);}));const used=new Set<number>(),loops:THREE.Vector3[][]=[];
segments.forEach((segment,index)=>{if(used.has(index))return;used.add(index);const loop=[segment[0],segment[1]];let end=key(segment[1]);const start=key(segment[0]);for(let n=0;n<segments.length&&end!==start;n++){const next=(edges.get(end)??[]).find(i=>!used.has(i));if(next===undefined)break;used.add(next);const s=segments[next],v=key(s[0])===end?s[1]:s[0];loop.push(v);end=key(v);}if(end===start&&loop.length>3){loop.pop();loops.push(loop);}});return loops;}
export function makeCap(s:Structure,plane:THREE.Plane){const loops=sectionLoops(s.mesh.geometry,plane);if(!loops.length)return null;const u=new THREE.Vector3().crossVectors(plane.normal,new THREE.Vector3(0,1,0)).normalize();if(u.lengthSq()<.1)u.set(1,0,0);const v=new THREE.Vector3().crossVectors(plane.normal,u).normalize(),positions:number[]=[];const tri=(a:THREE.Vector3,b:THREE.Vector3,c:THREE.Vector3)=>{for(const p of [a,b,c])positions.push(p.x+plane.normal.x*.00015,p.y+plane.normal.y*.00015,p.z+plane.normal.z*.00015);};
for(const loop of loops){if(s.layer==='skin'){const center=loop.reduce((a,b)=>a.add(b),new THREE.Vector3()).divideScalar(loop.length);for(let i=0;i<loop.length;i++){const a=loop[i],b=loop[(i+1)%loop.length],ai=a.clone().addScaledVector(center.clone().sub(a).normalize(),.004),bi=b.clone().addScaledVector(center.clone().sub(b).normalize(),.004);tri(a,b,ai);tri(b,bi,ai);}}else for(const t of THREE.ShapeUtils.triangulateShape(loop.map(p=>new THREE.Vector2(p.dot(u),p.dot(v))),[]))tri(loop[t[0]],loop[t[1]],loop[t[2]]);}
const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.computeVertexNormals();return g;}
export class SectionRenderer {group=new THREE.Group();plane=new THREE.Plane(new THREE.Vector3(1,0,0),0);caps:Structure[]=[];clear(){for(const c of this.caps){c.mesh.geometry.dispose();c.mesh.material.dispose();}this.caps=[];this.group.clear();}
update(structures:Structure[],events:DamageEvent[],active:boolean,offset=0){this.clear();for(const s of structures)s.mesh.material.clippingPlanes=active?[this.plane]:[];if(!active)return;const event=events.at(-1),n=event?new THREE.Vector3().crossVectors(new THREE.Vector3(0,1,0),event.direction).normalize():new THREE.Vector3(1,0,0);if(n.lengthSq()<.1)n.set(1,0,0);if(n.x<0)n.negate();this.plane.setFromNormalAndCoplanarPoint(n,event?.point??new THREE.Vector3());this.plane.constant-=offset;for(const s of structures){const g=makeCap(s,this.plane);if(!g)continue;const mat=tissueMaterial(s.layer,s.name);mat.roughness=.97;const mesh=new THREE.Mesh(g,mat),cap={...s,mesh,base:new Float32Array(g.attributes.position.array),normals:new Float32Array(g.attributes.normal.array)} as Structure;installDamageMaterial(cap);this.caps.push(cap);this.group.add(mesh);}updateDamageMaterials(this.caps,events);}}
