import * as THREE from 'three';
import type {Structure} from './anatomy';
import type {DamageEvent} from './damage';
import {projectileLesions,type Lesion} from './lesions';
export class WoundRenderer {
 group=new THREE.Group();surfaces=new THREE.Group();tracks=new THREE.Group();
 constructor(){this.group.add(this.surfaces,this.tracks);}
 clear(){for(const group of [this.surfaces,this.tracks]){group.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});group.clear();}}
 update(structures:Structure[],events:DamageEvent[]){this.clear();for(const l of projectileLesions(events)){const skin=structures.find(s=>s.id===l.skinId);if(!skin)continue;this.bowl(skin,l);this.bleeding(skin,l);if(!l.exit)this.tract(l);}}
 private surfaceHit(skin:Structure,point:THREE.Vector3,normal:THREE.Vector3){const ray=new THREE.Raycaster(point.clone().addScaledVector(normal,.045),normal.clone().negate(),0,.09);return ray.intersectObject(skin.mesh,false).find(h=>h.face!.normal.dot(normal)>.1)?.point.clone()??null;}
 private surface(skin:Structure,point:THREE.Vector3,normal:THREE.Vector3){return this.surfaceHit(skin,point,normal)??point.clone();}
 private basis(n:THREE.Vector3){const u=new THREE.Vector3().crossVectors(n,new THREE.Vector3(0,1,0));if(u.lengthSq()<.01)u.set(1,0,0);u.normalize();return [u,new THREE.Vector3().crossVectors(n,u).normalize()];}
 private mesh(positions:number[],colors:number[],indices:number[],group:THREE.Group,roughness=.86){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.setIndex(indices);g.computeVertexNormals();const mesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,roughness,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1}));group.add(mesh);return mesh;}
 bowl(skin:Structure,l:Lesion){const [u,v]=this.basis(l.normal),positions:number[]=[],colors:number[]=[],indices:number[]=[],count=40;
  for(let ring=0;ring<5;ring++)for(let i=0;i<count;i++){const a=i/count*Math.PI*2,irregular=1+.08*Math.sin(a*5)+.04*Math.cos(a*9),radial=u.clone().multiplyScalar(Math.cos(a)).addScaledVector(v,Math.sin(a)),r=[1.18,.99,.74,.28,0][ring]*l.radius*irregular,base=l.point.clone().addScaledVector(radial,r),point=this.surface(skin,base,l.normal);point.addScaledVector(l.normal,[.0005,-.001,-l.depth*.32,-l.depth*.8,-l.depth][ring]);positions.push(point.x,point.y,point.z);const color=new THREE.Color(['#985d4d','#883b35','#71302d','#411b20','#27161a'][ring]);color.multiplyScalar(.9+.1*Math.sin(i*2.13));colors.push(color.r,color.g,color.b);}
  for(let r=0;r<4;r++)for(let i=0;i<count;i++){const a=r*count+i,b=r*count+(i+1)%count,c=(r+1)*count+i,d=(r+1)*count+(i+1)%count;indices.push(a,c,b,b,c,d);}this.mesh(positions,colors,indices,this.surfaces,.72);
 }
 bleeding(skin:Structure,l:Lesion){const gravity=new THREE.Vector3(0,-1,0).addScaledVector(l.normal,l.normal.y);if(gravity.lengthSq()<.08)return;gravity.normalize();const across=new THREE.Vector3().crossVectors(gravity,l.normal).normalize();
  const length=Math.min(.115,.03+Math.sqrt(l.count-1)*.024);for(let stream=0;stream<2+(l.count>3?1:0);stream++){const positions:number[]=[],colors:number[]=[],indices:number[]=[],steps=16,offset=(stream-1)*l.radius*.50,end=length*(stream===1?1:.64);for(let i=0;i<=steps;i++){const t=i/steps,d=l.radius*.85+t*end,width=(.0012+Math.min(l.count,8)*.00022)*(1-t*.82)*(stream===1?1:.65),center=l.point.clone().addScaledVector(gravity,d).addScaledVector(across,offset+Math.sin(t*7+stream)*.0018*t);const sides=[-1,1].map(side=>this.surfaceHit(skin,center.clone().addScaledVector(across,width*side),l.normal));if(sides.some(q=>!q||q.distanceTo(center)>.04))break;for(const found of sides){const q=found!.addScaledVector(l.normal,.00065);positions.push(q.x,q.y,q.z);const c=new THREE.Color('#692b29').lerp(new THREE.Color('#9a4740'),t*.6);colors.push(c.r,c.g,c.b);}}for(let i=0;i<positions.length/6-1;i++){const a=i*2;indices.push(a,a+2,a+1,a+1,a+2,a+3);}if(indices.length)this.mesh(positions,colors,indices,this.surfaces,.52);}
 }
 tract(l:Lesion){const e=l.event,dir=e.direction,origin=e.point,intervals=(e.tracks??[]).map(t=>({a:t.start.clone().sub(origin).dot(dir),b:t.end.clone().sub(origin).dot(dir)})).sort((a,b)=>a.a-b.a),merged:{a:number;b:number}[]=[];for(const i of intervals){const last=merged.at(-1);if(last&&i.a<=last.b+.001)last.b=Math.max(last.b,i.b);else merged.push({...i});}
  for(const interval of merged){const start=origin.clone().addScaledVector(dir,interval.a),end=origin.clone().addScaledVector(dir,interval.b);if(start.distanceTo(end)<.002)continue;const radius=Math.min(.011,.0045+Math.sqrt(l.count-1)*.0018),g=new THREE.TubeGeometry(new THREE.LineCurve3(start,end),12,radius,10,false),p=g.attributes.position,colors:number[]=[];for(let i=0;i<p.count;i++){const point=new THREE.Vector3().fromBufferAttribute(p,i),axial=point.clone().sub(start).dot(dir),center=start.clone().addScaledVector(dir,axial),radial=point.clone().sub(center);point.copy(center).addScaledVector(radial,.8+.2*Math.sin(i*1.71)+.15*Math.cos(axial*410));p.setXYZ(i,point.x,point.y,point.z);const c=new THREE.Color('#622a31').multiplyScalar(.83+.17*Math.sin(i*.73));colors.push(c.r,c.g,c.b);}g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.computeVertexNormals();this.tracks.add(new THREE.Mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.92,side:THREE.DoubleSide})));}
 }
 setView(view:string,plane:THREE.Plane){this.surfaces.visible=view==='skin'||view==='cutaway';this.tracks.visible=view==='cutaway';this.group.traverse(o=>{if(o instanceof THREE.Mesh)o.material.clippingPlanes=view==='cutaway'?[plane]:[];});}
}
