import * as THREE from 'three';
import type {Structure} from './anatomy';
import type {DamageEvent} from './damage';
import {projectileLesions,tissueLesions,tissueRadius,type TissueLesion,type Lesion} from './lesions';
export class WoundRenderer {
 group=new THREE.Group();surfaces=new THREE.Group();tracks=new THREE.Group();
 constructor(){this.group.add(this.surfaces,this.tracks);}
 clear(){for(const group of [this.surfaces,this.tracks]){group.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});group.clear();}}
 update(structures:Structure[],events:DamageEvent[]){this.clear();for(const l of projectileLesions(events)){const skin=structures.find(s=>s.id===l.skinId);if(!skin)continue;this.bowl(skin,l);}for(const t of tissueLesions(events)){const structure=structures.find(s=>s.id===t.id);if(structure&&!(structure.layer==='bone'&&events.some(e=>e.physical?.fractures.some(f=>f.id===(structure.mesh.userData.parentId??structure.id)))))this.tract(t,structure);}}
 private surfaceHit(skin:Structure,point:THREE.Vector3,normal:THREE.Vector3){const ray=new THREE.Raycaster(point.clone().addScaledVector(normal,.045),normal.clone().negate(),0,.09);return ray.intersectObject(skin.mesh,false).find(h=>h.face!.normal.dot(normal)>.1)?.point.clone()??null;}
 private surface(skin:Structure,point:THREE.Vector3,normal:THREE.Vector3){return this.surfaceHit(skin,point,normal)??point.clone();}
 private basis(n:THREE.Vector3){const u=new THREE.Vector3().crossVectors(n,new THREE.Vector3(0,1,0));if(u.lengthSq()<.01)u.set(1,0,0);u.normalize();return [u,new THREE.Vector3().crossVectors(n,u).normalize()];}
 private mesh(positions:number[],colors:number[],indices:number[],group:THREE.Group,roughness=.86){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.setIndex(indices);g.computeVertexNormals();const mesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,roughness,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1}));group.add(mesh);return mesh;}
 bowl(skin:Structure,l:Lesion){const [u,v]=this.basis(l.normal),positions:number[]=[],colors:number[]=[],indices:number[]=[],count=40;
  for(let ring=0;ring<5;ring++)for(let i=0;i<count;i++){const a=i/count*Math.PI*2,irregular=1+.08*Math.sin(a*5)+.04*Math.cos(a*9),radial=u.clone().multiplyScalar(Math.cos(a)).addScaledVector(v,Math.sin(a)),r=[1.18,.99,.74,.28,0][ring]*l.radius*irregular,base=l.point.clone().addScaledVector(radial,r),point=this.surface(skin,base,l.normal);point.addScaledVector(l.normal,[.0005,-.001,-l.depth*.32,-l.depth*.8,-l.depth][ring]);positions.push(point.x,point.y,point.z);const color=new THREE.Color(['#ba8d39','#9c742f','#675228','#3d3925','#25352d'][ring]);color.multiplyScalar(.9+.1*Math.sin(i*2.13));colors.push(color.r,color.g,color.b);}
  for(let r=0;r<4;r++)for(let i=0;i<count;i++){const a=r*count+i,b=r*count+(i+1)%count,c=(r+1)*count+i,d=(r+1)*count+(i+1)%count;indices.push(a,c,b,b,c,d);}this.mesh(positions,colors,indices,this.surfaces,.72);
 }
 bleeding(skin:Structure,l:Lesion){const gravity=new THREE.Vector3(0,-1,0).addScaledVector(l.normal,l.normal.y);if(gravity.lengthSq()<.08)return;gravity.normalize();const across=new THREE.Vector3().crossVectors(gravity,l.normal).normalize();
  const length=Math.min(.115,.03+Math.sqrt(l.count-1)*.024);for(let stream=0;stream<2+(l.count>3?1:0);stream++){const positions:number[]=[],colors:number[]=[],indices:number[]=[],steps=16,offset=(stream-1)*l.radius*.50,end=length*(stream===1?1:.64);for(let i=0;i<=steps;i++){const t=i/steps,d=l.radius*.85+t*end,width=(.0012+Math.min(l.count,8)*.00022)*(1-t*.82)*(stream===1?1:.65),center=l.point.clone().addScaledVector(gravity,d).addScaledVector(across,offset+Math.sin(t*7+stream)*.0018*t);const sides=[-1,1].map(side=>this.surfaceHit(skin,center.clone().addScaledVector(across,width*side),l.normal));if(sides.some(q=>!q||q.distanceTo(center)>.04))break;for(const found of sides){const q=found!.addScaledVector(l.normal,.00065);positions.push(q.x,q.y,q.z);const c=new THREE.Color('#692b29').lerp(new THREE.Color('#9a4740'),t*.6);colors.push(c.r,c.g,c.b);}}for(let i=0;i<positions.length/6-1;i++){const a=i*2;indices.push(a,a+2,a+1,a+1,a+2,a+3);}if(indices.length)this.mesh(positions,colors,indices,this.surfaces,.52);}
 }
 tract(t:TissueLesion,s:Structure){const {start,end,direction:dir}=t;if(start.distanceTo(end)<.001)return;const radius=tissueRadius(s.layer,t.count),g=new THREE.TubeGeometry(new THREE.LineCurve3(start,end),16,radius*1.09,20,false),p=g.attributes.position,colors:number[]=[];
  for(let i=0;i<p.count;i++){const point=new THREE.Vector3().fromBufferAttribute(p,i),axial=point.clone().sub(start).dot(dir),center=start.clone().addScaledVector(dir,axial),radial=point.clone().sub(center);point.copy(center).addScaledVector(radial,1.+.04*Math.sin(axial*560.));p.setXYZ(i,point.x,point.y,point.z);const c=new THREE.Color(s.layer==='bone'?'#785d4d':s.layer==='muscle'?'#773332':'#54262e');c.multiplyScalar(.75+.25*Math.sin(i*1.17)**2);colors.push(c.r,c.g,c.b);}
  g.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));g.computeVertexNormals();const mesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.91,side:THREE.DoubleSide}));mesh.userData.layer=s.layer;this.tracks.add(mesh);
  // Close the terminal cross-section so a stopped track cannot expose an empty shell.
  const cap=new THREE.Mesh(new THREE.CircleGeometry(radius*1.09,20),new THREE.MeshStandardMaterial({color:s.layer==='bone'?'#624639':'#351820',roughness:.95,side:THREE.DoubleSide}));cap.position.copy(end);cap.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),dir);cap.userData.layer=s.layer;this.tracks.add(cap);
 }
 setView(view:string,plane:THREE.Plane){this.surfaces.visible=view==='skin'||view==='cutaway';this.tracks.visible=view!=='skin';for(const o of this.tracks.children)o.visible=view==='cutaway'||(view==='skin'&&o.userData.layer==='organ')||(view==='muscle'&&(o.userData.layer==='muscle'||o.userData.layer==='bone'))||(view==='skeleton'&&o.userData.layer==='bone')||(view==='organs'&&o.userData.layer==='organ');this.group.traverse(o=>{if(o instanceof THREE.Mesh)o.material.clippingPlanes=view==='cutaway'?[plane]:[];});}
}
