import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const origin='https://example.test/';const listeners={};const storage=new Map();let offline=false;
const caches={async open(name){if(!storage.has(name))storage.set(name,new Map());const entries=storage.get(name);const key=r=>typeof r==='string'?r:r.url||r.href;return{async put(r,res){entries.set(key(r),res.clone());},async match(r){return entries.get(key(r))?.clone();},async keys(){return [...entries.keys()].map(url=>({url}));}};},async keys(){return [...storage.keys()];},async delete(name){return storage.delete(name);}};
const shell='<!DOCTYPE html><html><body><div id="root">Chess</div><script type="module" src="./assets/app.js"></script></body></html>';
const fetch=async input=>{if(offline)throw new Error('offline');const url=typeof input==='string'?input:input.url;if(url.endsWith('.js'))return new Response('app()', {headers:{'Content-Type':'text/javascript'}});if(url.endsWith('.css'))return new Response('body{}',{headers:{'Content-Type':'text/css'}});return new Response('asset',{headers:{'Content-Type':'image/svg+xml'}});};
const self={registration:{scope:origin},location:{origin:'https://example.test'},clients:{async claim(){}},async skipWaiting(){self.activated=true;},addEventListener(name,fn){listeners[name]=fn;}};
const worker=readFileSync('polish/dist/sw.js','utf8');const build=worker.match(/const BUILD = '([^']+)'/)[1];
vm.runInNewContext(worker,{self,caches,fetch,URL,Response,AbortController,setTimeout,clearTimeout,console});
async function event(name,data={}){let pending;listeners[name]({...data,waitUntil:p=>{pending=p;}});await pending;}
const old=await caches.open('qk-offline-v15');await old.put(origin+'offline-shell.html',new Response('<script src="./assets/old.js"></script>',{headers:{'Content-Type':'text/html'}}));await old.put(origin+'assets/ancient.js',new Response('ancient()', {headers:{'Content-Type':'text/javascript'}}));await old.put(origin+'assets/old.js',new Response('old()', {headers:{'Content-Type':'text/javascript'}}));await caches.open('unrelated-app');
await event('install');assert.equal(self.activated,true);await event('activate');assert.ok(!storage.has('qk-offline-v15'));assert.ok(storage.has('unrelated-app'));assert.ok(storage.get('qk-shell-'+build).has(origin+'assets/old.js'));assert.ok(!storage.get('qk-shell-'+build).has(origin+'assets/ancient.js'));
let readiness;await event('message',{data:{type:'QK_OFFLINE_STATUS'},ports:[{postMessage:r=>readiness=r}]});assert.equal(readiness.ready,true);
offline=true;let navigation;listeners.fetch({request:{url:origin+'?room=ABC123',method:'GET',mode:'navigate'},respondWith:p=>navigation=p});assert.equal(await (await navigation).text(),readFileSync('polish/dist/offline-shell.html','utf8'));
let intercepted=false;listeners.fetch({request:{url:'https://quiet-knight-server-production.up.railway.app/rooms/ABC123',method:'GET'},respondWith(){intercepted=true;}});assert.equal(intercepted,false);
console.log('PASS complete precache, old-cache migration, old hashed asset survival, embedded offline navigation with room query, and Railway bypass');

const assetNames=worker.match(/const PRECACHE = (\[[^;]+\])/)[1];const assets=JSON.parse(assetNames);assert.ok(assets.some(p=>p.includes('computer-worker-')));for(const asset of assets)assert.ok(await (await caches.open('qk-shell-'+build)).match(origin+asset));console.log('PASS: exact built offline shell and every emitted asset, including computer worker, are cached; no Railway interception.');

// A second update retains the preceding build's own assets, not its inherited hashes.
offline=false;vm.runInNewContext(worker.replaceAll(build,'next-generation'),{self,caches,fetch,URL,Response,AbortController,setTimeout,clearTimeout,console});await event('install');await event('activate');const next=storage.get('qk-shell-next-generation');assert.ok(next);assert.ok(!next.has(origin+'assets/old.js'));assert.ok(!next.has(origin+'assets/ancient.js'));assert.equal([...storage.keys()].filter(k=>k.startsWith('qk-shell-')).length,1);console.log('PASS: current plus previous-generation manifest; orphaned hashes and inherited third-generation assets are not carried forward.');
