const {execFileSync}=require('node:child_process'),fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const adb=(...args)=>execFileSync('adb',args,{encoding:'utf8'}).trim();const sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{let browser;const pkg='com.andrefiker.onemore',apk='app/build/outputs/apk/debug/app-debug.apk';fs.mkdirSync('dist',{recursive:true});
adb('install','-r',apk);adb('install','-r','../daily-home-training/app/build/outputs/apk/debug/app-debug.apk');assert.ok(adb('shell','pm','list','packages',pkg).includes(pkg));assert.ok(adb('shell','pm','list','packages','com.andrefiker.dailyhometraining').includes('com.andrefiker.dailyhometraining'));
adb('shell','pm','clear',pkg);adb('shell','svc','wifi','disable');adb('shell','svc','data','disable');
async function connect(){adb('shell','am','start','-n',pkg+'/.MainActivity');let pid='';for(let i=0;i<20;i++){pid=adb('shell','pidof',pkg);if(pid)break;await sleep(500);}adb('forward','tcp:9222','localabstract:webview_devtools_remote_'+pid);let endpoint;for(let i=0;i<30;i++){try{let a=await (await fetch('http://127.0.0.1:9222/json')).json();endpoint=a.find(x=>x.type==='page')?.webSocketDebuggerUrl;if(endpoint)break;}catch{}await sleep(500);}if(!endpoint)throw Error('WebView debugging endpoint unavailable');browser=await chromium.connectOverCDP(endpoint.replace(/ws:\/\/[^/]+/,'ws://127.0.0.1:9222'));let p=browser.contexts()[0].pages()[0];await p.waitForFunction(()=>typeof state!=='undefined'&&typeof OneMore!=='undefined');return p;}
let page=await connect();const data=()=>page.evaluate(()=>JSON.parse(OneMore.load()));const click=a=>page.locator(`[data-action="${a}"]`).first().click();assert.equal(await page.locator('[data-action="start"][data-mode="main"]').count(),1);await page.locator('[data-action="start"][data-mode="main"]').click();assert.equal((await data()).draft.list.length,12);await click('log');await browser.close();adb('shell','input','keyevent','3');adb('shell','am','force-stop',pkg);page=await connect();assert.equal((await data()).draft.set,1,'native prefs persist after process death');await click('undo');assert.equal((await data()).draft.set,0);await click('log');await click('log');await click('next');await page.locator('#result').fill('7');await click('log');await click('log');await click('log');await click('next');
while((await data()).draft.index<12){let s=await data(),r=s.draft.list[s.draft.index];if(r.status==='done')await click('next');else{if(r.isBaseline)await page.locator('#result').fill('6');await click('log');}}await click('finish');let s=await data();assert.equal(s.sessions[0].results.length,12);assert.deepEqual(s.sessions[0].results[1].next,[[10],[11],[11]]);assert.deepEqual(s.sessions[0].results[5].next,[[7],[7],[7]]);
adb('shell','screencap','-p','/sdcard/one-more-summary.png');adb('pull','/sdcard/one-more-summary.png','dist/android-summary.png');await click('close-summary');await page.locator('[data-action="start"][data-mode="main"]').click();await click('log');await click('log');await click('next');assert.deepEqual((await data()).draft.list[1].target,[[10],[11],[11]]);adb('shell','screencap','-p','/sdcard/one-more-workout.png');adb('pull','/sdcard/one-more-workout.png','dist/android-workout.png');
// Native safe-frame bounds include status and navigation bars, even API35 edge-to-edge.
adb('shell','uiautomator','dump','/sdcard/ui.xml');let xml=adb('shell','cat','/sdcard/ui.xml');let bounds=xml.match(/class="android.webkit.WebView"[^>]*bounds="\[(\d+),(\d+)\]\[(\d+),(\d+)\]"/);assert.ok(bounds,'WebView bounds found');let [left,top,right,bottom]=bounds.slice(1).map(Number),size=adb('shell','wm','size').match(/(\d+)x(\d+)/);assert.ok(top>0,'status bar excluded');assert.ok(bottom<Number(size[2]),'navigation bar excluded');console.log('SAFE_FRAME_BOUNDS='+[left,top,right,bottom].join(','));
await browser.close();adb('shell','am','force-stop',pkg);page=await connect();assert.equal((await data()).sessions.length,1);assert.equal((await data()).draft.index,1);console.log('ANDROID_QA=PASS: fresh install, offline full workout, process-death resume, undo, baseline, failures, next targets, safe areas, coexistence');await browser.close();})().catch(e=>{console.error(e);process.exitCode=1;});
