const {execFileSync,spawnSync}=require('node:child_process'),fs=require('node:fs'),assert=require('node:assert/strict');
const adb=(...args)=>execFileSync('adb',args,{encoding:'utf8',timeout:20000}).trim(),sleep=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const pkg='com.andrefiker.onemore';fs.mkdirSync('dist',{recursive:true});adb('install','-r','dist/ONE-MORE-v1.0.0-update-fixture.apk');adb('install','-r','../daily-home-training/app/build/outputs/apk/debug/app-debug.apk');assert.ok(adb('shell','pm','list','packages',pkg).includes(pkg));assert.ok(adb('shell','pm','list','packages','com.andrefiker.dailyhometraining').includes('com.andrefiker.dailyhometraining'));adb('shell','pm','clear',pkg);adb('shell','svc','wifi','disable');adb('shell','svc','data','disable');
async function connect(){console.log(adb('shell','am','start','-W','-n',pkg+'/.MainActivity'));let pid='';for(let i=0;i<40;i++){let r=spawnSync('adb',['shell','pidof','-s',pkg],{encoding:'utf8',timeout:5000});if(r.status===0)pid=r.stdout.trim();if(pid)break;await sleep(250);}if(!pid)throw Error('App did not start: '+adb('logcat','-d','-t','200'));try{adb('forward','--remove','tcp:9222');}catch{}adb('forward','tcp:9222','localabstract:webview_devtools_remote_'+pid);let endpoint;for(let i=0;i<40;i++){try{let a=await(await fetch('http://127.0.0.1:9222/json/list',{signal:AbortSignal.timeout(2000)})).json();endpoint=a.find(x=>x.type==='page')?.webSocketDebuggerUrl;if(endpoint)break;}catch{}await sleep(250);}if(!endpoint)throw Error('WebView endpoint unavailable');let socket=new WebSocket(endpoint.replace(/ws:\/\/[^/]+/,'ws://127.0.0.1:9222'));await new Promise((r,j)=>{let t=setTimeout(()=>j(Error('CDP connection timed out')),8000);socket.onopen=()=>{clearTimeout(t);r();};socket.onerror=j;});let id=0,pending=new Map();socket.onmessage=event=>{let m=JSON.parse(event.data),p=pending.get(m.id);if(p){pending.delete(m.id);clearTimeout(p.t);m.error?p.j(Error(m.error.message)):p.r(m.result);}};function send(method,params){return new Promise((r,j)=>{let key=++id,t=setTimeout(()=>{pending.delete(key);j(Error('CDP timed out: '+method));},8000);pending.set(key,{r,j,t});socket.send(JSON.stringify({id:key,method,params}));});}async function evaluate(expression){let r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}let client={socket,evaluate};for(let i=0;i<40;i++){if(await evaluate("typeof state!=='undefined' && typeof OneMore!=='undefined' && !!document.querySelector('[data-tab=today]')"))return client;await sleep(250);}throw Error('App did not render.');}
let page=await connect();
// Exercise an actual package update from the rollback source, with native preferences intact.
const V1=require('/tmp/one-more-v1/one-more-training/app/src/main/assets/engine.js');
let legacy=V1.seed();legacy.exercises[0].name='My Jumping Jack';legacy.exercises[11].enabled=false;
V1.start(legacy,'main','2026-10-01');for(const r of legacy.draft.list){r.actual=r.target.map(row=>row.map(n=>Math.max(1,n)));r.status='done';}V1.finish(legacy);
V1.start(legacy,'main',V1.dateKey());let firstLegacy=legacy.draft.list[0];firstLegacy.actual=firstLegacy.target.map(row=>row.map(n=>Math.max(1,n)));firstLegacy.status='done';legacy.draft.index=1;
assert.equal(await page.evaluate(`OneMore.save(${JSON.stringify(JSON.stringify(legacy))})`),true);
page.socket.close();adb('shell','am','force-stop',pkg);page=await connect();assert.equal(await page.evaluate('state.schema'),1);assert.equal(await page.evaluate('loadError'),null);
page.socket.close();adb('shell','am','force-stop',pkg);adb('install','-r','app/build/outputs/apk/debug/app-debug.apk');page=await connect();
let migrated=await page.evaluate('JSON.parse(OneMore.load())');assert.equal(migrated.schema,2);assert.equal(migrated.exercises[0].name,'My Jumping Jack');assert.equal(migrated.exercises.find(e=>e.id==='seed-11').enabled,false);assert.equal(migrated.sessions.length,1);assert.equal(migrated.draft.index,1);assert.equal(migrated.draft.statuses['seed-0'],'done');assert.equal(await page.evaluate('loadError'),null);console.log('UPDATE_QA=PASS: v1.0 package updated with preferences/history/disabled movement/draft migrated');
page.socket.close();adb('shell','am','force-stop',pkg);adb('shell','pm','clear',pkg);page=await connect();const data=()=>page.evaluate('JSON.parse(OneMore.load())'),click=selector=>page.evaluate(`(()=>{let b=document.querySelector(${JSON.stringify(selector)});if(!b)throw Error('Control missing: '+${JSON.stringify(selector)});b.click();return true;})()`),action=a=>click(`[data-action="${a}"]`);await action('start');let s=await data();assert.equal(s.schema,2);assert.equal(s.draft.exerciseIds.length,8);assert.equal(await page.evaluate("!!document.querySelector('.movement-svg') && !!document.querySelector('.muscle-svg') && !!document.querySelector('.rep-button')"),true);await action('done');assert.equal((await data()).draft.index,1);page.socket.close();adb('shell','input','keyevent','3');adb('shell','am','force-stop',pkg);page=await connect();assert.equal((await data()).draft.index,1,'draft persists after process death');await action('undo');assert.equal((await data()).draft.index,0);let skippedId=(await data()).draft.exerciseIds[0];await action('skip');assert.equal((await data()).draft.statuses[skippedId],'skipped');await action('pause');assert.equal(await page.evaluate("!!document.querySelector('[data-action=continue]')"),true);await action('continue');while((await data()).draft)await action('done');s=await data();assert.equal(s.sessions.length,1);assert.equal(s.sessions[0].completedIds.length,7);assert.equal(s.sessions[0].skippedIds.length,1);const E=require('../app/src/main/assets/engine.js');assert.deepEqual(s.sessions[0].muscles,E.aggregateMuscles(s,s.sessions[0].completedIds));assert.ok(s.sessions[0].muscles.length>=5);assert.equal(await page.evaluate('document.documentElement.scrollWidth<=innerWidth+1'),true);assert.equal(await page.evaluate("document.body.innerText.includes('TODAY YOU TRAINED')"),true);adb('shell','screencap','-p','/sdcard/one-more-summary.png');adb('pull','/sdcard/one-more-summary.png','dist/android-summary-v1.1.png');
adb('shell','uiautomator','dump','/sdcard/ui.xml');let xml=adb('shell','cat','/sdcard/ui.xml'),bounds=xml.match(/class="android.webkit.WebView"[^>]*bounds="\[(\d+),(\d+)\]\[(\d+),(\d+)\]"/);assert.ok(bounds,'WebView bounds');let [left,top,right,bottom]=bounds.slice(1).map(Number),size=adb('shell','wm','size').match(/(\d+)x(\d+)/);assert.ok(top>0,'status bar excluded');assert.ok(bottom<Number(size[2]),'navigation bar excluded');console.log('SAFE_FRAME_BOUNDS='+[left,top,right,bottom].join(','));page.socket.close();adb('shell','am','force-stop',pkg);page=await connect();assert.equal((await data()).sessions.length,1);assert.equal((await data()).draft,null);assert.equal(await page.evaluate("document.body.innerText.includes('TODAY IS DONE')"),true);console.log('ANDROID_QA=PASS: fresh install + v1 update, offline one-rep workout, skip, pause/continue, visual guidance, process-death resume, undo, muscle summary, safe areas, coexistence');page.socket.close();})().catch(e=>{console.error(e);process.exitCode=1;});
