const {chromium}=require('playwright');const {createServer}=require('node:http');const fs=require('node:fs/promises');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{const assets=path.resolve('app/src/main/assets');const server=createServer(async(req,res)=>{try{let name=new URL(req.url,'http://localhost').pathname;let file=path.resolve(assets,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(assets+path.sep))throw Error();res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(await fs.readFile(file));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true});let context=await browser.newContext({viewport:{width:393,height:760},isMobile:true,hasTouch:true});let page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));let url=`http://127.0.0.1:${server.address().port}/`;
const click=action=>page.locator(`[data-action="${action}"]`).first().click();const data=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('one-more-v1')));await page.goto(url);await fs.mkdir('dist',{recursive:true});await page.screenshot({path:'dist/today.png'});await page.locator('[data-action="start"][data-mode="main"]').click();assert.equal((await data()).draft.list.length,12);await click('log');assert.equal((await data()).draft.set,1);await page.reload();assert.equal((await data()).draft.set,1);await click('undo');assert.equal((await data()).draft.set,0);await click('log');await click('log');await click('next');assert.equal(await page.evaluate(()=>scrollY),0,'next exercise starts at top');await page.screenshot({path:'dist/workout.png'});
// Miss two targets; keep them on next workout.
for(const v of [10,8,7]){await page.locator('#result').fill(String(v));await click('log');}await click('next');
while((await data()).draft.index<12){let s=await data(),r=s.draft.list[s.draft.index];if(r.status==='done'){await click('next');continue;}if(r.exercise.id==='seed-5')await page.locator('#result').fill('6');await click('log');}
await click('finish');assert.equal((await data()).sessions[0].results.length,12);let saved=await data();assert.deepEqual(saved.sessions[0].results[1].next,[[11],[10],[10]]);await page.reload();assert.equal((await data()).sessions.length,1);await page.locator('[data-tab="progress"]').click();await page.screenshot({path:'dist/progress.png'});await page.locator('[data-tab="today"]').click();await page.locator('[data-action="start"][data-mode="main"]').click();await click('log');await click('log');await click('next');assert.deepEqual((await data()).draft.list[1].target,[[11],[10],[10]]);
// Correct a previously logged set, then undo.
await click('log');await page.locator('[data-action="select-set"][data-set="0"]').click();await page.locator('#result').fill('4');await click('log');assert.equal((await data()).draft.list[1].actual[0][0],4);await click('undo');assert.equal((await data()).draft.list[1].actual[0][0],11);
// Exercise CRUD, editing, reorder, disable.
await page.locator('[data-tab="exercises"]').click();await click('add');await page.locator('[name="name"]').fill('Test exercise');await page.locator('button[type="submit"]').click();let exercise=(await data()).exercises.at(-1);assert.equal(exercise.name,'Test exercise');await page.locator(`[data-action="edit"][data-id="${exercise.id}"]`).click();await page.locator('[name="name"]').fill('Renamed exercise');await page.locator('[name="sets"]').fill('2');await page.locator('[name="bilateral"]').check();await page.locator('button[type="submit"]').click();assert.equal((await data()).exercises.at(-1).bilateral,true);await page.locator(`[data-action="move"][data-id="${exercise.id}"][data-delta="-1"]`).click();assert.equal((await data()).exercises[11].id,exercise.id);await page.locator(`[data-action="edit"][data-id="${exercise.id}"]`).click();await click('remove-request');await click('remove');assert.equal((await data()).exercises.length,12);
await page.locator('[data-tab="settings"]').click();await page.locator('[data-action="day"][data-day="2"]').click();assert.ok((await data()).schedule.includes(2));await page.locator('#theme').selectOption('light');assert.equal(await page.locator('body').getAttribute('class'),'light');await page.screenshot({path:'dist/settings-light.png'});
// Backup round-trip, validation and draft persistence.
await page.evaluate(()=>receiveBackup(JSON.stringify(state)));await click('confirm-restore');assert.equal((await data()).sessions.length,1);await page.locator('[data-tab="today"]').click();await page.reload();assert.equal((await data()).draft.list[1].actual[0][0],11);
// Easy session isolation.
await page.evaluate(()=>{state.draft=null;state.summary=null;persist();render();});let before=(await data()).sessions.filter(s=>s.mode==='main').length;await page.locator('[data-action="start"][data-mode="easy"]').click();while((await data()).draft.index<5){if((await data()).draft.list[(await data()).draft.index].status==='done')await click('next');else await click('log');}await click('finish');assert.equal((await data()).sessions.filter(s=>s.mode==='main').length,before);
await click('close-summary');for(const size of [{width:320,height:568},{width:393,height:760},{width:720,height:480}]){await page.setViewportSize(size);for(const t of ['today','progress','exercises','settings']){await page.locator(`[data-tab="${t}"]`).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true,`${t} no overflow ${size.width}`);let box=await page.locator('nav').boundingBox();assert.ok(box.y+box.height<=size.height+1);}}await page.evaluate(()=>{localStorage.setItem('one-more-v1','{broken');});await page.reload();assert.equal(await page.locator('[data-action=\"export-raw\"]').count(),1);await page.evaluate(()=>receiveBackup(JSON.stringify(OM.seed())));await click('confirm-restore');assert.equal((await data()).exercises.length,12);assert.deepEqual(errors,[]);console.log('BROWSER_QA=PASS: full workout, failures, baseline, resume, undo/edit, CRUD, schedule, themes, restore, Easy Day, three viewports');}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
