import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {structuresFromScene} from '../src/anatomy';import {computeEvent,applyDeformation,traceAnatomy,type DamageEvent} from '../src/damage';import {pickContact} from '../src/interaction';import {FractureGeometry} from '../src/fractures';import {EventReplay} from '../src/replay';import {SectionRenderer} from '../src/section';import {serializeEvents,restoreEvents,solveResponse,materialResistance,MAX_FRAGMENTS} from '../src/physics-state';
const models=await Promise.all(['torso','head'].map(async n=>{const b=await fs.readFile('public/models/'+n+'.glb');return structuresFromScene((await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'')).scene);}));const roots=[...models[0].filter(s=>s.layer!=='skin'),...models[1]];roots.forEach(s=>s.mesh.visible=s.layer==='skin');const bones=new FractureGeometry(roots),ray=(x=-.065,y=.15)=>new THREE.Raycaster(new THREE.Vector3(x,y,1),new THREE.Vector3(0,0,-1)),contact=(x=-.065,y=.15)=>pickContact(roots,ray(x,y))!;
import {SHOT_PROFILES,shotContacts,latestShot,replayShot,shotPosition} from '../src/shot-profiles';
import {GelRenderer} from '../src/gel';
import {ShotAnimation} from '../src/shot-animation';
test('shot profiles change actual traversal, not just the label',()=>{const c=contact(-.06,.12),p=computeEvent(roots,c,'projectile',1,0,[],'pistol')!,r=computeEvent(roots,c,'projectile',1,0,[],'rifle')!;assert.equal(p.physical!.path[0].energyIn,SHOT_PROFILES.pistol.energy);assert.equal(r.physical!.path[0].energyIn,SHOT_PROFILES.rifle.energy);assert.ok(r.point.distanceTo(r.end)>p.point.distanceTo(p.end));assert.ok(r.indent>p.indent);assert.notDeepEqual(r.end,p.end);});
test('scatter intersects three independent real surface points and restores one whole group',()=>{const contacts=shotContacts(roots,contact(-.06,.12),'shotgun');assert.equal(contacts.length,3);const events=contacts.map((c,i)=>{const e=computeEvent(roots,c,'projectile',1,i,[],'shotgun')!;e.shotId=0;return e;});assert.equal(new Set(events.map(e=>e.point.toArray().join())).size,3);assert.equal(latestShot(events).length,3);assert.equal(serializeEvents(restoreEvents(serializeEvents(events))),serializeEvents(events));assert.ok(restoreEvents(serializeEvents(events)).every(e=>e.point.isVector3&&e.shotId===0));const combined=replayShot(events);assert.equal(combined.physical!.contacts.length,events.reduce((n,e)=>n+e.physical!.contacts.length,0));events.splice(events.length-latestShot(events).length);assert.equal(events.length,0);});
test('flight follows each recorded path and reaches its actual terminal point',()=>{const e=computeEvent(roots,contact(),'projectile',1,0,[],'rifle')!;assert.ok(shotPosition(e,0).point.distanceTo(e.point)>.1);assert.ok(shotPosition(e,12).point.distanceTo(e.point)<.003);assert.ok(shotPosition(e,48).point.distanceTo(e.end)<.00001);const animation=new ShotAnimation();animation.setEvents([e]);animation.pose(24);const first=animation.tips[0].position.clone();animation.pose(64);animation.pose(24);assert.deepEqual(animation.tips[0].position,first);animation.clear();assert.ok(animation.group.children.every(o=>!o.visible));});
test('cavity starts behind arrival, expands locally, preserves earlier channels, and seeks exactly',()=>{const e=computeEvent(roots,contact(-.06,.12),'projectile',1,0,[],'rifle')!,g=new GelRenderer();g.update([e]);const mesh=g.group.children[0] as THREE.Mesh;g.pose(0,0);const at0=mesh.geometry.attributes.position.array.slice();assert.ok(Array.from(at0).filter((_,i)=>i%3!==2).every(v=>v===0));g.pose(32,0);const at32=mesh.geometry.attributes.position.array.slice();assert.notDeepEqual(at32,at0);g.pose(60,0);g.pose(32,0);assert.deepEqual(mesh.geometry.attributes.position.array,at32);g.pose();const final=mesh.geometry.attributes.position.array.slice();assert.notDeepEqual(final,at0);const e2={...e,id:1};g.update([e,e2]);g.pose(0,1);assert.ok(Array.from((g.group.children[0] as THREE.Mesh).geometry.attributes.position.array).some((v,i)=>i%3!==2&&Math.abs(v)>0));g.clear();});

test('recorded playback advances with wall time on slow renderers without resimulating',()=>{const e=computeEvent(roots,contact(),'projectile',1,0,[],'pistol')!,r=new EventReplay();r.event=e;r.playing=true;r.rate=.25;r.tick(.4);assert.equal(r.frame,12);assert.equal(r.clock,.1);const before=serializeEvents([e]);r.tick(.4);assert.equal(r.frame,24);assert.equal(serializeEvents([e]),before);});

import {rifleLaunch,RIFLE_INITIAL_ENERGY} from '../src/rifle-reference';
import {shotArrivalFrame} from '../src/shot-profiles';
test('rifle starting energy is derived from published mass and velocity, with an explicit illustrative unit mapping',()=>{const ref=rifleLaunch();assert.equal(ref.massKg,.008);assert.equal(ref.speedMps,738);assert.ok(Math.abs(ref.energyJ-2178.576)<1e-8);assert.equal(RIFLE_INITIAL_ENERGY,ref.energyJ/ref.joulesPerUnit);const e=computeEvent(roots,contact(-.06,.12),'projectile',1,0,[],'rifle')!;assert.deepEqual(e.launch,ref);assert.equal(e.physical!.path[0].energyIn,RIFLE_INITIAL_ENERGY);assert.equal(serializeEvents(restoreEvents(serializeEvents([e]))),serializeEvents([e]));});
test('reference replay decelerates and cavity arrival uses the same recorded timing',()=>{const e=computeEvent(roots,contact(-.06,.12),'projectile',1,0,[],'rifle')!;const path=e.physical!.path;let previous=Infinity;for(const l of path){assert.ok(l.energyIn<=previous+1e-8);assert.ok(l.energyOut>=0&&l.energyOut<=l.energyIn);previous=l.energyOut;}const total=path.reduce((s,l)=>s+l.start.distanceTo(l.end),0);for(const fraction of [0,.1,.25,.5,.75,.9,1]){const frame=shotArrivalFrame(e,fraction),point=shotPosition(e,frame).point;let distance=total*fraction,expected=e.end.clone();for(const l of path){const length=l.start.distanceTo(l.end);if(distance<=length){expected=l.start.clone().lerp(l.end,distance/length);break;}distance-=length;}assert.ok(point.distanceTo(expected)<.000001);}const fake={...e,exit:null,point:new THREE.Vector3(),end:new THREE.Vector3(0,0,-1),physical:{...e.physical!,path:[{start:new THREE.Vector3(),end:new THREE.Vector3(0,0,-1),energyIn:1,energyOut:0}]}};assert.ok(Math.abs(shotPosition(fake,30).point.z+.75)<1e-7);assert.equal(shotPosition(fake,48).point.z,-1);});
test('old recorded rifle shots retain their endpoints and timing without a new launch snapshot',()=>{const e=computeEvent(roots,contact(),'projectile',1,0,[],'rifle')!;delete e.launch;const saved=serializeEvents([e]),restored=restoreEvents(saved)[0];assert.equal(restored.launch,undefined);assert.ok(shotPosition(restored,48).point.distanceTo(e.end)<1e-8);assert.equal(shotArrivalFrame(restored,.5),30);});
test('reference rifle exit remains tied to an actual skin crossing and continues outside only after crossing',()=>{let exits=0;for(const [x,y] of [[-.06,.12],[.055,-.1],[-.08,.21],[0,.52]]){const e=computeEvent(roots,contact(x,y),'projectile',1,0,[],'rifle')!;assert.ok(e);assert.ok(e.physical!.path.length<=4);if(e.exit){exits++;assert.ok(e.exit.distanceTo(e.end)<1e-7);assert.ok(shotPosition(e,48).point.distanceTo(e.exit)<1e-7);assert.ok(shotPosition(e,60).point.distanceTo(e.exit)>0);}else assert.ok(shotPosition(e,60).point.distanceTo(e.end)<1e-7);}assert.ok(exits>0,'Reference rifle must support a genuine exit; not a hard-coded short stop');});
