import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';
import {gelTracks,gelRadius,cavityExpansion,GelRenderer,gelMaterial} from '../src/gel';
import type {DamageEvent} from '../src/damage';
const event=(id:number,offset=0)=>({id,tool:'projectile',physical:{path:[{start:new THREE.Vector3(offset,0,.15),end:new THREE.Vector3(offset,0,0),energyIn:1,energyOut:.4},{start:new THREE.Vector3(offset,0,0),end:new THREE.Vector3(offset+.05,0,-.04),energyIn:.4,energyOut:0}]}} as DamageEvent);
test('gel merges repeated channels without erasing bone deflection or adding an exit',()=>{const tracks=gelTracks([event(0),event(1)]);assert.equal(tracks.length,2);assert.ok(tracks.every(t=>t.count===2));assert.deepEqual(tracks[0].end,tracks[1].start);assert.deepEqual(tracks[1].end,event(0).physical!.path[1].end);assert.equal(gelTracks([event(0),event(1,.06)]).length,4);assert.ok(gelRadius(2)>gelRadius(1));assert.equal(gelRadius(10000),.025);});
test('gel replay is deterministic, bounded, leaves history unchanged, and reset disposes cavities',()=>{const g=new GelRenderer(),events=[event(0)],before=JSON.stringify(events);g.update(events);g.pose(28,0);const first=g.group.children.map(m=>m.scale.toArray());g.pose(67,0);g.pose(28,0);assert.deepEqual(g.group.children.map(m=>m.scale.toArray()),first);g.pose();assert.ok(g.group.children.every(m=>m.scale.x===1));assert.equal(JSON.stringify(events),before);assert.ok(Array.from({length:97},(_,i)=>cavityExpansion(i)).every(v=>v>=0&&v<=2.35));assert.equal(cavityExpansion(96),1);let disposed=0;for(const m of g.group.children as THREE.Mesh[])m.geometry.addEventListener('dispose',()=>disposed++);g.update([]);assert.equal(disposed,2);assert.equal(g.group.children.length,0);});
test('gel shell preserves double-sided entry/exit ray queries independently of visible faces',()=>{const m=gelMaterial();assert.equal(m.side,THREE.DoubleSide);const mesh=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),m);const hits=new THREE.Raycaster(new THREE.Vector3(.1,.2,2),new THREE.Vector3(0,0,-1)).intersectObject(mesh);assert.equal(hits.length,2);assert.equal(m.depthWrite,false);m.dispose();mesh.geometry.dispose();});

import {gelResistanceAt} from '../src/path-solver';
test('continuous host gel resists travel in anatomy gaps and retains an easier existing channel',()=>{const center=new THREE.Vector3(0,0,.07),events=[event(0)];assert.ok(gelResistanceAt(center,[])>.045);assert.ok(gelResistanceAt(center,events)<gelResistanceAt(center,[]));assert.equal(gelResistanceAt(new THREE.Vector3(.08,0,.07),events),gelResistanceAt(center,[]));});
