package com.ghost.screentimewidget

val awayMessages = listOf(
    "You successfully ignored several billion websites.",
    "Another successful encounter with reality.",
    "Nothing exploded while you were offline.",
    "The internet survived without you.",
    "Your phone had a small existential crisis.",
    "A little room for the rest of your life.",
    "The physical universe appreciates your visit.",
    "Your thumbs enjoyed their annual leave.",
    "Several algorithms had to entertain themselves.",
    "A notification waited. Civilization continued.",
    "You gave the feed nothing to feed on.",
    "The world outside the rectangle is still open.",
    "Your phone was beginning to think you'd moved out.",
    "An excellent episode of being elsewhere.",
    "Real life: surprisingly high resolution.",
    "No scrolling was required for that moment.",
    "You left a little silence between the pings.",
    "An unmonetized stretch of existence.",
    "The loading screen was a window.",
    "You let the pocket computer take a nap.",
    "A few pixels missed you. They'll recover.",
    "Your attention spent some time at home.",
    "Reality has no refresh button. Nice feature.",
    "The endless feed found its temporary end.",
    "A small vacation for your nervous thumbs.",
    "You were unavailable to the entire internet.",
    "The cloud managed its own affairs.",
    "A quiet gap. No subscription required.",
    "You visited a place with no comment section.",
    "Your time went somewhere besides a timeline.",
    "A screen-free chapter, quietly completed.",
    "No app needed to supervise that break.",
    "The algorithm filed a missing-thumb report.",
    "You left the refresh button unemployed.",
    "A respectable amount of being a mammal.",
    "There was life between the lock screens.",
    "Your phone practiced patience. Character building.",
    "A stretch of time with excellent privacy settings.",
    "You allowed a thought to finish loading.",
    "Reality did not ask you to accept cookies.",
    "Your attention had somewhere else to be.",
    "A little less rectangle. A little more room.",
    "The notifications formed an orderly queue.",
    "That break needed neither likes nor witnesses.",
    "Your phone discovered the joy of doing nothing.",
    "You let the internet talk amongst itself.",
    "A nice gap in the checking reflex.",
    "You spent that time beyond the glass.",
    "Your pocket held a very expensive paperweight.",
    "Somewhere, a feed refreshed for nobody.",
    "You were present somewhere the phone wasn't.",
    "A quiet interval. Yours to spend.",
    "Your attention declined a meeting with the feed.",
    "The touchscreen survived a period of loneliness.",
    "A break from the world's smallest billboard.",
    "You let curiosity look up for a change.",
    "Real life continued in airplane-to-the-feed mode.",
    "Your phone learned that waiting is possible.",
    "The apps had a perfectly adequate staff meeting.",
    "You made a little space without downloading any.",
    "A good stretch of not checking just in case.",
    "The scrolling department took a coffee break.",
    "A tiny rebellion against the infinite scroll.",
    "Your attention clocked in somewhere else.",
    "The internet remained very large without help.",
    "You left the glass door closed for a while."
)
fun reinforcementMessage(index: Long, minutes: Long): String = if(index > 0 && index % 9 == 0L) "$minutes daytime minutes with the phone locked. Room well made." else awayMessages[Math.floorMod(index,awayMessages.size.toLong()).toInt()]
