const fs=require('node:fs');const vm=require('node:vm');const assert=require('node:assert/strict');const {stripTypeScriptTypes}=require('node:module');
function js(file){return stripTypeScriptTypes(fs.readFileSync(file,'utf8')).replace(/import[^;]+;/g,'').replace(/export /g,'');}
const material=vm.runInNewContext(js('src/chess-view-model.ts')+';({materialTotals,materialValues})');
function position(fen){const out={};let i=0;for(const ch of fen.split(' ')[0])if(/[prnbqk]/i.test(ch))out[i++]={color:ch===ch.toUpperCase()?'w':'b',type:ch.toLowerCase()};return out;}
const score=fen=>JSON.stringify(material.materialTotals(position(fen)));
assert.equal(score('rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR'),'{"w":39,"b":39}');
assert.equal(score('rnbqkbnr/1pp1pppp/p2P4/8/8/8/PPPP1PPP/RNBQKBNR'),'{"w":39,"b":38}');
assert.equal(score('rnb1kbnr/1pp1pppp/p2q4/8/8/8/PPPP1PPP/RNBQKBNR'),'{"w":38,"b":38}');
const promoted=position('Qnbqkbnr/p1ppppp1/8/8/8/8/1PPPPPpP/RNBQKBNR');assert.equal(JSON.stringify(material.materialTotals(promoted)),'{"w":46,"b":33}');
assert.equal(score('Qnbqkbnr/p1ppppp1/8/8/8/8/1PPPPP1P/RNBQKBNq'),'{"w":41,"b":41}');
const before=material.materialTotals(promoted).w;delete promoted[0];assert.equal(before-material.materialTotals(promoted).w,9);
assert.equal(score('4k3/8/8/8/8/8/8/4K3'),'{"w":0,"b":0}');
async function audioHarness(enabled,options={}){let status='idle',created=0,resumes=0,started=0,closed=0;const effects=[],nodes=[];let running=false;
class Context{constructor(){created++;this.state=options.running?'running':'suspended';this.currentTime=0;this.destination={};}resume(){resumes++;if(options.blocked)return Promise.reject(Error('blocked'));return Promise.resolve().then(()=>{this.state='running';});}close(){closed++;this.state='closed';return Promise.resolve();}createOscillator(){const n={type:'',frequency:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){},start(){assert.equal(thisContext.state,'running');started++;},stop(){}};const thisContext=this;nodes.push(n);return n;}createGain(){return {gain:{setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}};}}
const hooks={useRef:v=>({current:v}),useState:v=>[v,n=>{status=n;}],useCallback:f=>f,useEffect:f=>effects.push(f)};
const sandbox={...hooks,window:{AudioContext:Context},document:{addEventListener(){},removeEventListener(){}},setTimeout,clearTimeout,Date};
const use=vm.runInNewContext(js('src/chess-audio.ts')+';useChessAudio',sandbox);const result=use(enabled,80);const cleanups=effects.map(f=>f());return {result,stats:()=>({status,created,resumes,started,closed}),dispose:()=>cleanups.forEach(f=>f?.())};}
(async()=>{let h=await audioHarness(true);assert.equal(await h.result.play(),true);assert.equal(h.stats().resumes,1);assert.equal(h.stats().started,4);assert.equal(h.stats().status,'ready');await h.result.play(true);assert.equal(h.stats().started,8);await h.result.play(false,true);assert.equal(h.stats().started,14);await h.result.play(false,false,false,true);assert.equal(h.stats().started,15);await h.result.play(true,true,false,true);assert.equal(h.stats().started,18);h.dispose();assert.equal(h.stats().closed,1);h=await audioHarness(false);assert.equal(await h.result.play(),false);assert.equal(h.stats().created,0);assert.equal(await h.result.test(),true);assert.equal(h.stats().started,4);h.dispose();h=await audioHarness(true,{blocked:true});assert.equal(await h.result.test(),false);assert.equal(h.stats().status,'blocked');assert.equal(h.stats().started,0);h.dispose();console.log('PASS: 39/39; en passant 39/38; recapture 38/38; promotions 46/33 then 41/41; promoted queen capture subtracts 9; kings excluded. PASS: awaited audio resume, move/capture/check voices, mute, explicit test, blocked resume, resource cleanup.');})().catch(e=>{console.error(e);process.exitCode=1;});
