plugins { id 'com.android.application' }
android {
    namespace 'appfarm.vao'
    compileSdk 35
    defaultConfig {
        applicationId 'appfarm.vao'
        minSdk 26
        targetSdk 34
        versionCode 5
        versionName '1.4.0'
        manifestPlaceholders = [appLabel: 'VÃO']
    }
    flavorDimensions 'channel'
    productFlavors {
        upgrade { dimension 'channel' }
        preview {
            dimension 'channel'
            applicationIdSuffix '.preview14'
            versionNameSuffix '-preview'
            manifestPlaceholders = [appLabel: 'VÃO 1.4 teste']
        }
    }
}
