plugins { id 'com.android.application' }
android {
    namespace 'appfarm.vao'
    compileSdk 35
    defaultConfig {
        applicationId 'appfarm.vao'
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName '1.2.0'
        manifestPlaceholders = [appLabel: 'VÃO']
    }
    flavorDimensions 'channel'
    productFlavors {
        upgrade { dimension 'channel' }
        preview {
            dimension 'channel'
            applicationIdSuffix '.preview12'
            versionNameSuffix '-preview'
            manifestPlaceholders = [appLabel: 'VÃO 1.2 teste']
        }
    }
}
